### PR TITLE
WIP: Add initial support for plymouth splash screen

### PR DESCRIPTION
**Pull request by zaolin**
Signed-off-by: Philipp Deppenwiese <zaolin@das-labor.org>

### CODE REVIEW

**Comment by zaolin** [comment]
Thanks good point. Can we remove libgcrypt or is it needed somehow. Normally it's optional for cryptsetup. It would safe 1.2MB

**Comment by osresearch** [comment]
I've reworked the makefile to make it easier to build the qemu ROM image (issue #37) and fixed issue #53 that prevented qemu from starting.  This makes it easier to debug, since qemu doesn't have the 4MB size issue of the real x230 ROM.  With plymouth included it prints an error when I try to run it:

```
plymouth: ply-event-loop.c:497: ply_event_loop_new: Assertion `loop->epoll_fd >= 0` failed.
```

Haven't had time to debug it further yet.

**Comment by zaolin** [comment]
Should be fixed by adding epoll to kernel config as syscall. I updated my #49 changeset to include some more syscalls..

**Comment by osresearch** [comment]
How do I test plymouth and the theme?  qemu (and chell) support 12 MB or more of payload, so we can make it there without having to squeeze into the x230's 4MB ROM.

**Comment by zaolin** [comment]
You can test the plymouth theme on your local machine or in qemu itself. Currently I am totally busy with orga stuff. Maybe I can fix the remaining issues this weekend and get it running for the 33c3

**Comment by osresearch** [comment]
I'd like to revisit this now that we have a more streamlined boot process and the coreboot to Heads to dracut to Qubes handoffs are working smoothly.  Can you rebuild the plymouth start screen and see about adding the totp or other displays to it?

**Pull request closed without merging**
