### PR TITLE
xx30 boards: suspend/resume fix

### PR DESCRIPTION
**Pull request by tlaurion**
As explained [here](https://github.com/osresearch/heads/issues/667#issuecomment-638971582) (@Thrilleratplay that NEEDS to be documented in development section/board porting...), CBFS region needs to be consistent to what is really available in IFD.

The suspend resume issues reported #770 #608, and blank screen upon internal flashing reported #737 were linked to CBFS mismatches. Thanks to @alex-nitrokey to have tested https://github.com/osresearch/heads/issues/770#issuecomment-692101135, since changing CBFS region a while ago caused this regression.

Drops:
- dropbear
- e1000e

Adds:
- hotp-verification

### CODE REVIEW

**Comment by Thrilleratplay** [comment]
@tlaurion I'll add it.

**Comment by tlaurion** [comment]
Decided to generalize the concept, since this problem SHOULD affect all boards that have the same IFD map not matching BIOS region.

from https://github.com/osresearch/heads/issues/692 listed board tester:
t430 (xx30): @flawedworld is listed as a tester. Do you suffer from suspend/resume issues also? 
the t430 coreboot config currently specifies [CONFIG_CBFS_SIZE=0x710000](https://github.com/osresearch/heads/blob/master/config/coreboot-t430.config#L8), which should show exactly the same problem.

**Comment by tlaurion** [comment]
@Thrilleratplay what platforms do you have? I see you are not listed under #692 ?

**Comment by Thrilleratplay** [comment]
@tlaurion I posted a list to #692

**Comment by tlaurion** [comment]
@Thrilleratplay So you have a T430. Is it suffering from suspend/resume issue with coreboot config specifying `CONFIG_CBFS_SIZE=0x710000` instead of `CONFIG_CBFS_SIZE=0x700000`?

**Comment by tlaurion** [comment]
Ci failing for coreboot 4.12 not downloading.... Retrying until it passes.

**Comment by Thrilleratplay** [comment]
@tlaurion It is a device I use mostly for checking standard coreboot configs when updating [coreboot-builder-scripts](https://github.com/Thrilleratplay/coreboot-builder-scripts/blob/master/t430/defconfig) and uses `CONFIG_CBFS_SIZE=0x400000`.  I will be a while before I can test this.

**Comment by tlaurion** [comment]
@Thrilleratplay : I will then consequently clone the x230 coreboot config and define the board with same coreboot base. It would not make any sense that it works. Just a false negative from lack of response from board users, based on this [post](https://github.com/osresearch/heads/issues/667#issuecomment-638971582). That region cannot be larger then CONFIG_CBFS_SIZE=0x700000 if IFD is not resized from liberated ME neutered and freed space, which is another debate and should be another board config, unless #703 is generalized, for which we don't have consensus yet.

**Comment by tlaurion** [comment]
TODO: cherry pick https://github.com/Nitrokey/heads/commit/ad75d8e36b87c3b3aac3eb1f863cb0f1a88a0b8d, extend and comment linking to https://github.com/osresearch/heads/issues/667#issuecomment-638971582

Will fix #770 

""

**Comment by tlaurion** [comment]
Oups..... needs rebase on master
```
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[1]: *** [Makefile:1110: insn-emit.o] Error 1
make[1]: *** Waiting for unfinished jobs....
rm gcc.pod
make[1]: Leaving directory '/root/project/build/coreboot-4.12/util/crossgcc/build-i386-elf-GCC/gcc'
make: *** [Makefile:4244: all-gcc] Error 2
```

**Comment by tlaurion** [comment]
I confirm the fix for x230 and x230-hotp-verification.
I think it is a safe bet to generalize that it should also fix for t430.

@flawedworld, please test master when you have a second (artifacts from CIs are downloadable through the little green checkmark beside each commit)

**Pull request merged**
