### PR TITLE
Make gnupg pubkey export an option only in oem-factory-reset

### PR DESCRIPTION
**Pull request by alex-nitrokey**
Since #758 is merged, users have a option to export GnuPG pubkey if
necessary. Thus, we they do not need to insert a USB drive during
factory reset. Until now the whole process failed just because a user
did not provide a USB drive instead.

This shall be fixed by this commit

### CODE REVIEW

**Comment by tlaurion** [comment]
As wrongly wrote (sorry) in #764 :
>@alex-nitrokey : I would prefer having mount-usb from preceded with a prompt prior of exporting the keys and keep factory-reset outputing normally to /media if not already mounted.

>I will merge my changes to that script in subsequent PR for the reownership wizard to work with upstreamed code, and to me it doesn't really make sense to have a factory reset without exporting the public key.

So in this case, I would set the default to N in the factory-reset script prompt, detect if there is USB drive and not fail but continue?

**Comment by alex-nitrokey** [comment]
> So in this case, I would set the default to N in the factory-reset script prompt, detect if there is USB drive and not fail but continue?

Sounds good to me!

**Comment by alex-nitrokey** [comment]
To add: I am preparing a commit accordingly.

**Comment by alex-nitrokey** [comment]
This should be fine now :)

**Comment by tlaurion** [comment]
@alex-nitrokey : conflict needs to be resolved prior of merging and testing

**Comment by alex-nitrokey** [comment]
Should be good to go again now :)

**Comment by tlaurion** [comment]
Works as intended.

**Pull request merged**
