### PR TITLE
[WIP] Make X230 and T430 use a universal flash-stage init

### PR DESCRIPTION
**Pull request by snmcmillan**
Let's try #579 again, this time with less broke.

This will replace separate `$CONFIG_BOARD-flash.init` files with a single `flash.init` file to reduce the clutter in the heads initrd and streamline the xx30 ThinkPads.

Affected boards at this time are T430 and X230. Testing has yet to be done on X230 or T430. I'll test on X230 when I can get a system that can actually build heads (Debian Sid is not able to build heads currently).

@flawedworld can you test to make sure t430-flash is still working as intended?

### CODE REVIEW

**Comment by tlaurion** [comment]
@SebastianMcMillan this PR is not clean :)

```
git fetch osresearch
git checkout osresearch/master
git reset --hard
git branch -D universal-flash-init
git checkout universal-flash-init

```

Verify following patch which from what I understood should touch only 3 files, put it under ./heads/seb.patch:
```
diff --git a/boards/t430-flash/t430-flash.config b/boards/t430-flash/t430-flash.config
index 43be7cb..4c92ab2 100644
--- a/boards/t430-flash/t430-flash.config
+++ b/boards/t430-flash/t430-flash.config
@@ -13,7 +13,7 @@ CONFIG_LINUX_CONFIG=config/linux-x230-flash.config
 CONFIG_LINUX_USB=y
 CONFIG_LINUX_E1000E=y
 
-export CONFIG_BOOTSCRIPT=/bin/t430-flash.init
+export CONFIG_BOOTSCRIPT=/bin/flash.init
 export CONFIG_FLASHROM_OPTIONS="--force --noverify-all -p internal --ifd --image bios"
 
 # This board is "special" in that we only want the top 4 MB of the ROM
diff --git a/boards/x230-flash/x230-flash.config b/boards/x230-flash/x230-flash.config
index edb417e..39c8db7 100644
--- a/boards/x230-flash/x230-flash.config
+++ b/boards/x230-flash/x230-flash.config
@@ -18,7 +18,7 @@ CONFIG_LINUX_CONFIG=config/linux-x230-flash.config
 CONFIG_LINUX_USB=y
 CONFIG_LINUX_E1000E=y
 
-export CONFIG_BOOTSCRIPT=/bin/x230-flash.init
+export CONFIG_BOOTSCRIPT=/bin/flash.init
 export CONFIG_FLASHROM_OPTIONS="--force --noverify-all -p internal --ifd --image bios"
 
 # This board is "special" in that we only want the top 4 MB of the ROM
diff --git a/initrd/bin/t430-flash.init b/initrd/bin/flash.init
similarity index 92%
rename from initrd/bin/t430-flash.init
rename to initrd/bin/flash.init
index 9b97970..a115e74 100755
--- a/initrd/bin/t430-flash.init
+++ b/initrd/bin/flash.init
@@ -20,7 +20,7 @@ echo ''
 echo 'To install from flash drive:'
 echo ''
 echo '  mount -o ro /dev/sdb1 /media'
-echo '  flash.sh /media/t430.rom'
+echo '  flash.sh /media/$CONFIG_BOARD.rom'
 echo ''
 
 exec /bin/ash
 
diff --git a/initrd/bin/x230-flash.init b/initrd/bin/x230-flash.init
deleted file mode 100755
index 0ba456f..0000000
--- a/initrd/bin/x230-flash.init
+++ /dev/null
@@ -1,26 +0,0 @@
-#!/bin/sh
-# Initialize the USB and network device drivers,
-# invoke a recovery shell and prompt the user for how to proceed
-
-. /etc/functions
-. /tmp/config
-
-insmod /lib/modules/ehci-hcd.ko
-insmod /lib/modules/ehci-pci.ko
-insmod /lib/modules/xhci-hcd.ko
-insmod /lib/modules/xhci-pci.ko
-insmod /lib/modules/e1000e.ko
-insmod /lib/modules/usb-storage.ko
-
-tpm extend -ix 4 -ic recovery
-sleep 2
-
-echo '***** Starting recovery shell'
-echo ''
-echo 'To install from flash drive:'
-echo ''
-echo '  mount -o ro /dev/sdb1 /media'
-echo '  flash.sh /media/x230.rom'
-echo ''
-
-exec /bin/ash
```
Then apply it on top of clean master:
`patch -p1 < seb.patch`

`git add`, `git commit`
the force update of your original PR with same branch name:
`git push --force seb-github`

**Comment by tlaurion** [comment]
On a side note, i'm not sure how this universal flash script should pick up usb devices if the modules are not loaded prior of calling flash.sh script?
```

-. /etc/functions
-. /tmp/config
-
-insmod /lib/modules/ehci-hcd.ko
-insmod /lib/modules/ehci-pci.ko
-insmod /lib/modules/xhci-hcd.ko
-insmod /lib/modules/xhci-pci.ko
-insmod /lib/modules/usb-storage.ko
```
Here, insmod is a bash wrapper defined under functions which modified PCR with module hash prior of really insmod module, invalidating measurements so secret can't be released. It is impossible to mount /dev/sdb1 if usb-storage is not present, which depends on USB dev types, made avail by insmodding EHCI, XHCI, then usb-storage.

mount-usb takes care of that altogether, I thin (not tested in flash env, but should) while calling `recovery` if ./etc/functions is imported should also take care of modifying additional PCR to say we are in recovery, nor in normal boot, modifying measurements. 

I think the same logic should be the same everywhere so people get how Heads work, else confusion arises on internal security mechanisms and their applications.

**Comment by SebastianMcMillan** [comment]
I can fix the USB mounting as well. The flash.init is completely unchanged
other than it being board-agnostic currently.

**Comment by tlaurion** [comment]
@SebastianMcMillan needs clean rebase, contains a lot of unrelated changes.

**Comment by tlaurion** [comment]
Implemented at https://github.com/osresearch/heads/commit/30963e121fc172f82fa1b490f2713ab22d29a44f

**Pull request closed without merging**
