### PR TITLE
Bump Librem and KGPE-D16 to Linux 5.10.5

### PR DESCRIPTION
**Pull request by Tonux599**
Supersedes #946.

Bumps Librem boards and KGPE-D16 to Linux 5.10.5. This generally brings better graphics support.

A note has been added that explicitly says linuxboot systems should **not** use 5.10.5 until a proper review has been done, as `0000-efi_bds.patch` does not cleanly port.

KGPE-D16's microcode has been removed. This is due to a bug where Linux panic's when using microcode that has been loaded by Coreboot from the CBFS. AMD Opteron 6300 series should be stable enough in the Heads environment and microcode can be loaded by the chainloaded operating system; a note has been added in KGPE-D16's configs encouraging them to do so.

Marking this PR as draft for the moment as not had a chance to test yet.

### CODE REVIEW

**Comment by Tonux599** [comment]
Okay built locally for `kgpe-d16_workstation` and flashed to my main workstation. Appears to work well.

@MrChromebox will open for your review, hopefully you have the same success I have.

@tlaurion @zifxify @blobless @0rb677 if you want to test:
* [kgpe-d16_server-whiptail](https://62-254229935-gh.circle-artifacts.com/0/build/kgpe-d16_server-whiptail/heads-kgpe-d16_server-whiptail-v0.2.0-1009-g31edd87.rom)
* [kgpe-d16_server](https://62-254229935-gh.circle-artifacts.com/0/build/kgpe-d16_server/heads-kgpe-d16_server-v0.2.0-1009-g31edd87.rom)
* [kgpe-d16_workstation-usb_keyboard](https://62-254229935-gh.circle-artifacts.com/0/build/kgpe-d16_workstation-usb_keyboard/heads-kgpe-d16_workstation-usb_keyboard-v0.2.0-1009-g31edd87.rom)
* [kgpe-d16_workstation](https://62-254229935-gh.circle-artifacts.com/0/build/kgpe-d16_workstation/heads-kgpe-d16_workstation-v0.2.0-1009-g31edd87.rom)

**Comment by MrChromebox** [comment]
only issue I'm seeing with the 5.10 kernel vs 5.4 is that the Disk Info line under System Info needs some reformatting, due to the change in output of `fisk -l ...` in gui-init. with 5.10, the sector count got added in, which is pretty useless and just takes up space

**Comment by MrChromebox** [comment]
actually, it looks like this change slipped in with the busybox bump to 1.32.0, so it's a separate issue. I'll open a PR for it once I figure out how to fix the mess

**Comment by MrChromebox** [comment]
so looks like this breaks virtualization (virt-manager or gnome-boxes, Qubes as well) on Librems, going to have to roll back to 5.4.69 until I have time to figure it out

**Comment by Tonux599** [comment]
> so looks like this breaks virtualization (virt-manager or gnome-boxes, Qubes as well) on Librems, going to have to roll back to 5.4.69 until I have time to figure it out

@MrChromebox all seems well KGPE-D16 end and Qubes works well. It shouldn't affect virtualization as the heads Linux environment should have no impact on what CPU features are reported to a kexec'd kernel. Very strange.

**Comment by MrChromebox** [comment]
I've verified it here, and several Purism users have experienced it as well.

ref: https://forums.puri.sm/t/pureboot-16-and-virtualization/12303

**Comment by MrChromebox** [comment]
@Tonux599 I'd guess it's a kernel config issue then, a change in defaults or addition between 5.4.x and 5.10.x

**Pull request merged**
