### PR TITLE
modules/flashrom: update to v1.2 release

### PR DESCRIPTION
**Pull request by MrChromebox**
- Update flashrom module to v1.2.
- Drop Thinkpad x220 patch as it's now properly supported.
- Drop 'laptop=force_I_want_a_brick' from board FLASHROM_OPTIONS
  since it's no longer needed.
- Migrate kgpe-d16 patch.

The kgpe-d16 patch needed a complete overhaul when rebased against
flashrom v1.2, and needs close inspection/testing as a result.
The following changes were made from the previous patch:

- dropped addition of 4-byte addressing (4BA), since now supported
- dropped addtiion of Macronix MX25L256 and MX66L512 chips,
  since now supported
- added 4BA erase commands for Winbond W25Q256 chip
- dropped code to show progress indicator, since another PR already adds that

Signed-off-by: Matt DeVillier <matt.devillier@puri.sm>

### CODE REVIEW

**Comment by tlaurion** [comment]
@mrchromebox ping?

**Comment by MrChromebox** [comment]
@tlaurion I can go ahead and do the last 2 items, but unsure about the kgpe-d16.  Need someone with one to see if patch still needed

**Comment by MrChromebox** [comment]
pushed a quick update, took a quick look at the kgpe-d16 patch and it is still needed, I'll massage it as needed tomorrow and push a new patch

**Comment by MrChromebox** [comment]
@flammit mind marking as reviewed and noting what board(s) you tested on?

**Comment by tlaurion** [comment]
May break #335

**Pull request merged**
