### PR TITLE
feat(busybox): set CONFIG_BASH_IS_ASH

### PR DESCRIPTION
**Pull request by Thrilleratplay**
enable CONFIG_BASH_IS_ASH

Part of #885 and should be included with #900

### CODE REVIEW

**Comment by tlaurion** [comment]
@Thrilleratplay : impact?

**Comment by tlaurion** [comment]
https://www.in-ulm.de/~mascheck/various/ash/#busybox :
```
compile time option ("ASH_BASH_COMPAT", active per default) for several bash compatibility features:
option pipefail, substring and replacement parameter expansion ${x:y:z} and ${x/y/z}, [[, source, $'...', &>
```

**Comment by Thrilleratplay** [comment]
@tlaurion From everything I can determine, none.  This seems to only creates a symlink from `/bin/ash` to `/bin/bash`.  `CONFIG_ASH_BASH_COMPAT` is a different config, providing Bash like comparability in Ash, and is already enabled.  It is because `CONFIG_ASH_BASH_COMPAT` is enabled that `CONFIG_BASH_IS_ASH` has no impact.  Allowing scripts with shebangs `#!/bin/bash` to be used in initrd scripts and making shellcheck, which does not have ash compatibility, usable.

**Comment by tlaurion** [comment]
@Thrilleratplay haha!

**Pull request merged**
