### PR TITLE
Add support for the Thinkpad T430s

### PR DESCRIPTION
**Pull request by petabyteboy**
It boots into Heads fine, but everything else is untested.
GUI is borked, only half of the content is visibale, so it is disabled for now.

### CODE REVIEW

**Comment by tlaurion** [comment]
@petabyteboy : 
- Please post picture of borked graphic with gui-init in seperate issue. I haven't reviewed differences between linux/coreboot configs and x230's yet.

**Comment by petabyteboy** [comment]
Yeah I first copied the kernel config from the X230 without changes, that gave me the borked result.

**Comment by petabyteboy** [comment]
I fixed the graphics glitch by re-enabling libgfxinit. 
I have also tested tpm and gpg functionality, it all works as expected.
Only the flash-x230.sh script does not work as it is yet.

**Comment by tlaurion** [comment]
Please collaborate and test #656

**Comment by SebastianMcMillan** [comment]
@tlaurion this is a different device! T430s is different from T430.

**Comment by tlaurion** [comment]
Sorry, meant #723

**Pull request closed without merging**
