### PR TITLE
Branding proposition + d-wid logo/bootsplash

### LINKED ISSUE #1468: Adapt configs to ease rebranding
By default, Heads branding is 'Heads': 
https://github.com/osresearch/heads/blob/59972f39728a95fc2926c598d7356a0aea092884/Makefile#L13

This partly overrides both Linux version and coreboot version. 

It is currently applied for librem boards (**missing for all other boards**):

Linux config: https://github.com/osresearch/heads/blob/59972f39728a95fc2926c598d7356a0aea092884/config/linux-librem_common-6.1.8.config#L1

coreboot config override: https://github.com/osresearch/heads/blob/59972f39728a95fc2926c598d7356a0aea092884/modules/coreboot#L78

Note that SMBIOS name is matching board name only as if now: https://github.com/osresearch/heads/blob/59972f39728a95fc2926c598d7356a0aea092884/modules/coreboot#L79

Do we want to adapt this?
- [ ] replicate librem branding in Linux config
- [ ] extend to agreed scheme

### PR DESCRIPTION
**Pull request by tlaurion**
This PR is an attempt to fix #1468 by adapting #1502 from @d-wid amazing work.

@JonathonHall-Purism would like to hear from you on Makefile change and branding/Heads directory and qemu config used as example to use the default brand_name.

@d-wid : this PR works, but as stated inside of the commit message here:
- the xcf is too big to be accepted under master: that would add 4mb of download to anyone downloading the heads tree. We need to make sure that what is accepted, even more when binary data, is not gonna change much in the future.
- the commit message of the squash commit under #1502 should be clearer and the filenames referencing the authors of the images. Please read commit and ping me if its possible for you to change the commit message/filenames to reflect this. If not, please challenge me on the xcf utility (not a designer here) to justify presence under git tree forever.

I would then take your work, and modify this PR accordingy to have all coreboot configs point to the bootsplash as depicted by this PR and modify Makefile following remarks here and either merge this PR and or yours to have proper branding with logo/bootsplashes produced.

@d-wid sorry for those back and forths!

### CODE REVIEW

**Comment by d-wid** [comment]
>     * the xcf is too big to be accepted under master: that would add 4mb of download to anyone downloading the heads tree. We need to make sure that what is accepted, even more when binary data, is not gonna change much in the future.

Hi, I don't actually expect the xcf (from which all the jpges were sourced, with some layer manipulation) to be merged into master. The idea is that that PR serves as a repository of what I come up with, the xcf is there so that people can build on it (in the exact same way I did on the original from @Thrilleratplay ), or change the donation QR code etc without applying the JPEG compression again. Same idea with the svg. If you want to put it somewhere on the readme, website etc you can, and in any size you want, but it's obviously not a splash image.

I guess I could remove the xcf and put it in my own repo somewhere, if that works. Otherwise would you (all) prefer a new jpg-only or xcf-only PR right here to keep xcf inside the Heads github in some form?

Is the plan to merge all the jpegs? My first gut feeling is that it might be a bit much, but in that case I think @ThePlexus gets the credit for the box if I remember correctly.

**Comment by tlaurion** [comment]
> ~I guess I could remove the xcf and put it in my own repo somewhere, if that works. Otherwise would you (all) prefer a new jpg-only or xcf-only PR right here to keep xcf inside the Heads github in some form?~ Oh wait. This is the "another PR" you referred to in #1502. In that case yeah, I see no reason for the xcf to stay here from a purely end user POV.
> 
> Is the plan to merge all the jpegs? In that case I think @ThePlexus gets the credit for the box if I remember correctly.
> 
> > properly credit previous authors in the present PR?
> 
> What do you mean by properly? In any case @Thrilleratplay probably gets credit for all the images since they're all just new layers on top of some of his existing ones (though it's not always the case anymore that any of his layers remain visible, not sure how that works but probably not something I ought to stress about too much?). The box versions were copied from @ThePlexus , and the Heads logo used (and the colour scheme in the tricolour version) gets credited to Microsoft of all people lol.

I think I addressed all comments but squashing my commit and #1502 on previous commit. Next commit will squash both and remove you as author to be able to remove the xcf.

@ThePlexus @Thrilleratplay @d-wid Please look at branding/Heads/CREDITS and let me know if something is wrong.

**Comment by tlaurion** [comment]
> Next commit will squash both and remove you as author to be able to remove the xcf so merging will not pollute history with binary image. I think CREDITS does a good job referencing Bing, authors and remixers, let me know.

Nicer then I thought. @d-wid we are now co-authors on commit last commit here after squashing your commit with mine.

**Comment by tlaurion** [comment]
This is what it looks like with currently selected default on qemu

**Comment by JonathonHall-Purism** [comment]
> @JonathonHall-Purism would like to hear from you on Makefile change and branding/Heads directory and qemu config used as example to use the default brand_name.

Thanks!  I think this is a pretty reasonable approach.  It's nice to tie the brand name and bootsplash together since they are related.

**Comment by tlaurion** [comment]
@d-wid @Thrilleratplay @ThePlexus : a quick review on CREDITS file please?

**Comment by d-wid** [comment]
It would be more correct to say that the svg (instead any of the jpegs into which the svg was imported) was the result of Inkscape automatically smoothing out a the Bing image (after I made it all black with gimp). Bing itself didn't spit out anything in vector form after all.

Otherwise I think it looks alright.

**Comment by tlaurion** [comment]
> It would be more correct to say that the svg (instead any of the jpegs into which the svg was imported) was the result of Inkscape automatically smoothing out a the Bing image (after I made it all black with gimp). Bing itself didn't spit out anything in vector form after all.
> 
> Otherwise I think it looks alright.
> 
> On 4 October 2023 21:12:40 UTC, tlaurion ***@***.***> wrote:
> >@d-wid @Thrilleratplay @ThePlexus : a quick review on CREDITS file please? 
> >
> >-- 
> >Reply to this email directly or view it on GitHub:
> >https://github.com/osresearch/heads/pull/1506#issuecomment-1747649115
> >You are receiving this because you were mentioned.
> >
> >Message ID: ***@***.***>
> 

Any direct change you ant to see @d-wid

**Comment by d-wid** [comment]
Something along the lines of:

bing-d-wid_logo.svg: Heads Logo generated by Bing's AI on August 03 2023 with prompt "Double Headed Janus Logo for Heads Open Source Firmware" shared under https://github.com/osresearch/heads/issues/1402#issuecomment-1664636591 *edited with GIMP and traced with Inkscape*

bing-d-wid_heads-red_blue_background-plain-3_DonateQrCode.jpg: @d-wid remix of Bing's Heads logo + DonateQrCode

**Comment by Thrilleratplay** [comment]
@tlaurion I appreciate offering credit for the trivial bit of a background I threw together by sending one of the coreboot source files (I can't remember which) into a binary encoder and pasting into GIMP, but feel it is unwarranted.  Had I not been so busy the past few days, I would have said not to bother mentioning me.  Oh well.  Thank you.  These look awesome.

**Comment by tlaurion** [comment]
@d-wid sorry for delay.
https://github.com/osresearch/heads/pull/1506/commits/aaf869890e7f64574059c1a030eda98e1f803ab4 looks fine?

**Comment by d-wid** [comment]
Yeah I think so.

I meant for the "*" characters to result in italics in the above comment instead of appearing in the txt file and the last three pictures might also need "+DonateQrCode" added to them but those are minor points not worth getting boddeg down over.

**Pull request merged**
