### PR TITLE
x230-maximized boards: build against coreboot 4.13

### PR DESCRIPTION
**Pull request by tlaurion**
Smaller step to #944 since t430 hypothesized to not boot. x230 only here.

### CODE REVIEW

**Comment by bwachter** [comment]
After spending way too long on this because parallel builds are broken I didn't get past the kernel compilation step:

```
$ make BOARD=x230-maximized build=/tmp/heads
[...]
make[2]: Leaving directory '/tmp/heads/coreboot-4.13'
2021-01-04 13:35:08+00:00 CONFIG coreboot
/tmp/heads/make-4.2.1/make \
        -C "/tmp/heads/linux-4.14.62" \
        INSTALL_HDR_PATH="/home/bwachter/git/misc/heads/install" \
        O="linux-4.14.62/linux-x230" \
        KCONFIG_CONFIG="/home/bwachter/git/misc/heads/config/linux-x230.config" \
        headers_install
make[2]: Entering directory '/tmp/heads/linux-4.14.62'
make[3]: Entering directory '/tmp/heads/linux-4.14.62/linux-4.14.62/linux-x230'
  CHK     include/generated/uapi/linux/version.h
make[4]: *** No targets specified and no makefile found.  Stop.
make[3]: *** [/tmp/heads/linux-4.14.62/Makefile:463: scripts_basic] Error 2
make[3]: Leaving directory '/tmp/heads/linux-4.14.62/linux-4.14.62/linux-x230'
make[2]: *** [Makefile:146: sub-make] Error 2
make[2]: Leaving directory '/tmp/heads/linux-4.14.62'
make[1]: *** [modules/linux:47: /home/bwachter/git/misc/heads/install/include/linux/limits.h] Error 2
make[1]: Leaving directory '/home/bwachter/git/misc/heads'
make: *** [Makefile:648: all] Error 2
```

**Comment by tlaurion** [comment]
@bwachter can you elaborate? CI builds are building with 
`make BOARD=x230-maximized CPUS=4 V=1` without error as of right now, where #935 seems to be a thing, where I was't able to reproduce.

**Comment by tlaurion** [comment]
@bwachter CircleCI building each commit is on debian-10. What is your host OS?
(Note that #950 should be merged, which stops CIs builds to randomly fails because of some gnu mirrors having bad https certs right now)

**Comment by tlaurion** [comment]
@bwachter never specified `build=` before either.

**Comment by tlaurion** [comment]
Rebasing on top of https://github.com/osresearch/heads/pull/950 for CI build (click green mark on next commit to go see live build and download produced artifacts). Lost too many days waiting for GNU to ban some non-compliant mirrors.

**Comment by tlaurion** [comment]
@bwachter 
https://755-103208611-gh.circle-artifacts.com/0/build/x230-maximized/heads-x230-maximized-v0.2.0-999-gc475958-bottom.rom
https://755-103208611-gh.circle-artifacts.com/0/build/x230-maximized/heads-x230-maximized-v0.2.0-999-gc475958-top.rom
https://755-103208611-gh.circle-artifacts.com/0/build/x230-maximized/heads-x230-maximized-v0.2.0-999-gc475958.rom

**Comment by bwachter** [comment]
I was trying to set MAKE_JOBS, as CPUS should get set in the Makefile, but I assume it's also not being propagated - when invoking make with CPUS set it does seem to work. That should be fixed (or at least documented), it's rather unexpected that -j doesn't work, no sensible amount of parallel tasks started automatically, and nothing mentioned in build instructions.

Still running into the same error building the Linux kernel, though. Full build log for `make BOARD=x230-maximized CPUS=64 build=/tmp/heads` on suse tumbleweed attached.

[heads-build.log](https://github.com/osresearch/heads/files/5768763/heads-build.log)

**Comment by tlaurion** [comment]
@bwachter i'm sorry, I do not use tumbleweed, which is a rolling release and you will probably hit problems no one else met.
What I see from the log you posted is that the Heads Makefile stops after installing linux kernel headers, while BOARD seems not to be passed.

From the OP
`make[3]: *** [/tmp/heads/linux-4.14.62/Makefile:463: scripts_basic] Error 2`

Which is
```
scripts_basic:
        $(Q)$(MAKE) $(build)=scripts/basic
        $(Q)rm -f .tmp_quiet_recordmcount

```

To me, it seems that you passing `build=/tmp` is confusing the build environment. Could you retry without it? Or clone Heads under /tmp completely, so that you build in RAM if that is what you intend to do? Of use docker image as in CircleCI to build on Debian-10? Can you confirm that you have the host tools equivalents as in working CircleCI recipe?

```
cd /tmp/heads
git clone https://github.com/osresearch/heads
cd heads
make BOARD=x230-maximized CPUS=64
```

report back

**Comment by bwachter** [comment]
On a leap 15.1 I have it failing late at the blobs (which is expected, as I didn't put anything there yet). Difference is make 4.2.1 vs make 4.3. I pretty much never run into toolchain issues on tumbleweed, and if I do it's generally rather obvious issues with the compiler or libraries. I'd recommend adding at least occasional builds on other distributions to CI and fix up the build system to behave better - that kind of very specific toolchain dependency tends to become a big burden and ties projects to outdated distributions for building eventually.

**Comment by tlaurion** [comment]
Needs https://github.com/osresearch/heads/pull/954 related changes

**Comment by tlaurion** [comment]
@bwachter I can't build  in memory like you do with `build=/tmp/heads`

Please retry and report by doing:
`make BOARD=x230-maximized CPUS=64 V=1` and post back results.

Note the successful CI build recipe:
1- [build requirements](https://github.com/osresearch/heads/blob/0d5b3d75e7b84ca85ff252fe5fe23aea990da435/.circleci/config.yml#L8-L11) 
2- [Blobs placed in searched blobs dirs prior of coreboot module being built](https://github.com/osresearch/heads/blob/0d5b3d75e7b84ca85ff252fe5fe23aea990da435/.circleci/config.yml#L428-L430)
3- [make call to build with 4 CPUS](https://github.com/osresearch/heads/blob/0d5b3d75e7b84ca85ff252fe5fe23aea990da435/.circleci/config.yml#L434) having debugging trace.

From the log you [pasted](https://github.com/osresearch/heads/files/5768763/heads-build.log), my eyes see no error to work on. My best hypothesis is that building in memory doesn't seem to be a passed argument, where I can't replicate easily (CIs won't accept to take that much memory)

**Comment by tlaurion** [comment]
Considering the comments here are linked to buildsystem errors that can be mitigated per instructions, and not specific to this x230 board being bumped to coreboot 4.13, unless opposition, I will merge this PR in the following days.

**Comment by tlaurion** [comment]
> make BOARD=x230-maximized CPUS=64 build=/tmp/heads

@bwachter : this issue should be filed into another issue  called : "Cannot build in memory" and/or "Cannot build in Tumbleweed".

Successfull builds are happening https://circleci.com/gh/osresearch/heads at each merged commit on top of debian-10 docker image following CircleCI file provided in tree.

**Comment by tlaurion** [comment]
@mrchromebox: 
https://app.circleci.com/pipelines/github/tlaurion/heads/733/workflows/a983f0a3-023f-4879-851f-027e775a6bf8/jobs/1092/artifacts build of Heads based on coreboot 4.13 boots QubesOS 4.0.4 iso and installed OS.

Rom tested:
full rom flashed: https://1092-103208611-gh.circle-artifacts.com/0/build/x230-hotp-maximized/heads-x230-hotp-maximized-v0.2.0-1040-gaf87971.rom

Bottom:
https://1092-103208611-gh.circle-artifacts.com/0/build/x230-hotp-maximized/heads-x230-hotp-maximized-v0.2.0-1040-gaf87971-bottom.rom
Top:
https://1092-103208611-gh.circle-artifacts.com/0/build/x230-hotp-maximized/heads-x230-hotp-maximized-v0.2.0-1040-gaf87971-top.rom

**Comment by MrChromebox** [comment]
@tlaurion thx for testing. Will have to try and figure out why Qubes 4.0.4 hangs with coreboot 4.11+ on Librem 13/15s then (no issue on Mini v1/v2/L14)

**Comment by tlaurion** [comment]
Superseded by https://github.com/osresearch/heads/pull/1015

**Pull request closed without merging**
