### PR TITLE
CircleCi on ubuntu 2104

### PR DESCRIPTION
**Pull request by tlaurion**
CircleCI was stuck to debian 10 for a while.
Thanks @bluecmd and @itworksfinebro for individual proposed fixes, that merged together in this PR, should permit building of older boards on newer OSes.

This PR:
- Attempts inclusion of #1035 
- Automates manual fix proposed by @itworksfinebro #983 (comment) in form of coreboot 4.8.1 and 4.11 patches
- Removes manual https to http patch that was pushed in emergency when upstream mirrors were not upgrading their certs while I was doing build tests back in time.

Should fix :
#983
#1036

Close #1035

Waiting for the result of the build here. My CircleCI is rate limiting threads since i'm overusing my instance. Pushing it as PR should use @osresearch's and give faster result.

### CODE REVIEW

**Comment by MrChromebox** [comment]
@tlaurion why are we not bumping iasl for coreboot 4.11 the same as we are for 4.81?

On the Librem 13/15 with Heads built using coreboot 4.9+, Qubes 4.0.x freezes right after kexec with no useful output. I'll retest with coreboot 4.14 and Qubes 4.1 RC and report back

**Comment by tlaurion** [comment]
> @tlaurion why are we not bumping iasl for coreboot 4.11 the same as we are for 4.81?
> 

Could definitely give it a try for 4.11.... But for the moment, I have no clue on how to make 4.8.1 support forward. Could swap boards builds on CI so that a 4.11 board is built first bumping IASL. Patches welcome.

**Comment by tlaurion** [comment]
Before merge:

-[] 4.8.1 boards needs to compile or boards need to be upgraded to 4.13+

-[] 4.11 kgpe-16 CiecleCI artifact needs to be tested

**Comment by MrChromebox** [comment]
> @MrChromebox have your confirmed https://1959-103208611-gh.circle-artifacts.com/0/build/librem_l1um/heads-librem_l1um-v5.0.1-53-ga57e41b.rom works as expected too?

yes, tested working

**Comment by tlaurion** [comment]
@MrChromebox 4.8.1 coreboot builds on newer OSes is stuck here with current patchset https://github.com/osresearch/heads/pull/1038#issuecomment-943721373

**Comment by tlaurion** [comment]
Next

**Comment by tlaurion** [comment]
Was fixed a while ago, circleci being based on debian-11 and the only supported path as of now.

**Pull request closed without merging**
