### PR TITLE
Makefile: Support passing environment variables through make--and use…

### PR DESCRIPTION
**Pull request by daym**
… it to support host compilers that use environment variables CPATH etc. See Issue #609.

### CODE REVIEW

**Comment by tlaurion** [comment]
Hello @daym 
I get the following on fedora-30:
```
make -C "/home/user/heads/build/busybox-1.28.0" CC=/home/user/heads/install/bin/musl-gcc -fdebug-prefix-map=/home/user/heads=heads -gno-record-gcc-switches -D__MUSL__  CPP=/home/user/heads/build/../crossgcc/x86_64-linux-musl/bin/x86_64-linux-musl-cpp CXXCPP=/home/user/heads/build/../crossgcc/x86_64-linux-musl/bin/x86_64-linux-musl-cpp CC_FOR_BUILD= BUILD_CC= HOSTCC= AR=/home/user/heads/build/../crossgcc/x86_64-linux-musl/bin/x86_64-linux-musl-ar LD=/home/user/heads/build/../crossgcc/x86_64-linux-musl/bin/x86_64-linux-musl-ld STRIP=/home/user/heads/build/../crossgcc/x86_64-linux-musl/bin/x86_64-linux-musl-strip NM=/home/user/heads/build/../crossgcc/x86_64-linux-musl/bin/x86_64-linux-musl-nm OBJCOPY=/home/user/heads/build/../crossgcc/x86_64-linux-musl/bin/x86_64-linux-musl-objcopy OBJDUMP=/home/user/heads/build/../crossgcc/x86_64-linux-musl/bin/x86_64-linux-musl-objdump PKG_CONFIG_PATH=/home/user/heads/install/lib/pkgconfig PKG_CONFIG_SYSROOT_DIR=/home/user/heads/install    
make[1]: Entering directory '/home/user/heads/build/busybox-1.28.0'
rm -f .kernelrelease
echo 1.28.0 > .kernelrelease
/home/user/heads/build/busybox-1.28.0/scripts/gen_build_files.sh /home/user/heads/build/busybox-1.28.0 /home/user/heads/build/busybox-1.28.0
make -f scripts/Makefile.build obj=scripts/basic
   -Wp,-MD,scripts/basic/.fixdep.d         -o scripts/basic/fixdep scripts/basic/fixdep.c  
/bin/sh: -Wp,-MD,scripts/basic/.fixdep.d: No such file or directory
make[2]: *** [scripts/Makefile.host:104: scripts/basic/fixdep] Error 127
make[1]: *** [Makefile:357: scripts_basic] Error 2
make[1]: Leaving directory '/home/user/heads/build/busybox-1.28.0'
make: *** [Makefile:384: /home/user/heads/build/busybox-1.28.0/.build] Error 1
```

make sure to:
```
cd heads
make BOARD=YourBoard real.clean
rm -rf crossgcc
```

**Comment by tlaurion** [comment]
@daym ping!

**Comment by tlaurion** [comment]
@osreserch: issue linked to this might expose roots of reproducibility issues?

**Comment by daym** [comment]
> @daym ping!

I'd like to finish this, but I can't--because musl-cross in Guix doesn't work anymore.

I need this stuff to actually work so I compiled it in Redhat for the time being.

**Comment by daym** [comment]
Rebased in new pull request #710.

**Comment by daym** [comment]
(I didn't fix the ctype issue in musl-cross - I just commented the part out because we don't use it anyway. Works fine)

**Pull request closed without merging**
