### PR TITLE
T430 initial support

### PR DESCRIPTION
**Pull request by SebastianMcMillan**
Requires #579 to be merged first.

Introduces T430 support, coupled with t430-flash.

Directly based on X230 configs, currently untested. Made to help troubleshoot #541.

### CODE REVIEW

**Comment by flawedworld** [comment]
So I have been unable to build this, I get: https://pastebin.com/NPJPAwdQ

However, I was successfully able to build from your master, I will attempt to try to test it on my T430 either today or on the weekend.

Both were built on a Debian 9 VM due to the current (unrelated) bug in build system preventing builds on Arch.

**Comment by SebastianMcMillan** [comment]
Make sure to give it a while when you power on, we're having an issue that
delays boot up on all sandy/ivy systems not X230 currently.

If it boots up almost immediately, I need to know.

**Comment by tlaurion** [comment]
> So I have been unable to build this, I get: https://pastebin.com/NPJPAwdQ
> 
@SebastianMcMillan no blob extraction scripts for the t430? (x230 like board?)
Why t430/fmap.fmap isn't found, as reported per @flawedworld ?

**Comment by SebastianMcMillan** [comment]
T430 is similar to X230.

For the fmap not found, I'm not getting this issue. I'll look into this
later today.

**Comment by SebastianMcMillan** [comment]
Alright, it is fixed. I forgot to fix the name of one of the configs, since coreboot refers to t430 as THINKPAD_T430 and not T430 like the others.

**Comment by SebastianMcMillan** [comment]
Alright, so after some testing, T430 doesn't have a working TPM implementation in 4.8.1. 

@flawedworld built 4.9 and it does have TPM, so this board relies on changes in 4.9.

What's the status on the 4.9/4.10 porting process?

**Comment by SebastianMcMillan** [comment]
This branch's flash.sh changes are reverted to conform with #592's way of supplying flash definitions.

**Comment by tlaurion** [comment]
Porting work has started on sandy bridge (xx20). Ivy bridge will follow soon after (xx30)
I'll try to give input as the work under grant goes, while pinging involved developers to collaborate if needed.

**Comment by SebastianMcMillan** [comment]
This PR is superseded by #656 therefore I am closing.

**Pull request closed without merging**
