### PR TITLE
Have coreboot 4.11 boards locally buildable again (patches compliant with "git apply" + make 4.2.1+ fixes)

### PR DESCRIPTION
**Pull request by tlaurion**
This PR was aimed to bring back coreboot 4.11 boards to CircleCI but there seems to be a racing condition that happens on docker with debian-11 that cannot be reproduced locally.... 

This PR brings a coreboot patch to fix coreboot 4.11 Makefile.inc to be make 4.2.1/4.3 friendly and fixes coreboot 4.11 patches  to be compliant with git apply. It also removes a transitional patch that was added at a time where https certificate was broken and downloaded coreboot 4.11 buildstack from http websites.

Bringing back coreboot 4.11 boards to CircleCI will be another task. 
kgpe-d16 and librem_l1um boards can be built on top of debian-11 again.

### CODE REVIEW

**Comment by tlaurion** [comment]
Just built successfully (locally) kgpe-d16_server target on top of this PR on **debian-10** (not debian-11):
```
2022-12-05 10:54:40-05:00 DONE coreboot
# Use coreboot.rom, because custom output files might not be processed by cbfstool
"/home/user/heads/build/x86/coreboot-4.11/kgpe-d16_server-whiptail/cbfstool" "/home/user/heads/build/x86/coreboot-4.11/kgpe-d16_server-whiptail/coreboot.rom" print
FMAP REGION: COREBOOT
Name                           Offset     Type           Size   Comp
cbfs master header             0x0        cbfs header        32 none
fallback/romstage              0x80       stage          175060 none
fallback/ramstage              0x2acc0    stage           91453 none
config                         0x41240    raw               866 none
revision                       0x41600    raw               697 none
cmos.default                   0x41900    cmos_default      256 none
cmos_layout.bin                0x41a40    cmos_layout      3524 none
fallback/dsdt.aml              0x42840    raw              9875 none
fallback/payload               0x44f40    simple elf    7031874 none
(empty)                        0x6f9bc0   null          9459992 none
bootblock                      0xfff500   bootblock        2216 none
2022-12-05 10:54:40-05:00 INSTALL   build/x86/coreboot-4.11/kgpe-d16_server-whiptail/coreboot.rom => build/x86/kgpe-d16_server-whiptail/heads-kgpe-d16_server-whiptail-v0.2.0-1301-g61f72f8-dirty.rom
2f500a6e8ac018a3ec82dba3a116a82bc452dd5bda9294e7b6028e8a96cc9b67  build/x86/kgpe-d16_server-whiptail/heads-kgpe-d16_server-whiptail-v0.2.0-1301-g61f72f8-dirty.rom
2f500a6e8ac018a3ec82dba3a116a82bc452dd5bda9294e7b6028e8a96cc9b67  /home/user/heads/build/x86/kgpe-d16_server-whiptail/heads-kgpe-d16_server-whiptail-v0.2.0-1301-g61f72f8-dirty.rom
```

**Comment by tlaurion** [comment]
Same for librem_l1um on debian-10:
```
2022-12-05 11:28:56-05:00 DONE coreboot
# Use coreboot.rom, because custom output files might not be processed by cbfstool
"/home/user/heads/build/x86/coreboot-4.11/librem_l1um/cbfstool" "/home/user/heads/build/x86/coreboot-4.11/librem_l1um/coreboot.rom" print
FMAP REGION: COREBOOT
Name                           Offset     Type           Size   Comp
cbfs master header             0x0        cbfs header        32 none
fallback/romstage              0x80       stage           40852 none
cpu_microcode_blob.bin         0xa080     microcode       56320 none
fallback/ramstage              0x17d00    stage           72857 none
config                         0x29a00    raw              1076 none
revision                       0x29e80    raw               697 none
fallback/dsdt.aml              0x2a180    raw              9662 none
fallback/payload               0x2c7c0    simple elf    7197613 none
(empty)                        0x709bc0   null          3760600 none
fsp.bin                        0xa9fdc0   fsp           1179648 none
(empty)                        0xbbfe00   null           194968 none
bootblock                      0xbef7c0   bootblock        1504 none
2022-12-05 11:28:56-05:00 INSTALL   build/x86/coreboot-4.11/librem_l1um/coreboot.rom => build/x86/librem_l1um/heads-librem_l1um-v0.2.0-1301-g61f72f8-dirty.rom
e76779bcc409d30f647f9fe15f50dbfe8eec68db1e2098d51c77bd28fd1d2177  build/x86/librem_l1um/heads-librem_l1um-v0.2.0-1301-g61f72f8-dirty.rom
e76779bcc409d30f647f9fe15f50dbfe8eec68db1e2098d51c77bd28fd1d2177  /home/user/heads/build/x86/librem_l1um/heads-librem_l1um-v0.2.0-1301-g61f72f8-dirty.rom

```

**Comment by tlaurion** [comment]
```
user@kgpe-d16:~/heads$ make --version
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
user@kgpe-d16:~/heads$ gawk --version
GNU Awk 4.2.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.1.2)
Copyright (C) 1989, 1991-2018 Free Software Foundation.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see http://www.gnu.org/licenses/.

```

**Comment by tlaurion** [comment]
Have cloned kgpe-d16 qube which was based on debian-10 to kgpe-d16-deb11, based on debian-11 template and relaunched the build:

```
user@kgpe-d16-deb11:~/heads$ make BOARD=kgpe-d16_server-whiptail
make -C "/home/user/heads/build/x86/coreboot-4.11" CPUS=2 "crossgcc-i386"
make[1]: Entering directory '/home/user/heads/build/x86/coreboot-4.11'
rm -rf build/*.elf build/*.o .xcompile
rm -f nvramcui.elf
rm -rf /home/user/heads/build/x86/coreboot-4.11/payloads/external/depthcharge/depthcharge/build
test -d seabios/out && rm -rf seabios/out || exit 0
test -d u-boot && make -C u-boot clean || exit 0
test -d /home/user/heads/build/x86/coreboot-4.11/payloads/external/Memtest86Plus/memtest86plus && make -C /home/user/heads/build/x86/coreboot-4.11/payloads/external/Memtest86Plus/memtest86plus clean || exit 0
test -d ipxe && make -C ipxe/src veryclean || exit 0
rm -f ipxe/ipxe.rom
test -d tint && make -C tint clean || exit 0
test -d /home/user/heads/build/x86/coreboot-4.11/payloads/external/tianocore/tianocore && (cd /home/user/heads/build/x86/coreboot-4.11/payloads/external/tianocore/tianocore; rm -rf Build; rm -f Conf/tools_def.txt) || exit 0
test -f grub2/build/Makefile && make -C grub2/build clean || exit 0
if [ -d "linuxboot/kernel" ]; then rm -rf linuxboot/kernel; fi
rm -f linuxboot/u-root
rm -f linuxboot/initramfs*
test -d /home/user/heads/build/x86/coreboot-4.11/payloads/external/Yabits/uefi && make -C /home/user/heads/build/x86/coreboot-4.11/payloads/external/Yabits/uefi clean LIBCONFIG_PATH="../../../libpayload" XGCC= || exit 0
bash ./buildgcc -p i386-elf -j 2   \
		 -d /home/user/heads/build/x86/coreboot-4.11/util/crossgcc/xgcc
Welcome to the coreboot cross toolchain builder v ()

Building toolchain using 2 thread(s).

Target architecture is i386-elf

Found compatible Ada compiler, enabling Ada support by default.

Downloading and verifing tarballs ...
 * gmp-6.1.2.tar.xz (cached)... hash verified (9dc6981197a7d92f339192eea974f5eca48fcffe)
 * mpfr-4.0.2.tar.xz (cached)... hash verified (52c1f2a4c9a202f46cf3275a8d46b562aa584208)
 * mpc-1.1.0.tar.gz (cached)... hash verified (b019d9e1d27ec5fb99497159d43a3164995de2d0)
 * binutils-2.32.tar.xz (cached)... hash verified (cd45a512af1c8a508976c1beb4f5825b3bb89f4d)
 * gcc-8.3.0.tar.xz (cached)... hash verified (c27f4499dd263fe4fb01bcc5565917f3698583b2)
Downloaded tarballs ... ok
Unpacking and patching ...
 * gcc-8.3.0.tar.xz
   o gcc-8.3.0_ada-musl_workaround.patch
   o gcc-8.3.0_gnat-bad_constant.patch
   o gcc-8.3.0_gnat.patch
   o gcc-8.3.0_gnat_eh.patch
   o gcc-8.3.0_libgcc.patch
   o gcc-8.3.0_nds32_ite.patch
Unpacked and patched ... ok
Building packages ...
Skipping GMP v6.1.2 for host as it is already built
Skipping MPFR v4.0.2 for host as it is already built
Skipping MPC v1.1.0 for host as it is already built
Skipping BINUTILS v2.32 for target as it is already built
Skipping GCC v8.3.0 for target as it is already built
Packages built ... ok
Copied EDK2 tools template ... ok
Cleaning up temporary files... ok

You can now run i386-elf cross GCC from /home/user/heads/build/x86/coreboot-4.11/util/crossgcc/xgcc.
bash ./buildgcc -P nasm -j 2    -d /home/user/heads/build/x86/coreboot-4.11/util/crossgcc/xgcc
Welcome to the coreboot cross toolchain builder v ()

Building toolchain using 2 thread(s).

Downloading and verifing tarballs ...
 * nasm-2.14.02.tar.bz2 (cached)... hash verified (fe098ee4dc9c4c983696c4948e64b23e4098b92b)
Downloaded tarballs ... ok
Unpacking and patching ...
 * nasm-2.14.02.tar.bz2
Unpacked and patched ... ok
Building packages ...
Skipping NASM v2.14.02 for host as it is already built
Packages built ... ok
Copied EDK2 tools template ... ok
Cleaning up temporary files... ok

You can now run NASM from /home/user/heads/build/x86/coreboot-4.11/util/crossgcc/xgcc.
bash ./buildgcc -P iasl -j 2    -d /home/user/heads/build/x86/coreboot-4.11/util/crossgcc/xgcc
Welcome to the coreboot cross toolchain builder v ()

Building toolchain using 2 thread(s).

Downloading and verifing tarballs ...
 * acpica-unix-20210105.tar.gz (cached)... hash verified (6d825e662eac26d36f58e7f1a698833267ab4a5b)
Downloaded tarballs ... ok
Unpacking and patching ...
 * acpica-unix-20210105.tar.gz
   o acpica-unix-20210105_iasl.patch
Unpacked and patched ... ok
Building packages ...
Skipping IASL v20210105 for host as it is already built
Packages built ... ok
Copied EDK2 tools template ... ok
Cleaning up temporary files... ok

You can now run IASL ACPI compiler from /home/user/heads/build/x86/coreboot-4.11/util/crossgcc/xgcc.
make[1]: Leaving directory '/home/user/heads/build/x86/coreboot-4.11'
2022-12-05 11:49:30-05:00 CONFIG coreboot
2022-12-05 11:49:32-05:00 INSTALL-MODULE drivers/net/ethernet/intel/e1000e/e1000e.ko
2022-12-05 11:49:32-05:00 INSTALL-MODULE drivers/usb/host/uhci-hcd.ko
2022-12-05 11:49:32-05:00 INSTALL-MODULE drivers/usb/host/ohci-hcd.ko
2022-12-05 11:49:32-05:00 INSTALL-MODULE drivers/usb/host/ohci-pci.ko
2022-12-05 11:49:32-05:00 INSTALL-MODULE drivers/usb/host/ehci-hcd.ko
2022-12-05 11:49:32-05:00 INSTALL-MODULE drivers/usb/host/ehci-pci.ko
2022-12-05 11:49:32-05:00 INSTALL-MODULE drivers/usb/host/xhci-hcd.ko
2022-12-05 11:49:32-05:00 INSTALL-MODULE drivers/usb/host/xhci-pci.ko
2022-12-05 11:49:33-05:00 INSTALL-MODULE drivers/usb/storage/usb-storage.ko
2022-12-05 11:49:33-05:00 SYMLINK bin/busybox
2022-12-05 11:50:02-05:00 INSTALL-BIN build/x86/kexec-tools-2.0.22/build/sbin/kexec
2022-12-05 11:50:02-05:00 INSTALL-BIN build/x86/tpmtotp-18b860fdcf5a55537c8395b891f2b2a5c24fc00a/totp
2022-12-05 11:50:02-05:00 INSTALL-BIN build/x86/tpmtotp-18b860fdcf5a55537c8395b891f2b2a5c24fc00a/hotp
2022-12-05 11:50:02-05:00 INSTALL-BIN build/x86/tpmtotp-18b860fdcf5a55537c8395b891f2b2a5c24fc00a/base32
2022-12-05 11:50:02-05:00 INSTALL-BIN build/x86/tpmtotp-18b860fdcf5a55537c8395b891f2b2a5c24fc00a/qrenc
2022-12-05 11:50:02-05:00 INSTALL-BIN build/x86/tpmtotp-18b860fdcf5a55537c8395b891f2b2a5c24fc00a/util/tpm
2022-12-05 11:50:02-05:00 INSTALL-BIN build/x86/pciutils-3.5.4/lspci
2022-12-05 11:50:03-05:00 INSTALL-BIN build/x86/flashrom-b1f858f65b2abd276542650d8cb9e382da258967/flashrom
2022-12-05 11:50:03-05:00 INSTALL-BIN build/x86/cryptsetup-1.7.3/src/.libs/cryptsetup
2022-12-05 11:50:03-05:00 INSTALL-BIN build/x86/cryptsetup-1.7.3/src/.libs/cryptsetup-reencrypt
2022-12-05 11:50:03-05:00 INSTALL-BIN build/x86/cryptsetup-1.7.3/src/.libs/veritysetup
2022-12-05 11:50:03-05:00 INSTALL-BIN build/x86/gnupg-2.2.21/g10/gpg
2022-12-05 11:50:03-05:00 INSTALL-BIN build/x86/gnupg-2.2.21/agent/gpg-agent
2022-12-05 11:50:03-05:00 INSTALL-BIN build/x86/gnupg-2.2.21/scd/scdaemon
2022-12-05 11:50:03-05:00 INSTALL-BIN build/x86/pinentry-1.1.0/tty/pinentry-tty
2022-12-05 11:50:03-05:00 INSTALL-BIN build/x86/lvm2.2.02.168/tools/dmsetup
2022-12-05 11:50:03-05:00 INSTALL-BIN build/x86/lvm2.2.02.168/tools/lvm
2022-12-05 11:50:03-05:00 INSTALL-BIN build/x86/dropbear-2016.74/ssh
2022-12-05 11:50:03-05:00 INSTALL-BIN build/x86/dropbear-2016.74/scp
2022-12-05 11:50:03-05:00 INSTALL-BIN build/x86/dropbear-2016.74/dropbear
2022-12-05 11:50:03-05:00 INSTALL-BIN build/x86/flashtools-76bdfa21d65caeb7dbe9c2fa1a837369732f50af/flashtool
2022-12-05 11:50:04-05:00 INSTALL-BIN build/x86/flashtools-76bdfa21d65caeb7dbe9c2fa1a837369732f50af/peek
2022-12-05 11:50:04-05:00 INSTALL-BIN build/x86/flashtools-76bdfa21d65caeb7dbe9c2fa1a837369732f50af/poke
2022-12-05 11:50:04-05:00 INSTALL-BIN build/x86/flashtools-76bdfa21d65caeb7dbe9c2fa1a837369732f50af/cbfs
2022-12-05 11:50:04-05:00 INSTALL-BIN build/x86/flashtools-76bdfa21d65caeb7dbe9c2fa1a837369732f50af/uefi
2022-12-05 11:50:04-05:00 INSTALL-BIN build/x86/newt-0.52.20/whiptail
2022-12-05 11:50:04-05:00 MAKE cbmem
make[1]: Entering directory '/home/user/heads/build/x86/coreboot-4.11/util/cbmem'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/user/heads/build/x86/coreboot-4.11/util/cbmem'
2022-12-05 11:50:04-05:00 INSTALL-BIN build/x86/coreboot-4.11/util/cbmem/cbmem
2022-12-05 11:50:04-05:00 INSTALL-LIB crossgcc/x86/x86_64-linux-musl/lib/libc.so
2022-12-05 11:50:04-05:00 INSTALL-LIB build/x86/cryptsetup-1.7.3/lib/.libs/libcryptsetup.so.4
2022-12-05 11:50:04-05:00 INSTALL-LIB build/x86/libassuan-2.5.3/src/.libs/libassuan.so.0
2022-12-05 11:50:04-05:00 INSTALL-LIB build/x86/libgcrypt-1.8.6/src/.libs/libgcrypt.so.20
2022-12-05 11:50:04-05:00 INSTALL-LIB build/x86/libgpg-error-1.37/src/.libs/libgpg-error.so.0
2022-12-05 11:50:04-05:00 INSTALL-LIB build/x86/libksba-1.4.0/src/.libs/libksba.so.8
2022-12-05 11:50:04-05:00 INSTALL-LIB build/x86/libusb-1.0.21/libusb/.libs/libusb-1.0.so.0
2022-12-05 11:50:04-05:00 INSTALL-LIB build/x86/libusb-compat-0.1.5/libusb/.libs/libusb-0.1.so.4
2022-12-05 11:50:04-05:00 INSTALL-LIB build/x86/lvm2.2.02.168/libdm/libdevmapper.so.1.02
2022-12-05 11:50:05-05:00 INSTALL-LIB build/x86/mbedtls-2.4.2/library/libmbedcrypto.so.0
2022-12-05 11:50:05-05:00 INSTALL-LIB build/x86/newt-0.52.20/libnewt.so.0.52
2022-12-05 11:50:05-05:00 INSTALL-LIB build/x86/npth-1.6/src/.libs/libnpth.so.0
2022-12-05 11:50:05-05:00 INSTALL-LIB build/x86/pciutils-3.5.4/lib/libpci.so.3.5.4
2022-12-05 11:50:05-05:00 INSTALL-LIB install/x86/lib/libpci.so.3
2022-12-05 11:50:05-05:00 INSTALL-LIB build/x86/popt-1.16/.libs/libpopt.so.0
2022-12-05 11:50:05-05:00 INSTALL-LIB build/x86/qrencode-3.4.4/.libs/libqrencode.so.3
2022-12-05 11:50:05-05:00 INSTALL-LIB build/x86/slang-2.3.1a/src/elfobjs/libslang.so.2
2022-12-05 11:50:05-05:00 INSTALL-LIB build/x86/tpmtotp-18b860fdcf5a55537c8395b891f2b2a5c24fc00a/libtpm/libtpm.so
2022-12-05 11:50:05-05:00 INSTALL-LIB build/x86/util-linux-2.29.2/.libs/libuuid.so.1
2022-12-05 11:50:05-05:00 INSTALL-LIB build/x86/util-linux-2.29.2/.libs/libblkid.so.1
2022-12-05 11:50:05-05:00 INSTALL-LIB build/x86/zlib-1.2.11/libz.so.1
2022-12-05 11:50:05-05:00 INSTALL boards/kgpe-d16_server-whiptail/kgpe-d16_server-whiptail.config
2022-12-05 11:50:05-05:00 HASH 61f72f8d512fd9459cba8158a521875eb62a7959 dirty kgpe-d16_server-whiptail
2022-12-05 11:50:05-05:00 CPIO      build/x86/kgpe-d16_server-whiptail/tools.cpio
2022-12-05 11:50:06-05:00 UNCHANGED build/x86/kgpe-d16_server-whiptail/tools.cpio
0cdcf1395412f34aa85d7277961f7b56d0a4be4231549f4188e0c2a80e513e4e  /home/user/heads/build/x86/kgpe-d16_server-whiptail/tools.cpio
2022-12-05 11:50:06-05:00 HASHES    build/x86/kgpe-d16_server-whiptail/tools.cpio
2022-12-05 11:50:07-05:00 CPIO      build/x86/kgpe-d16_server-whiptail/heads.cpio
2022-12-05 11:50:07-05:00 UNCHANGED build/x86/kgpe-d16_server-whiptail/heads.cpio
21583d2aa671472d98a3896586437f56fd2965dfcb4ddda2ec84717d6c02217d  /home/user/heads/build/x86/kgpe-d16_server-whiptail/heads.cpio
2022-12-05 11:50:07-05:00 HASHES    build/x86/kgpe-d16_server-whiptail/heads.cpio
2022-12-05 11:50:07-05:00 MAKE coreboot
tail /home/user/heads/build/x86/log/coreboot.log
-----
make -C "/home/user/heads/build/x86/coreboot-4.11/kgpe-d16_server-whiptail" -C /home/user/heads/build/x86/coreboot-4.11 obj=/home/user/heads/build/x86/coreboot-4.11/kgpe-d16_server-whiptail CROSS=/home/user/heads/crossgcc/x86/bin/i386-linux-musl- IASL=/home/user/heads/build/x86/coreboot-4.11/util/crossgcc/xgcc/bin/iasl DOTCONFIG=/home/user/heads/build/x86/coreboot-4.11/kgpe-d16_server-whiptail/.config BUILD_TIMELESS=1 CFLAGS_x86_32=-fdebug-prefix-map=/home/user/heads=heads -gno-record-gcc-switches -Wno-error=packed-not-aligned CFLAGS_x86_64=-fdebug-prefix-map=/home/user/heads=heads -gno-record-gcc-switches -Wno-error=packed-not-aligned -j2 --max-load 16
make[1]: Entering directory '/home/user/heads/build/x86/coreboot-4.11'
#
# configuration written to /home/user/heads/build/x86/coreboot-4.11/kgpe-d16_server-whiptail/.config
#
    GEN        generated/assembly.inc
make[1]: *** No rule to make target '".car.data"', needed by 'kgpe-d16_server-whiptail/coreboot.pre'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/user/heads/build/x86/coreboot-4.11'
make: *** [Makefile:408: /home/user/heads/build/x86/coreboot-4.11/kgpe-d16_server-whiptail/.build] Error 1
```

**Comment by JonathonHall-Purism** [comment]
This is what I brought back make 4.2.1 for in that patch.  I did a "shallow" dive into this back for PB release 23 and couldn't readily see where this file was supposed to come from through the complex Makefiles, needs a deeper dive but I just brought back make 4.2.1 in order to finish that release and had to backburner it :-/

So unfortunately no, I don't know offhand what exactly is going wrong or what is supposed to be happening here - maybe we could get some suggestions in #coreboot?

**Comment by tlaurion** [comment]
As current, cmos-mem/ build.h still fails to be build randomly where others run are successful (race condition).
As a side note, building with debian-10 doesn't show those problems. I tried my best to cherry pick coreboot fixes on Makefile and Makefile.inc but it seems to just break later and later without 100% success rate. There is always a build that fails.


If someone wants to continue this deeper, the best found way to do so is to reuse the following circleci configuration which only builds for coreboot 4.11 boards, without caching:
https://raw.githubusercontent.com/tlaurion/heads/coreboot_411_kgpe_l1um_tests_without_saving_cache_with_nvramtool_minimal_gcc_fix-5/.circleci/config.yml
So one can simply push multiple branches to github if CircleCI is linked to your github fork of heads and follows it. 


-------------

As of now, one wanting to review my attempts can go here:
https://app.circleci.com/pipelines/github/tlaurion/heads and search for builds that happened between December 7th 2022 and December 8th 2022:

And click the failing builds for the boards, under "Make board" step.

For example, one would see:
- librem_l1um randomly fails to find build.h https://app.circleci.com/pipelines/github/tlaurion/heads/1310/workflows/152db986-d333-4c56-a5a9-008163a80f92/jobs/13151?invite=true#step-103-806
- kgpe-d16 boards randomly fails to find cmos-mem.o: https://app.circleci.com/pipelines/github/tlaurion/heads/1310/workflows/152db986-d333-4c56-a5a9-008163a80f92/jobs/13148?invite=true#step-103-862

**Comment by tlaurion** [comment]
@JonathonHall-Purism I think that will be it for this first step. Comments?

**Comment by JonathonHall-Purism** [comment]
Yeah I am good with this @tlaurion, thanks for all the work on this.  It addresses the quick hacks I was carrying for librem_l1um on Debian 11.  I build that fairly regularly on Debian 11, so while not as good as CI at least it is some insulation against breakage as long as I stay on top of upstreaming.

I'm puzzled by the CI issues we struggled with but as usual, no reason to hold good improvements.  For what it's worth, I tried building on tmpfs with 32 CPUs on PureOS (~Debian 11) and still did not see any races, not even the obvious one in nvramtool.  I still don't know why it is different on CircleCI.

**Pull request merged**
