### PR TITLE
qemu-coreboot-fbwhiptail board addition

### PR DESCRIPTION
**Pull request by tlaurion**
by doing:
`make BOARD=qemu-coreboot-fbwhiptail && make BOARD=qemu-coreboot-fbwhiptail run`

One can test gui-init

Based on #707

### CODE REVIEW

**Comment by tlaurion** [comment]
@MrChromebox done

**Comment by MrChromebox** [comment]
@tlaurion tested ok here and mostly LGTM. Though the utility is somewhat limited without any disk attached

Also, commit message for ef499f607 has the board name order incorrect though (coreboot-qemu-fbwhiptail vs qemu-coreboot-fbwhiptail).

**Comment by tlaurion** [comment]
> @tlaurion tested ok here and mostly LGTM. Though the utility is somewhat limited without any disk attached
> 
@MrChromebox : Agreed. those comments should be made to #516 and/or #701 which would need to be filled in for another PR to be made consequently. This is just basic board config which would benefit from love given in the two other issues pointed here.

> Also, commit message for [ef499f6](https://github.com/osresearch/heads/commit/ef499f6076e6c0c15f3271f4bb6f9d56ffadbe02) has the board name order incorrect though (coreboot-qemu-fbwhiptail vs qemu-coreboot-fbwhiptail).

Fixed. Thanks.

**Comment by MrChromebox** [comment]
> Fixed. Thanks.

I'm still seeing the first commit as:

> Working config to do make BOARD=coreboot-qemu-fbwhiptail and then mak…

the most recent force push only changed the 2nd commit

**Comment by tlaurion** [comment]
@MrChromebox fixed.

**Pull request merged**
