### PR TITLE
DO NOT MERGE: Shellcheck script files in initrd

### PR DESCRIPTION
**Pull request by Thrilleratplay**
This is an alternative approach to #862.  

Instead of rewriting all BASH syntax to be POSIX, add busybox config to set `CONFIG_BASH_IS_ASH=y` which I believe statically links `/bin/ash` to `/bin/bash`.  This combined with the existing `CONFIG_ASH_BASH_COMPAT` setting should allow shellcheck to the check the scripts under `/initrd` as closer to how they already exists and with few large changes.

While labeling these scripts as `#!/bin/bash` may be misleading, all scripts are read-only within the ROM and will still need to be tested before being committed in the official repo.  The only problem I can foresee would be if users who try to execute BASH scripts from external media that may execute bash scripts with incompatible syntax, although, I think this is currently a possibility.

 - [x] [SC1001](https://www.shellcheck.net/wiki/SC1001)
 - [x] [SC1009](https://www.shellcheck.net/wiki/SC1009)
 - [x] [SC1083](https://www.shellcheck.net/wiki/SC1083)
 - [x] [SC2001](https://www.shellcheck.net/wiki/SC2001)
 - [x] [SC2002](https://www.shellcheck.net/wiki/SC2002)
 - [x] [SC2003](https://www.shellcheck.net/wiki/SC2003)
 - [x] [SC2004](https://www.shellcheck.net/wiki/SC2004)
 - [x] [SC2005](https://www.shellcheck.net/wiki/SC2005)
 - [x] [SC2006](https://www.shellcheck.net/wiki/SC2006)
 - [x] [SC2012](https://www.shellcheck.net/wiki/SC2012)
 - [x] [SC2013](https://www.shellcheck.net/wiki/SC2013)
 - [x] [SC2015](https://www.shellcheck.net/wiki/SC2015)
 - [x] [SC2016](https://www.shellcheck.net/wiki/SC2016)
 - [x] [SC2034](https://www.shellcheck.net/wiki/SC2034)
 - [x] [SC2044](https://www.shellcheck.net/wiki/SC2044)
 - [x] [SC2046](https://www.shellcheck.net/wiki/SC2046)
 - [x] [SC2048](https://www.shellcheck.net/wiki/SC2048)
 - [x] [SC2061](https://www.shellcheck.net/wiki/SC2061)
 - [x] [SC2086](https://www.shellcheck.net/wiki/SC2086)
 - [x] [SC2091](https://www.shellcheck.net/wiki/SC2091)
 - [x] [SC2093](https://www.shellcheck.net/wiki/SC2093)
 - [x] [SC2116](https://www.shellcheck.net/wiki/SC2116)
 - [x] [SC2119](https://www.shellcheck.net/wiki/SC2119)
 - [x] [SC2124](https://www.shellcheck.net/wiki/SC2124)
 - [x] [SC2155](https://www.shellcheck.net/wiki/SC2155)
 - [x] [SC2157](https://www.shellcheck.net/wiki/SC2157)
 - [x] [SC2160](https://www.shellcheck.net/wiki/SC2160)
 - [x] [SC2162](https://www.shellcheck.net/wiki/SC2162)
 - [x] [SC2166](https://www.shellcheck.net/wiki/SC2166)
 - [x] [SC2181](https://www.shellcheck.net/wiki/SC2181)
 - [x] [SC2188](https://www.shellcheck.net/wiki/SC2188)
 - [x] [SC2210](https://www.shellcheck.net/wiki/SC2210)
 - [x] [SC2216](https://www.shellcheck.net/wiki/SC2216)
 - [x] [SC2219](https://www.shellcheck.net/wiki/SC2219)
 - [x] [SC2220](https://www.shellcheck.net/wiki/SC2220)
 - [x] [SC2231](https://www.shellcheck.net/wiki/SC2231)
 - [x] [SC2236](https://www.shellcheck.net/wiki/SC2236)
 - [x] [SC2242](https://www.shellcheck.net/wiki/SC2242)

Exceptions added for:
 - [ ] [SC1091](https://www.shellcheck.net/wiki/SC1091) - Generally added under `.shellcheckrc`
 - [ ] [SC2094](https://www.shellcheck.net/wiki/SC2094) - `initrd/init.sh`
 - [ ] [SC2154](https://www.shellcheck.net/wiki/SC2154) - `initrd/sbin/config-dhcp.sh`

@osresearch @tlaurion @MrChromebox One of three possible paths:

* I can complete this PR using BASH syntax
* I can complete #862 using POSIX syntax with a few exceptions.
* I can complete this PR using BASH syntax and during the long term goal of cleaning up these scripts, migrate to POSIX during this process.

### CODE REVIEW

**Comment by tlaurion** [comment]
@Thrilleratplay what is your preferate approach between #862 and here? Seems lik here wins to me.

**Comment by Thrilleratplay** [comment]
@tlaurion I would probably vote for this version, fake BASH.  It will likely be easier to verify the changes and run spellcheck against.

**Comment by tlaurion** [comment]
@Thrilleratplay : can you make circleCi follow your github so that automatic builds are made at each commit? This PR seems mature enough to test builds for regressions

**Comment by Thrilleratplay** [comment]
@tlaurion I will try. Currently I am still testing and running into issues.

**Comment by tlaurion** [comment]
This is not going to work. #862 approach is preferred.

**Pull request closed without merging**
