### PR TITLE
Eliminate use of CONFIG_USB_BOOT_DEV

### PR DESCRIPTION
**Pull request by MrChromebox**
mount-usb switched to dynamic USB device detection a while back,
so eliminate instances of CONFIG_BOOT_USB_DEV, and derive the
mounted USB device from /etc/mtab in the one place where it's
actually needed (usb-scan). Clean up areas around calls to
mount-usb for clarity/readability.

Addresses issue #673

Test: Build Librem 13v4, boot ISO file on USB

Signed-off-by: Matt DeVillier <matt.devillier@puri.sm>

### CODE REVIEW

**Comment by MrChromebox** [comment]
needs good/thorough testing, pushed just to get feedback on approach

**Comment by tlaurion** [comment]
Had this debate prior of change of behavior with Kyle a while back but the goal of having a fallback to board configured device was to be able to boot from dock station hard drive or second hard drive to facilitate OEM tasks or recovery from fast drive having lots of ISOs. I like the approach and will continue to boot in recovery, mount device in /media and run gui-init again, but now it won't be mount /media. It will be mount /dev/sdb1 /media. Will probably put it in history file to facilitate backstage tasks.

I would personally love a generic "boot from other media", where usb drives would be considered as any other block devices after loading usb modules through lsblk or similar. Will check to see if I can propose something in that direction. 

On February 20, 2020 4:31:26 AM UTC, MrChromebox <notifications@github.com> wrote:
>needs good/thorough testing, pushed just to get feedback on approach
>
>-- 
>You are receiving this because your review was requested.
>Reply to this email directly or view it on GitHub:
>https://github.com/osresearch/heads/pull/685#issuecomment-588603974

-- Sent from /e/ Mail

**Comment by tlaurion** [comment]
@MrChromebox : 
what about doing a simple `stat -c % /sys/block/* | grep pci`
And form there, remove CONFIG_BOOT_DEV from the output to create a "Boot from other devices" instead of Boot from USB devices? 

The removing hardcoded CONFIG_BOOT_USB_DEV would become totally irrelevant in all use cases.

**Comment by MrChromebox** [comment]
> And form there, remove CONFIG_BOOT_DEV from the output to create a "Boot from other devices" instead of Boot from USB devices?

CONFIG_BOOT_DEV isn't necessarily what's mounted on /boot, esp on Librems where there can be multiple SATA drives or SATA + NVMe. would need to extract from /etc/mtab like I'm doing

right now, USB booting has two very different paths: signed ISO file, and unsigned kernel. what we'd need to do is separate out the former, and then group the latter as part of the new unsigned 'Boot from other devices' option

**Pull request merged**
