### PR TITLE
config/linux-x230: remove debug symbols

### PR DESCRIPTION
**Pull request by merge**
Remove debug symbols and dynamic debug support from Linux. This reduces
our resulting bzImage by 100K.

This should help when size becomes even more limited, see #562

### CODE REVIEW

**Comment by merge** [comment]
for the record, I flashed that and did a test run.

**Comment by paulmenzel** [comment]
On 20.05.19 13:10, Martin Kepplinger wrote:
> Remove debug symbols and dynamic debug support from Linux. This reduces
> our resulting bzImage by 200K.

How big was the image before?

**Comment by merge** [comment]
thanks for asking, I was wrong and updated the commit message. It's 100K: 3031K -> 2936K. circa.

**Comment by merge** [comment]
With this reduction I was able to do a test-build using coreboot's vboot measured boot. (not without this reduction - we really are at our size limit currently).

The usable cbfs size (fmap see #562) for our vboot-case is not yet defined. This should just be a beginning and we should become even smaller after this!

**Comment by tlaurion** [comment]
#517 is the biggest culprit

**Comment by merge** [comment]
> #517 is the biggest culprit

I see. it is good to have another promising candidate to work on. Unless we need to have debug symbold by default, it doesn't make this change less useful though, right? I'd say let's reduce our size where possible without losing any functionality.

**Pull request merged**
