### PR TITLE
xx20/xx30 maximized coreboot configs: Fix CONFIG_CBFS_SIZE to reflect ifd.bin's BIOS region (xx20: gain of 0.59mb, xx30: gain of 0.4mb

### PR DESCRIPTION
**Pull request by tlaurion**
The calculations outlined at https://github.com/osresearch/heads/pull/1282#discussion_r1072473677 sums to having 'ifdtool -f layout.txt ifd_shrinked.bin && cat layout.txt' 

The content of layout.txt for T440p:
```
00000000:00000fff fd
00021000:00bfffff bios
00003000:00020fff me
00001000:00002fff gbe
```

Here: 
00bfffff-00021000=BDEFFF 
BDEFFF to decimal = 12447743

Which is exact result of @rbeslow's calculations, and was recommended calculation for CBFS size (outside of bugs), otherwise setting it to 8mb.

There is an issue on haswell, maybe because of car, maybe because of non native memory init blob, but all of that is related to #1282, not here. 

But this is not the case for xx20/xx30 boards which have native ram init (where t440p should see it hapenning under 4.19+)

----

Tested with this PR:
- [x] xx30: Gain of 0.4mb flashed x230-maximized: booted with same boot time (felt 5s, same as master).
  - [x] Using [x230-hotp-maximized](https://output.circle-artifacts.com/output/job/50032bcf-3d17-47e7-81df-47a38efd7997/artifacts/0/build/x86/x230-hotp-maximized/heads-x230-hotp-maximized-v0.2.0-1358-gf07ef81.rom) as daily driver as of now 
- [x] xx20: t420 and x220 reported as tested successfully
  - [x] Gain of 0.59mb!!!

This would be free gain for #590!!!

---

This, if working for all boards with unlocked ifd (maximized builds), (truely) maximizes available space for Heads (CBFS), based on freed ME space relegated to BIOS region.

Now time to test other boards. Tagging people from https://github.com/osresearch/heads/issues/692 to test only if external programmer accessible:
- [x] x220 (xx20): @techge @Thrilleratplay @BlackMaria @srgrint
- [x] [t420](https://doc.coreboot.org/mainboard/lenovo/t420.html) (xx20): @alexmaloteaux @natterangell (iGPU) @akfhasodh @doob85
- [ ] [t430](https://doc.coreboot.org/mainboard/lenovo/t430.html) (xx30): @Thrilleratplay @alexmaloteaux @lsafd @bwachter(iGPU) @shamen123 @eganonoa(iGPU) @nitrosimon @jans23 @icequbes1 (iGPU) @weyounsix (t430-dgpu)
- [ ] [t430s](https://www.coreboot.org/Board:lenovo/t430s) and https://github.com/osresearch/heads/pull/1019 (xx30): @Siproqu
- [ ] [t520](https://doc.coreboot.org/mainboard/lenovo/t520.html) (xx30): NOBODY
- [ ] [t530](https://doc.coreboot.org/mainboard/lenovo/t530.html) (xx30): @3hhh
- [ ] [w530](https://doc.coreboot.org/mainboard/lenovo/w530.html) (xx30): @eganonoa @zifxify @weyounsix (dGPU: w530-k2000m) @jnscmns (dGPU K1000M)

### CODE REVIEW

**Comment by tlaurion** [comment]
Additional details:

# x230-hotp-maximized
-  [Master's build log](https://app.circleci.com/pipelines/github/osresearch/heads/510/workflows/87a58dc1-9995-44e2-ac12-964ab410116c/jobs/6781/parallel-runs/0/steps/0-103)
```
FMAP REGION: COREBOOT
Name                           Offset     Type           Size   Comp
cbfs master header             0x0        cbfs header        32 none
fallback/romstage              0x80       stage           85100 none
cpu_microcode_blob.bin         0x14d80    microcode       26624 none
fallback/ramstage              0x1b600    stage           97672 none
config                         0x333c0    raw               834 none
revision                       0x33740    raw               691 none
fallback/dsdt.aml              0x33a40    raw             14615 none
vbt.bin                        0x373c0    raw              1433 LZMA (4281 decompressed)
cmos_layout.bin                0x379c0    cmos_layout      1884 none
fallback/postcar               0x38180    stage           25816 none
fallback/payload               0x3e6c0    simple elf    7321031 none
(empty)                        0x739cc0   null          4350168 none
bootblock                      0xb5fdc0   bootblock       65536 none 
```
- [This PR's build log cbfs print](https://app.circleci.com/pipelines/github/tlaurion/heads/1388/workflows/b07cec94-d549-49b5-a665-1b337eab65fe/jobs/15031/parallel-runs/0/steps/0-103):
```
FMAP REGION: COREBOOT
Name                           Offset     Type           Size   Comp
cbfs master header             0x0        cbfs header        32 none
fallback/romstage              0x80       stage           85100 none
cpu_microcode_blob.bin         0x14d80    microcode       26624 none
fallback/ramstage              0x1b600    stage           97670 none
config                         0x333c0    raw               834 none
revision                       0x33740    raw               691 none
fallback/dsdt.aml              0x33a40    raw             14615 none
vbt.bin                        0x373c0    raw              1433 LZMA (4281 decompressed)
cmos_layout.bin                0x379c0    cmos_layout      1884 none
fallback/postcar               0x38180    stage           25816 none
fallback/payload               0x3e6c0    simple elf    7321543 none
(empty)                        0x739ec0   null          4742872 none
bootblock                      0xbbfdc0   bootblock       65536 none
```
4742872-4350168=392704bytes

# t420-hotp-maximized
- [Master's cbfs print extract](https://app.circleci.com/pipelines/github/osresearch/heads/510/workflows/87a58dc1-9995-44e2-ac12-964ab410116c/jobs/6794/parallel-runs/0/steps/0-103):
```
FMAP REGION: COREBOOT
Name                           Offset     Type           Size   Comp
cbfs master header             0x0        cbfs header        32 none
fallback/romstage              0x80       stage           87724 none
cpu_microcode_blob.bin         0x157c0    microcode       26624 none
fallback/ramstage              0x1c040    stage          119354 none
config                         0x392c0    raw               904 none
revision                       0x39680    raw               691 none
fallback/dsdt.aml              0x39980    raw             14615 none
vbt.bin                        0x3d300    raw              1368 LZMA (3985 decompressed)
cmos.default                   0x3d8c0    cmos_default      256 none
cmos_layout.bin                0x3da00    cmos_layout      1992 none
fallback/postcar               0x3e200    stage           27288 none
fallback/payload               0x44d00    simple elf    7222727 none
(empty)                        0x728300   null            31384 none
bootblock                      0x72fdc0   bootblock       65536 none
```
- [This PR's cbfs print exerpt](https://app.circleci.com/pipelines/github/tlaurion/heads/1388/workflows/b07cec94-d549-49b5-a665-1b337eab65fe/jobs/15036/parallel-runs/0/steps/0-103):
```
FMAP REGION: COREBOOT
Name                           Offset     Type           Size   Comp
cbfs master header             0x0        cbfs header        32 none
fallback/romstage              0x80       stage           87724 none
cpu_microcode_blob.bin         0x157c0    microcode       26624 none
fallback/ramstage              0x1c040    stage          119368 none
config                         0x392c0    raw               904 none
revision                       0x39680    raw               691 none
fallback/dsdt.aml              0x39980    raw             14615 none
vbt.bin                        0x3d300    raw              1368 LZMA (3985 decompressed)
cmos.default                   0x3d8c0    cmos_default      256 none
cmos_layout.bin                0x3da00    cmos_layout      1992 none
fallback/postcar               0x3e200    stage           27288 none
fallback/payload               0x44d00    simple elf    7221191 none
(empty)                        0x727d00   null           622744 none
bootblock                      0x7bfdc0   bootblock       65536 none
```
622744-31384=591360bytes

**Comment by srgrint** [comment]
I have just flashed https://output.circle-artifacts.com/output/job/008109e7-ede2-4ed1-95bc-dd9f5117edfc/artifacts/0/build/x86/x220-maximized/heads-x220-maximized-v0.2.0-1358-gf07ef81.rom on my x220.  Seems to work fine with no adverse effects.

**Comment by natterangell** [comment]
t420-hotp-maximized world great!

**Comment by tlaurion** [comment]
> t420-hotp-maximized works great!
@natterangell thanks for testing!!!

I'll wait for a couple of days but since we have xx20 reports, I'm comfortable merging.

**Comment by tlaurion** [comment]
Rebased on https://github.com/osresearch/heads/pull/967

MERGE #967 FIRST!!!!!!

**Pull request merged**
