### PR TITLE
Add support for dGPU in t430

### PR DESCRIPTION
**Pull request by walliams**
pull @eganonoa's t430-dgpu board configs upstream

### CODE REVIEW

**Comment by tlaurion** [comment]
@walliams ping

**Comment by walliams** [comment]
howdy. how can i help get this merged? says it has conflicts that must be resolved and i don't have write access.
also, now that linux-xxxx.config's have been split to legacy & maximized, the t430-dgpu board configs need to be edited or build returns error: 
`make: *** No rule to make target 'config/linux-x230.config', needed by '/home/user/heads/build/linux-4.14.62/linux-x230/.configured'.  Stop.`

**Comment by tlaurion** [comment]
You would have to checkout @eganonoa's branch, rebase on master, resolve conflicts, and then a PR of your own to replace this one. 

Bestnwoukd be if @eganonoa's could do it, but he is not responsive on github for a while.

-modify t430-dgpu board config to point to linux-230-maximized.config. commit

-modify vbios-t430.sh script with review comments, commit.

That way, original work from @eganonoa would be acknowledged, and your additional work as well.

You cannot push changes to a branch on which you do not have access. But git is made for that. You would basically cherry-pick someone's else work and work on top of that.

@walliams makes sense?

**Comment by walliams** [comment]
generallly understood, but being new to git, finer details are lost.
i forked the branch from @eganonoa , but now what is meant by "rebase on master"?

**Comment by walliams** [comment]
hmmm, perhaps i should fork theads/master and then merge eganonoa/heads/tree/dgpu-t430 in my own repo before making the PR here?

**Pull request closed without merging**
