### PR TITLE
WIP: Lemp10 bringup

### PR DESCRIPTION
**Pull request by aesrentai**
This is a WIP.  Expect it to be force-pushed over repeatedly with no warning.  See commit messages for details.  This PR is a very standard board bringup except it adds the S76 github repo as a coreboot source.

Note: right now tpm2 support is disabled and the no tpm code is used, which should be changed whenever tpm2 support is added.

### CODE REVIEW

**Comment by aesrentai** [comment]
This is supposed to be a draft PR-- I don't have the permissions to do so or I can't find the button to do so.

**Comment by aesrentai** [comment]
Support for the lemp10 in upstream coreboot has just been (merged)[https://review.coreboot.org/c/coreboot/+/52294].  The final version of the patchset will not include the S76 coreboot repo, rather, it will use coreboot 4.15 directly.

**Comment by tlaurion** [comment]
@aesrentai how is this going since 4.15 release?

**Comment by tlaurion** [comment]
@aesrentai FYI https://github.com/system76/firmware-open/pull/260#issuecomment-988358000

**Comment by aesrentai** [comment]
> @aesrentai how is this going since 4.15 release?

Life got busy, not sure when I'll have time to work on this in the immediate future.  This code boots but I'm not comfortable merging it until #1031 gets merged also, and that's going to take a while longer.

**Comment by tlaurion** [comment]
Might want to revive this based on #1292

**Pull request closed without merging**
