### PR TITLE
Arch iso boot fixup (kexec-parse-boot and kexec-boot-iso fixups)

### PR DESCRIPTION
**Pull request by tlaurion**
Archlinux is providing detached signed iso, just like Tails and Qubes OS. We add it here:

- The public key was generated in this PR for inclusion by :
```
mkdir /tmp/test3
gpg --homedir /tmp/test3 --auto-key-locate clear,wkd -v --locate-external-key pierre@archlinux.de
gpg --homedir /tmp/test3 --edit-key pierre@archlinux.de
(minimize, save)
gpg --homedir /tmp/test3 --export --armor > ~/heads/initrd/etc/distro/keys/archlinux.key
```
- One can then build Heads to boot from detached signed iso. Download ISO and detached signature:
http://mirror.rackspace.com/archlinux/iso/2022.02.01/archlinux-2022.02.01-x86_64.iso
http://mirror.rackspace.com/archlinux/iso/2022.02.01/archlinux-2022.02.01-x86_64.iso.sig

- Flash build ROM. Put downloaded iso and detached signature on USB thumb drive. Boot from ISO (Options,Boot options, USB boot)
- Realize that arch is waiting for `/dev/disk/by/label/ARCH_202202` which is never brought up.

@tslilc : Any insight? Does that need to be fixed upstream by Archlinux? 
- kexec boot params are passing `archisolabel=ARCH_202202` and archisobasedir=arch
- where the actual Heads added arguments are passing the right uuid, as to boot all other ISOs....
- Arch really wants to boot from label, while not making it available.... How to fix this? not sure and not investigated. 
EDIT: fixed with kexec-iso-boot fixup.

Hint: There might be code inside of linuxboot/webboot that might help us resolve this, since they implemented a correct parser.

On the good side, the present commit is not breaking other detached signature verified ISO boot: 
- https://github.com/osresearch/heads/commit/c511c68ea894fd6d3e28895dd504a578bd551edf is not breaking: 
  - Tails 4.26 boots from detached signature verified iso (fromiso= passes uuid not label at final kexec call)
  - Qubes 4.0.4 boots from detached signature verified iso. (fromiso= passes  uuid not label at final kexec call)

### CODE REVIEW

**Comment by tlaurion** [comment]
[Some hints on why this might not be working out of the box](https://github.com/u-root/webboot/blob/f9db084bbb91335ff1ea76b9d803e15bdda13ba6/docs/remaster-arch-iso.md#rebuild-the-iso)

Not sure how to hack around this.

On Heads side, a quick [hack was done a while ago to permit iso boot](https://github.com/u-root/webboot/blob/f9db084bbb91335ff1ea76b9d803e15bdda13ba6/docs/remaster-arch-iso.md#rebuild-the-iso), which was to pass fromiso and the iso boot options to cover most OS iso boot.

Some recalled hints: https://github.com/osresearch/heads/issues/470#issuecomment-431891721, pointing to https://mbusb.aguslr.com/howto.html shows that Arch expects:
`img_dev=$imgdevpath img_loop=$iso_path`

Since Heads already passes variables to support debian (`findiso=$iso_path`) and fedora (`iso-scan/filename=$iso_path`), there might be a need to support others, since those variables are only picked up by the OS that are interested in them.

**Comment by tlaurion** [comment]
Ok with https://github.com/osresearch/heads/pull/1120/commits/8f6c61cb1afb8a4fcb671a4c1bb9ea0136040558 change, the iso boots successfully!

Then comes the time to install it and have it booted successfully, which will probably require additional changes to kexec-parse-boot.

**Comment by techge** [comment]
What exactly needs to get tested if you already checked it correctly? That is to say: I am not sure what exactly I am supposed to be looking for.
What is the best way to get a pre-built rom (which option/version shall I use) these days? I do not have a working toolchain right now...

**Comment by techge** [comment]
btw, I just remembered: Ironically, I flashed a coreboot rom last weekend, because I was annoyed that I can not start my arch iso in heads to re-install my system :D

**Comment by lynxred** [comment]
```
mkdir /tmp/test3
gpg --homedir /tmp/test3 --auto-key-locate clear,wkd -v --locate-external-key pierre@archlinux.de
gpg --homedir /tmp/test3 --edit-key pierre@archlinux.de
(minimize, save)
gpg --homedir /tmp/test3 --export --armor > ~/heads/initrd/etc/distro/keys/archlinux.key
```

it needs to be written in the heads console?

**Comment by lynxred** [comment]
i see this error image

**Comment by tlaurion** [comment]
> mkdir /tmp/test3
> gpg --homedir /tmp/test3 --auto-key-locate clear,wkd -v --locate-external-key pierre@archlinux.de
> gpg --homedir /tmp/test3 --edit-key pierre@archlinux.de
> (minimize, save)
> gpg --homedir /tmp/test3 --export --armor > ~/heads/initrd/etc/distro/keys/archlinux.key

No. That is his Arch linux distribution public key was added to Heads in this PR.


@techge The iso boots from this PR.
But the Arch being installed? Not tested.

You reported in the past that initrd needed to be manually generated.
Is it still the case? I915 driver still missing?

**Comment by tlaurion** [comment]
@techge : To download prebuilt roms: https://github.com/osresearch/heads-wiki/issues/88

**Comment by tlaurion** [comment]
> i see this error image

So following your comment here https://github.com/osresearch/heads/issues/1117#issuecomment-1046274875 I expect you are using x230-maximized ROM. And following the error you have https://github.com/osresearch/heads/pull/1120#issuecomment-1048781043 even through ISO was signed in FEB 2022, I expect you are not running the ROM produced by this PR when clicking https://github.com/osresearch/heads/pull/1120/commits/8f6c61cb1afb8a4fcb671a4c1bb9ea0136040558 green mark, x230-maximized board, artifacts and then downloading the full ROM.

**Comment by tlaurion** [comment]
@lynxred And I just realised that this PR was not based on master, and consequently, the x230-maximized board was not built by the CI.

Its happening now with https://github.com/osresearch/heads/pull/1120/commits/1809b3be3d6cf0b7a1129ec23ec079cb57752aab, sorry about that.

**Comment by tlaurion** [comment]
> btw, I just remembered: Ironically, I flashed a coreboot rom last weekend, because I was annoyed that I can not start my arch iso in heads to re-install my system :D

@techge hopefully, you are willing to retest installation/boot and report with ROM produced in this PR!

**Comment by techge** [comment]
> @techge hopefully, you are willing to retest installation/boot and report with ROM produced in this PR!

I am willing, but I can't make any promises about when this will happen. I **try** to do it this week though. I am sorry.

**Comment by tlaurion** [comment]
Just retested from ISO boot:
- Q4.1, Q4.0
- Archlinux
- Tails 4.26

**Review by MrChromebox — APPROVED** [review]

**Pull request merged**
