### PR TITLE
Update flashrom to 1.0

### PR DESCRIPTION
**Pull request by kakaroto**
This adds skylake support in flashrom.

### CODE REVIEW

**Comment by flammit** [comment]
Does the 0.9.9 patch still work?  I recall trying to do this upgrade and running into problems there.

**Comment by kakaroto** [comment]
Oh, there's a pretty big flashrom patch for 0.9.9 that I forgot about. It adds a bunch of stuff, some ast1100 device support, 4 byte addressing mode for spi, progress reporting, thinkpad x220 whitelisted, and a bunch of other small features I suppose. Would need to go through it and see what needs to be ported to 1.0 (and why they weren't upstreamed)

For flashrom 1.0, it works, I even tested it from the recovery shell, it dumped the flash without issues (I didn't try to write, but reading was enough of a test to confirm it works).

**Comment by osresearch** [comment]
The 0.9.9 patch was all about reducing the size of the binary (nearly 1 MB with all the drivers?) and ensuring that it was possible to flash even if IFD was not unlocked (ignore read failures).

Moving to `flashtool` where supported will help reduce the dependency on the patch.

Or we can try to convince the flashroom devs to make it more modular in the build and/or allow partial reflashes without trying to read the entire ROM.

**Comment by kakaroto** [comment]
Ok. but most of the drivers are disabled in the make arguments, the patch that removed some chipsets was reverted in commit f7de7d73 due to issue #249.
The binary of 0.9.9 was 193KB, the one for 1.0 is 490KB. Once compressed with 'xz', the size becomes 71KB for 0.9.9 and 106KB for 1.0, so a 35KB difference in the resulting initrd.

Commit 0f299fe4 however is what brought the most changes to the patch. If these need to go back in, they need to be made into separate patches in a series.

**Comment by osresearch** [comment]
It's not possible* to unlock the IFD from software, so flashing the unlocked IFD and cleaned ME requires physical access.

@kakaroto will the IFD be unlocked on the LIbrem machines?  The issue with flashrom reading the entire chip even for a partial reflash can cause problems if the ME region is locked.



____
* Without discovering a new vulnerability in the PCH or ME handling of the flash descriptor write permission checks

**Comment by kakaroto** [comment]
On the librems, the IFD gives full read/write access to the entire flash. 
By the way, for the non-librems out there, can the '--ifd -i bios' option to flashrom be used to make it read/write only the BIOS region and ignore the ifd/me regions if they are locked. This way, you won't need a patch to flashrom to make it ignore read errors.

By the way, I see in the 0.9.9 patch that there was some code to add a progress bar/report of some sort.
I wrote a simple parser of flashrom -V output that transforms it into a progress bar (the function flashrom_progress) : https://code.puri.sm/kakaroto/coreboot-files/src/master/build_coreboot.sh#L246
Maybe it can be copied/reused in heads (note, the total rom size is hardcoded to 16MB in that script).

**Comment by osresearch** [comment]
The `--ifd -i bios` must be new in 1.0.0.  It 0.9.9 it would still try to read the entire ROM even if `-i bios` were used, which was one of the reasons that the patch was required.

**Comment by kakaroto** [comment]
I never tried it, the `-i bios` might still make it try to read the entire rom but only write the bios region, I don't know. Either way, it might be a good idea to patch it to not read the me region if `-i bios` is given as argument. The `--ifd` just means 'read the layout from the ifd' instead of reading the layout from a `--layout` argument

**Comment by kakaroto** [comment]
Cool, thanks for merging. Did you test the '--ifd -i BIOS' option in 8108e419fe4789e5671cde8f6aa7a38a2be7a382  (in the code I see the region named as 'bios' when loaded from ifd, I don't see the comparison as being case insensitive) ?

**Pull request merged**
