### PR TITLE
xx30 boards: fixing CONFIG_CBFS_SIZE=0x710000 for x230 and t430 boards

### PR DESCRIPTION
**Pull request by tlaurion**
Probable fix for #815 and #667

### CODE REVIEW

**Comment by tlaurion** [comment]
Build was successful: https://app.circleci.com/pipelines/github/tlaurion/heads/360/workflows/f32d840f-6dfb-4904-ac19-98d2870cae47/jobs/388

Roms testable direct links:
x230: https://388-103208611-gh.circle-artifacts.com/0/build/x230/coreboot.rom
t430: https://388-103208611-gh.circle-artifacts.com/0/build/t430/coreboot.rom

@Trapacid @nickfrostatx @lsafd @bwachter
Please follow : https://github.com/osresearch/heads/issues/815#issuecomment-684097153
Above CircleCI builds are fixing CBFS. This is what we want to test upon a ME cleaning as per recommendation.

Please report back success/failing.
@flawedworld : if you have anything to add, please advise.

**Comment by tlaurion** [comment]
Note: 710000 is the maximum size possible without modifying IFD to maximize BIOS region consequently of having reduced ME region, following this thread https://github.com/osresearch/heads/issues/667#issuecomment-638971582

**Comment by tlaurion** [comment]
> x230: https://388-103208611-gh.circle-artifacts.com/0/build/x230/coreboot.rom
Tested and works as expected. Waiting for someone to confirm that the PR works on the t430 and fixes the issue.

**Comment by Trapacid** [comment]
Will test t430 config this evening.

**Comment by tlaurion** [comment]
@Trapacid result?

**Comment by Trapacid** [comment]
@tlaurion t430 CBFS size change to 0x710000 worked successfully.

**Pull request merged**
