### PR TITLE
WIP: Add support for TPM2 in all shell scripts

### PR DESCRIPTION
**Pull request by aesrentai**
This is broken and will be for the foreseeable future.  The goal is to replace all tpm 1.2 commands with their tpm2 equivalent, as well as following tpm2 best practices to ensure maximum security (ie, enabling parameter encryption, locking the OS out TPM2 platform authorization, etc).

Note: this should be merged on top of #893 but for some reason if I select that as the branch to merge on top of github loses it and wants to merge 116 commits.  Whenever that is merged I'll rebase on top of master.

### CODE REVIEW

**Comment by tlaurion** [comment]
Complementary @aesrentai 

https://github.com/hardenedvault/vaultboot/commit/4506fc26d0d9aed1e15030bbf8cd49cede6c4d49

**Comment by aesrentai** [comment]
I saw that commit already actually, and I'll probably take some code from it.  From a high level it takes a similar approach, creating a generic wrapper for each tpm command and then checking for tpm 1.2 or tpm2 in each wrapper.

**Comment by daringer** [comment]
hey together, I'm trying to test this on real hardware, got this:
image

but can't promise this isn't my fault, as I do not know (yet) all tpm-related information of the platform, mainly how the tpm is connected, or which tpm it actually is, just know it's a tpm2 from my memory of the original bios.

but for *reasons unknown* I cannot go back to the original firmware, I'll get this sorted out soon then I'll report again, just wanted to make sure you guys know I am also looking into this

**Comment by shamen123** [comment]
>mainly how the tpm is connected, or which tpm it actually is, just know it's a tpm2 from my memory of the original bios.
> 
@daringer  in your board config did you change the following? For tpmx script to understand which TPM you have it needs to have the correct TPMtype set in boards/<yourboard>

export CONFIG_TPM=y
 to
export CONFIG_TPM2=y

That bing said im not sure the tpm2 work is fully complete and it looks like the error is that tpmx is not passed the correct parameters at some point around the ehci module. I am due to start playing with the tpm2 variant soon as I have a tpm2 for one of my boards. might try later this evening.

**Comment by shamen123** [comment]
welp, tpm2 wont build ...

export CONFIG_TPM2 in board config, using @aesrentai tpm2-shell-bringup-upstream branch 

`    CC         bootblock/security/tpm/tss/tcg-1.2/tss.o
    CC         bootblock/security/tpm/tss/tcg-2.0/tss.o
src/security/tpm/tss/tcg-2.0/tss.c:19:7: error: no previous prototype for 'tpm_process_command' [-Werror=missing-prototypes]
 void *tpm_process_command(TPM_CC command, void *command_body)
       ^~~~~~~~~~~~~~~~~~~
src/security/tpm/tss/tcg-2.0/tss.c:320:10: error: conflicting types for 'tlcl_define_space'
 uint32_t tlcl_define_space(uint32_t space_index, size_t space_size,
          ^~~~~~~~~~~~~~~~~
In file included from src/security/tpm/tss/tcg-2.0/tss.c:8:
src/security/tpm/tss.h:26:10: note: previous declaration of 'tlcl_define_space' was here
 uint32_t tlcl_define_space(uint32_t index, uint32_t perm, uint32_t size);
          ^~~~~~~~~~~~~~~~~
src/security/tpm/tss/tcg-2.0/tss.c:363:10: error: no previous prototype for 'tlcl_get_hash_size_from_algo' [-Werror=missing-prototypes]
 uint16_t tlcl_get_hash_size_from_algo(TPMI_ALG_HASH hash_algo)
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/security/tpm/tss/tcg-2.0/tss.c:411:10: error: no previous prototype for 'tlcl_get_capability' [-Werror=missing-prototypes]
 uint32_t tlcl_get_capability(TPM_CAP capability, uint32_t property,
          ^~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
`

**Comment by shamen123** [comment]
@daringer the issue appears to be the set -e command in tpmx (line 6). removing this line allows the $1 variable to pass through to the functions reset and extend in the wrapper. Leaving this in means $1 is always 'pipefail'

**Comment by aesrentai** [comment]
> hey together, I'm trying to test this on real hardware, got this: image
> 
> but can't promise this isn't my fault, as I do not know (yet) all tpm-related information of the platform, mainly how the tpm is connected, or which tpm it actually is, just know it's a tpm2 from my memory of the original bios.
> 
> but for _reasons unknown_ I cannot go back to the original firmware, I'll get this sorted out soon then I'll report again, just wanted to make sure you guys know I am also looking into this

My tree has a bunch of random hacks (not public) and I haven't actually tested this on real hardware yet.  Unfortunately I have not had tons of time to work on this recently.  In other words, any errors you encounter are almost certainly me, not you, and why this is marked WIP.

**Comment by tlaurion** [comment]
@daringer @aesrentai @shamen123 @root-hardenedvault : collaboaration here would be awesome.

**Comment by daringer** [comment]
yup I can boot my system now, I have seen measured boot values in PCR, no /dev tpm device yet, but this is another issue, so in short: I am progressing towards a state where I can actually help developing on this.

Apart from that TPM2 tooling (the modules from https://github.com/osresearch/heads/pull/893) are not upstream, @tlaurion how do you see this being included into heads ? one big PR including the modules and the `tpmx` stuff, or should we maybe first include the modules to make things easier to develop on top on it ?

**Comment by tlaurion** [comment]
@daringer I couldn't test myself, but having both in a PR wouldn't hurt if tpmx wrapper is still working for TPM 1! Congrats!

I recall that recovery should be in its own file to be measured by tpm2 toolset?

Having a PR to do some regression test for other boards would be a good step.

Looking at discussions that happened on slack would give you insights on what needed to be done on acpi tables to have the device recognised from oses?

Let me know, I don't have a strong opinion, as long as it doesn't break things.

Last time I checked, @hardened-vault implementation was working for him but building instructions were not clear and dependences not updated.

**Comment by daringer** [comment]
okok, sounds good to me, then I will likely first target a PR with something that builds and include all the necessary stuff (under the line this will be: #893 + #1031 on top of the current master) using this we can first check if things work as intended with the `tpmx` wrapper - feels like a legit 1st step...

**Comment by tlaurion** [comment]
Again, wanting to know why not https://github.com/hardenedvault/vaultboot/commit/4506fc26d0d9aed1e15030bbf8cd49cede6c4d49

@aesrentai @daringer

**Comment by aesrentai** [comment]
@daringer @tlaurion apologies for the long wait, school got very busy.  Now it's summer however and I'll have time to finish this along with #1030 .  I completely forgot where I was, however, so I'll get back to you late this week on why I didn't just copy the entire hardenedvault wrapper-- I remember I had a reason but honestly I forgot what it was.

**Comment by tlaurion** [comment]
> I completely forgot where I was, however, so I'll get back to you late this week on why I didn't just copy the entire hardenedvault wrapper-- I remember I had a reason but honestly I forgot what it was.

@daringer @aesrentai We are at a stage, with KVM/QEMU support under #1188 for swtpm HOTP and local testing, to take a leadership decision on what implementation to chose and go forward.

Personally, I would take @root-hardenedvault implementation, based on #893 and #907 prior work and go from there, making hardenedvault approach upstream (tested and used in hardware already).

@aesrentai @daringer  : your input on his approach and why you decided to create/use another one (while similar) would be interesting prior of going forward.

#1188 board configurations can be reused easily to create `-tpm2` instead of tpm in additional board configurations to test without real hardware first. #1188 will be merged soon.

I'm asking for your input, since I would take that ball and move it forward under paid grant application work, thanks to Nlnet.

**Comment by daringer** [comment]
#1188 is a very cool thing, TPM2 was not moved forward from my side as I miss some capable tpm2 hardware for some time now...

> @aesrentai @daringer : your input on his approach and why you decided to create/use another one (while similar #1109 ) would be interesting prior of going forward.

No strong opinion here, I adopted mainly @aesrentai's approach, so under the line from the risk perspective I would also suggest to go for the  hardenedvault

**Comment by tlaurion** [comment]
> #1188 is a very cool thing, TPM2 was not moved forward from my side as I miss some capable tpm2 hardware for some time now...
> 
> > @aesrentai @daringer : your input on his approach and why you decided to create/use another one (while similar #1109 ) would be interesting prior of going forward.
> 
> No strong opinion here, I adopted mainly @aesrentai's approach, so under the line from the risk perspective I would also suggest to go for the hardenedvault

@aesrentai @daringer @shamen123 : I would call for participation under #1292 !

**Comment by tlaurion** [comment]
Superseded by #1292

**Pull request closed without merging**
