### PR TITLE
Started update of xen to 4.8.1-4 for Qubes 4

### PR DESCRIPTION
**Pull request by flammit**
No reproducibility tests yet, but compilation, installation and boot seem to work (though VMs are boot seem unstable).

Had to alter the `head.S` Xen patch due to a change in a register.

### CODE REVIEW

**Comment by flammit** [comment]
Does it make sense to make a separate branch for Qubes 4 for testing purposes?

**Comment by osresearch** [comment]
I haven't tested Qubes 4.0 yet; is there a working ISO for experimentation?

LVM thin provisioning #202 is probably a blocker.

**Comment by osresearch** [comment]
Removing the `vga.c` hacks from Xen (issue #227) seems to have caused a conflict, but hopefully makes for an easier overall merge.

**Comment by flammit** [comment]
There are a couple posts in qubes-devel with preliminary isos. Here's the latest:

https://groups.google.com/forum/m/#!topic/qubes-devel/jeAsPQjImlU

When I tried the first one on x230, I couldn't get sys-USB to start (USB pci issue), but it seemed to install and boot okay. LVM-thin is an option but not the default yet.

**Comment by flammit** [comment]
Rebased patch to current master (w/o the vga tweaks).

Tested the 20170718 ISO on an x230.  Everything seems to work (usb/network/firewall) but with the caveats described in the qubes-devel post.  Be sure to use LVM instead of LVM thin provisioning.

**Comment by flammit** [comment]
Looks like there are additional qubes xen command line parameters from grub that may need to be supported.

**Comment by flammit** [comment]
FYI - https://www.qubes-os.org/news/2017/07/31/qubes-40-rc1/

**Comment by flammit** [comment]
FYI there's a commit in qubes-vmm-xen that might be necessary if we update the Heads iommu/igfx behavior - https://github.com/QubesOS/qubes-vmm-xen/commit/f6fdebef909d8a8f8ffd735de5514d00402c289d 

I believe I had the iommu enabled for intel graphics (in the non-i915 mode Heads mode) and it was fine, but will test again this weekend and the new RC1 cut.

**Comment by flammit** [comment]
Please hold off on this merge. I'll update PR so that the xen version is configurable.

**Comment by flammit** [comment]
PTAL - the xen version can be controlled by `CONFIG_XEN_VERSION=4.6` or `CONFIG_XEN_VERSION=4.8` in the board config files: `x230-generic.config` etc.

**Comment by osresearch** [comment]
Thanks for tracking the xen updates.  I'll merge this in.

**Pull request merged**
