### PR TITLE
t420-maximized boards: build against coreboot 4.13

### PR DESCRIPTION
**Pull request by natterangell**
Bump Coreboot to version 4.13 and enable measured boot. This obviates the need for coreboot 4.8.1 0030-sandybridge.patch

Tested and verified [here](https://github.com/osresearch/heads/issues/692#issuecomment-862577188).

Would be nice to get confirmation from other board owners. Tagging @SebastianMcMillan @alexmaloteaux

### CODE REVIEW

**Comment by tlaurion** [comment]
@SebastianMcMillan @alexmaloteaux : measured boot output here:

https://github.com/osresearch/heads/issues/692#issuecomment-862577188

**Comment by tlaurion** [comment]
@SebastianMcMillan @alexmaloteaux since I do not own the board, I would need at least one confirmation prior of merging and moving CI config for that board to depend on 4.13 material on CircleCI.

**Comment by tlaurion** [comment]
CircleCI build happening here: https://app.circleci.com/pipelines/github/tlaurion/heads/732/workflows/812c5598-47ca-49e1-9819-6dd2f985d633

Note: CircleCI config didn't have to be changed, since t420 builds (and all others) depend on librem_mini build cache, which is coreboot 4.13.

Artifacts will be available there in like 8 hours (caches get deleted after 30 days of uselessness [not used by another build])

**Comment by tlaurion** [comment]
CircleCI builds can be seen here:
t420-maximized: https://app.circleci.com/pipelines/github/tlaurion/heads/732/workflows/812c5598-47ca-49e1-9819-6dd2f985d633/jobs/1072
 t420-hotp-maximized: https://app.circleci.com/pipelines/github/tlaurion/heads/732/workflows/812c5598-47ca-49e1-9819-6dd2f985d633/jobs/1072

Build artifacts (roms) resulting of this PR can be downloaded here:
t420-maximized: https://app.circleci.com/pipelines/github/tlaurion/heads/732/workflows/812c5598-47ca-49e1-9819-6dd2f985d633/jobs/1078/artifacts
t420-hotp-maximized: https://app.circleci.com/pipelines/github/tlaurion/heads/732/workflows/812c5598-47ca-49e1-9819-6dd2f985d633/jobs/1078/artifacts

As current board config, only the full rom is created. Will need to fix that....

**Comment by tlaurion** [comment]
@akfhasodh have you tested this under #999 ?

**Comment by tlaurion** [comment]
> @akfhasodh have you tested this under #999 ?

@akfhasodh Is that what was tested under #1004 ? Or master over coreboot 4.8.1?

**Comment by tlaurion** [comment]
@akfhasodh can I add you under #692  for the t420 board?
Will rebase @natterangell branch on master and link the new build happening here.
Will then edit the post with links to fully internally flashable rom from CircleCI.

**Comment by akfhasodh** [comment]
@tlaurion yes

**Comment by tlaurion** [comment]
@akfhasodh a build occured for the same coomit id (3e13af1) 29 days ago for which artifacts exists:
https://app.circleci.com/pipelines/github/tlaurion/heads/732/workflows/812c5598-47ca-49e1-9819-6dd2f985d633/jobs/1072/artifacts
Where direct link to internally fully flashed rom for t420 maximized HOTP board is here (if you have a Nitrokey Pro/Nitrokey Storage or Librem Key):
https://1072-103208611-gh.circle-artifacts.com/0/build/t420-maximized/heads-t420-maximized-v0.2.0-1040-g3e13af1.rom

The actual build "should" result in the same hashes.txt file output since from same CI. 
You can wait for the next build to finish or test this one.

**Comment by akfhasodh** [comment]
@tlaurion The issue TOTP/HOTP inconsistency issue still persists on the 4.13 rom. Maybe its an issue with my hardware itself?

**Comment by tlaurion** [comment]
What measurement changes between boots?

**Comment by tlaurion** [comment]
@akfhasodh: Can you please:

1. Validate that you kept settings at reflash (including your public key and /etc/config.user overlay)
2. Reset TPM from GUI (will generate new Qr Code and seal secret to USB Security dongle through HOTP). Save/rename TOTP entree in phone. Reboot.
3. Regenerate TOTP/HOTP through GUI. Will generate a Qr code. Scan it under new name. Those two entree SHOULD give the same TOTP (result of measurements) since we are talking about the same ROM here with same components measured.

[Going into the recovery console is invalidating TOTP unsealing by modifying PCR4](Replacing with https://github.com/osresearch/heads/issues/1008). The measurements calculated with coreboot and exposed through TCPA logs should advise us into what is changing in ROM or if TPM is misbehaving.

**Comment by tlaurion** [comment]
Reviewed tested x230-hotp-maximized board config which doesn't seem to add anything special compared to the t420-hotp-maximized board.

Building here and will retest cbmem and other notes to test my own procedures before asking you to redo.
Build is happening here, reusing cache from yesterday build: https://app.circleci.com/pipelines/github/tlaurion/heads/739/workflows/05a5c7c0-8718-4497-99c6-1d63f385cb15/jobs/1159

**Comment by tlaurion** [comment]
@akfhasodh running
`cbmem -c` at the recovery shell should give your output from recovery shell with the actual measurements being extended in PCR-2.

I would love to see those when it fails, and when it succeeds on coreboot 4.13 t420-hotp-maximized rom

**Comment by akfhasodh** [comment]
@tlaurion turns out the instability was only something I would experience at the beginning, as all my subsequent boots for the past two days have had successful TOTP/HOTP unseals. If I come across the issue again, I will definitely send the differences in cbmem

**Comment by akfhasodh** [comment]
@tlaurion It started again, and it got worse, After I attempted updating qubes dom0 (and failed), I decided to reboot. Upon the reboot I was met with the same issue of inconsistent unseals. But, once I got a proper unseal, it showed a red screen with the TOTP code dispayed, and "HOTP: Invalide code". Up until the failed update things were working fine, unfortunately, I forgot to save the TOTP verification to my phones OTP, so I have no idea whether there was an actual compromise.

**Comment by tlaurion** [comment]
> @akfhasodh running
> `cbmem -c` at the recovery shell should give your output with the actual measurements being extended in PCR-2.
> 
> I would love to see those when it fails, and when it succeeds on coreboot 4.13 t420-hotp-maximized rom

@akfhasodh do you have before/after PCR-2 measurements?

It would be useful to have reports from other t420 owners here.

>  is it possible for heads to have been tampered with without physical access?
Highly doubtful, while still possible. But highly improbable.

**Comment by akfhasodh** [comment]
@tlaurion 
this one, I believe is when it was working properly:
IMG_20210723_132213
And this one is not:
IMG_20210723_132117
Although I may have mixed these up.

**Comment by tlaurion** [comment]
@akfhasodh payload measurements are different

**Comment by akfhasodh** [comment]
I didn't notice the difference, may I ask where?

**Comment by akfhasodh** [comment]
@tlaurion What does this mean?

**Comment by tlaurion** [comment]
Are those measurements stable across reboots?

There was issue created in the past when CBFS regions mismatched available space.  One hypothesis here would be that coreboot measurements of the region mismatches reality.

Coreboot 4.13 uses TCPA logs to output the TPM  measurements into cbmem.

I would recommend reflashing internally,  resetting TPM,  resealing TOTP/HOTP, and taking a screenshot of cbmem when it works. And then retaking a snapshot when it doesn't. 

There is a larger PR trying to bring Heads based on coreboot 4.13 altogether. The T420 and x220 use the same defined CBFS regions.

I would need other board owners output and bug replication to know if there is an issue for xx20 boards and CBFS region.

The payload measurements should not change in time. So something is weird here and needs to be diagnosed.

Using CI builds would be recommended to have exactly the same hashes.

**Comment by tlaurion** [comment]
Superseded by https://github.com/osresearch/heads/pull/1015

**Pull request closed without merging**
