### PR TITLE
logo, bootsplash upload from me

### PR DESCRIPTION
**Pull request by d-wid**
Now that I've got some time I took #1451 and did some stuff on GIMP and (automatically!) traced it with Inkscape to produce imo a serviceable svg.

Also with a PR I can finally upload the xcf used to create the bootsplash, like I said [here](https://github.com/osresearch/heads/issues/1402#issuecomment-1546452818) it is based on this [xcf](https://github.com/Thrilleratplay/coreboot-builder-scripts/issues/15) @Thrilleratplay uploaded.

I hope none if this so far is problematic licence-wise (I'm suspicious though uninformed about the idea of taking something from a presumably proprietary AI generator and re-releasing it under a free licence)

### CODE REVIEW

**Comment by tlaurion** [comment]
Bing would really love to be quoted with a date and a prompt. Will need to find it out.

**Comment by tlaurion** [comment]
> @tlaurion @d-wid yes, they do look good! Although for the AI-generated janus-head, I think the matrix-like background makes it too noisy. Out of those, I think [background-plain-3.jpg](https://github.com/osresearch/heads/pull/1502/files#diff-02702842cc350baa7dceec124b5c2c113e3fec876fb5d3284892204657fbc1dc) or [background-plain.jpg](https://github.com/osresearch/heads/pull/1502/files#diff-3462753acb442e02387382b48dfc4d7133130d9d0b86b3495ded6383c0202925) look best.

_Originally posted by @natterangell in https://github.com/osresearch/heads/issues/1501#issuecomment-1719770899_

**Comment by Tickmeister1** [comment]
Background-binary-2 is my preference.

**Comment by jans23** [comment]
I like background-binary-2.jpg too.

**Comment by Tickmeister1** [comment]
> > @tlaurion @d-wid yes, they do look good! Although for the AI-generated janus-head, I think the matrix-like background makes it too noisy. Out of those, I think [background-plain-3.jpg](https://github.com/osresearch/heads/pull/1502/files#diff-02702842cc350baa7dceec124b5c2c113e3fec876fb5d3284892204657fbc1dc) or [background-plain.jpg](https://github.com/osresearch/heads/pull/1502/files#diff-3462753acb442e02387382b48dfc4d7133130d9d0b86b3495ded6383c0202925) look best.
> 
> _Originally posted by @natterangell in [#1501 (comment)](https://github.com/osresearch/heads/pull/1501#issuecomment-1719770899)_

I feel the "matrix code" effect gives the logo some needed visual softness.  The sharp white version being too harsh to blink onto the screen.  Just my opinion, mind.

**Comment by d-wid** [comment]
Smoothed out the bi/tricolour version of the bootsplash and I think it looks good with some vignette effect now.

Removed some of the shadow on the nose in the matrix binary-2 version. I think it's more readily recognisable as a pair of faces (or heads) that way.

background-plain-3
background-binary-2

**Comment by natterangell** [comment]
Would it be an idea to also frame the QR-code in a matching colour frame of sorts? Might round it out a little.

image

**Comment by d-wid** [comment]
> Would it be an idea to also frame the QR-code in a matching colour frame of sorts? Might round it out a little.
> 
> image

For now I think something like this might be better, but you can play around with the xcf yourself if you want and see what sticks.
background-plain-2

**Comment by tlaurion** [comment]
Seems weird, but the following seems sufficient. 

Microsoft Bing (2023). Graphic art generated by an artificial intelligence model. Retrieved from https://www.bing.com/chat

**Comment by tlaurion** [comment]
@d-wid would be interested into making this go forward. In previous comments, I said I would prefer not having a lot of binaries in git, which means keeping inclusion/removal of binary content. I would go forward and squash those commits, meaning that we would be co-author on your last commit here.


By doing another PR based on this work, I would cite as best as I could bing and move the bootsplash and logos under branding/heads and modify all coreboot configs to point to the symlink of currently chosen bootpslash.

This would resolve https://github.com/osresearch/heads/issues/1468 at the same time.


Oppositions?

**Comment by tlaurion** [comment]
@d-wid please see #1506. I was wandering what is the purpose of the xcf file(4mb to be downloded by anyone downloading heads tree) and if you could take comments from #1506 to rename filename and properly credit previous authors in the present PR?

**Comment by tlaurion** [comment]
Replaced by #1506

**Pull request closed without merging**
