### PR TITLE
Update hotp-verification (fixes #746)

### LINKED ISSUE #746: Upgrade nitrokey-hotp-verification module
@szszszsz upgrade module/nitrokey-hotp-verification with https://github.com/Nitrokey/nitrokey-hotp-verification/commit/1cf1e1f3601b79692b81d409597136b8ff7c723a

### PR DESCRIPTION
**Pull request by alex-nitrokey**
- [x] use newer version of hotp-verification module to avoid patch
- [x] testing new version on board

What do you think, shall I make two separate PRs instead?

(will fix #746)

### CODE REVIEW

**Comment by AUX234** [comment]
Tested and working. This also fixed #737

**Comment by techge** [comment]
> Tested and working.

Does it? It had some problems with it during initializing HOTP (hence still WIP).

**Comment by tlaurion** [comment]
@techge @AUX234 : https://github.com/osresearch/heads/pull/756

**Comment by MrChromebox** [comment]
@tlaurion I'll need to retest to be sure, but IIRC this failed verification when I tested on a Librem13v4

**Comment by tlaurion** [comment]
#756 is just CBFS fix for x230-hotp-verification board which was reported not boot

**Comment by alex-nitrokey** [comment]
It boots and builds indeed, but for me it is not able to do the HOTP verification. Doesn't you had the problem?

Steps to reproduce:
* generate new HOTP secrets
* succeeds and key blinks green
* after that, every check let key blink red and invalid code message appears

**Comment by tlaurion** [comment]
Still not working.

**Comment by alex-nitrokey** [comment]
> Still not working.

Just to make sure: you mean, you are experiencing the same, right?

**Comment by alex-nitrokey** [comment]
I found the issue as described [here](https://github.com/Nitrokey/nitrokey-hotp-verification/pull/17). It is very embarrasing, so let's not talk about it.

As soon as it is merged into master of hotp-verification I will update the version and hash here and thus the PR is ready to merge then.

**Comment by szszszsz** [comment]
@alex-nitrokey Just merged

**Comment by alex-nitrokey** [comment]
Builds and runs as intended, initialization and verification works fine.

**Comment by tlaurion** [comment]
https://github.com/osresearch/heads/pull/756 was merged meanwhile to fix #737

**Comment by tlaurion** [comment]
Non-reproducible

**Comment by tlaurion** [comment]
Sorry closed by error and reopened.

**Comment by MrChromebox** [comment]
looks like we just need to update libremkey-hotp-verification_version to d4adfc58e53e61519adafc3dce2ddf729e7ebc86 (or later; master at 03a198c418a60c54ef3ec67ea8a9a2d29b675b9b currently) and adjust hash accordingly

**Comment by stmc-droid** [comment]
> It boots and builds indeed, but for me it is not able to do the HOTP verification. Doesn't you had the problem?
> 
> Steps to reproduce:
> 
> * generate new HOTP secrets
> * succeeds and key blinks green
> * after that, every check let key blink red and invalid code message appears

I am still having this same issue with a Librem Key. Please let me know how I can help troubleshoot.

**Comment by MrChromebox** [comment]
@stmc-droid see my comment above, this PR needs updating to fix the issue

**Comment by alex-nitrokey** [comment]
> looks like we just need to update libremkey-hotp-verification_version to d4adfc58e53e61519adafc3dce2ddf729e7ebc86 (or later; master at 03a198c418a60c54ef3ec67ea8a9a2d29b675b9b currently) and adjust hash accordingly

I thought I updated this PR as well, but apparently I did it only in #761 hence the confusion, sorry.

**Comment by alex-nitrokey** [comment]
https://github.com/osresearch/heads/pull/748/commits/38ba25706372d22bf1f033c5543b71496e4d7d61 is the corresponding commit which I just forgot to push last week.

**Comment by MrChromebox** [comment]
pushed #774 since this seems to have stalled, and wanted something working we can merge to get master back to functional ASAP

**Comment by techge** [comment]
Commit 38ba257 that is already in this PR should work and uses newer version of hotp-verification... Thus, I do not see the need for #744.

In the end I would suggest to merge #761 instead of the other two PRs anyway (they should not conflict anyway)

**Comment by MrChromebox** [comment]
if 761 is ready then correct no need, but the commit/PR message lists two items under 'things still needed' so my understanding was that it was not ready, and why I pushed a separate PR to fix the issue independently.

**Comment by techge** [comment]
> but the commit/PR message lists two items under 'things still needed' 

Mh, that is strange, aren't they ticked? I ticked them last week or so and they are ticked for me...

**Comment by MrChromebox** [comment]
they show as grey checkboxes for me, which contrasts with the green checkmarks used elsewhere on github so it certainly appears they are not completed

**Comment by szszszsz** [comment]
https://github.com/osresearch/heads/pull/748#issue-432500441 is ticked both for me as well. Maybe you mean different one?

**Comment by MrChromebox** [comment]
if that's ticked, then it's just horrible design

**Comment by techge** [comment]
> if that's ticked, then it's just horrible design

Then it is :D

**Comment by tlaurion** [comment]
Checked
?!?

**Comment by MrChromebox** [comment]
Screenshot from 2020-07-08 20-12-51

guess it's a Chrome(ium)/Linux issue?

**Comment by techge** [comment]
Well, at least there are the marks :joy:

**Pull request merged**
