### PR TITLE
Use HTTPS URL for flashrom

### PR DESCRIPTION
**Pull request by flammit**

### CODE REVIEW

**Comment by paulmenzel** [comment]
I wouldn’t use *fix* but *Use HTTPS URL for flashrom*. Could you please update the descriptions?

**Comment by flammit** [comment]
Done

**Comment by osresearch** [comment]
Merged!

We should also think about the 1.0.0 release which was just announced by Nico on the coreboot list: https://mail.coreboot.org/pipermail/coreboot/2018-January/085890.html

**Comment by flammit** [comment]
Thanks!  And agreed - I'll test flashrom 1.0.0 and also start a branch targeting the upcoming coreboot 4.7 release.

**Pull request merged**
