### PR TITLE
Add support for t530 and w530 dGPU

### PR DESCRIPTION
**Pull request by eganonoa**
This commit adds support for the t530 and w530 boards to enable dGPUs. dGPU's are required for DisplayPort external displays in the t530 dgpu model, and for both the VGA dn DisplayPort external displays in the W530 (which has two dGPUs, the K1000M and K2000M, hence two boards).  The commit does the following:

1. Adds automated extraction scripts for vbios modelled on the me script in the blobs directory (one per board is necessary as it is based on board-specific bios updates), using the [VBiosFinder tool](https://github.com/coderobe/VBiosFinder). 
2. Adds specific boards for the various dGPU models and corresponding coreboot configs.
3. Updates circleci config.yaml to run scripts and test boards.

Tested and working on T530 dgpu and W530 K1000M. dGPU scripts tested on Debian 10 and Ubuntu 21.04.

### CODE REVIEW

**Comment by tlaurion** [comment]
@eganonoa circleci config unfortunately under config.yml instead of .circleci/config.yml so cannot merge. Discussed offline.

**Comment by eganonoa** [comment]
@tlaurion. Fixed. Thanks!

**Comment by tlaurion** [comment]
@eganonoa this PR needs rebasing on master since Librem boards were added

**Comment by eganonoa** [comment]
@tlaurion Thanks. Done!

**Comment by tlaurion** [comment]
Oups, closed instead of merging.
@eganonoa : next time, please be cleaner in commits, as showed in #1084.

**Pull request merged**
