### PR TITLE
Add Librem Key support to Heads

### PR DESCRIPTION
**Pull request by kylerankin**
The Librem Key is a custom device USB-based security token Nitrokey is
producing for Purism and among other things it has custom firmware
created for use with Heads. In particular, when a board is configured
with CONFIG_LIBREMKEY, this custom firmware allows Heads to use the
sealed TOTP secret to also send an HOTP authentication to the Librem
Key. If the HOTP code is successful, the Librem Key will blink a green
LED, if unsuccessful it will blink red, thereby informing the user that
Heads has been tampered with without requiring them to use a phone to
validate the TOTP secret.

Heads will still use and show the TOTP secret, in case the user wants to
validate both codes (in case the Librem Key was lost or is no longer
trusted). It will also show the result of the HOTP verification (but not
the code itself), even though the user should trust only what the Librem
Key displays, so the user can confirm that both the device and Heads are
in sync. If HOTP is enabled, Heads will maintain a new TPM counter
separate from the Heads TPM counter that will increment each time HOTP
codes are checked.

This change also modifies the routines that update TOTP so that if
the Librem Key executables are present it will also update HOTP codes
and synchronize them with a Librem Key.

### CODE REVIEW

**Comment by tlaurion** [comment]
@kylerankin : having a hard time to get a clear answer from Nitrokey guys on when the Nitrokey v2 will be available (was supposed to be during June)

Do you have any insight on that?
Thanks.

**Comment by kylerankin** [comment]
1. I don't have any insight on their release schedule for their next model, unfortunately.
2. The Librem Key will use the very latest Nitrokey Pro firmware, this commit in particular: https://github.com/Nitrokey/nitrokey-pro-firmware/commit/664c11b3e6429551f1b21534efd8ae364047fa87
This contains specific changes for integration with this Heads PR and those firmware changes were only recently committed. Nitrokeys purchased in the past would be running older firmware that wouldn't contain software changes that enable HOTP checks. Anything running firmware at the above revision would match the Librem Keys. I know that Librem Keys will have that firmware revision but I don't know at what point Nitrokey Pros will include those features.

**Comment by tlaurion** [comment]
Can we order them now? 😃

**Comment by kylerankin** [comment]
Very, very soon! We will make a big announcement on our website when they are ready for purchase.

**Comment by tlaurion** [comment]
Nitrokey Pro v2 are ready to order!

**Comment by tlaurion** [comment]
@kylerankin : you see any problems that would arise in porting this to other laptops?
The keys will arrive soon! :)

**Comment by kylerankin** [comment]
The underlying code within this PR doesn't have any Librem laptop-specific hooks. If you have a key, the laptop itself shouldn't matter as long as CONFIG_LIBREMKEY is set and the userpsace tools are built for that image.

That's once this branch gets merged of course :)

**Comment by tlaurion** [comment]
@kylerankin Nitrokey Pro v2 contains https://github.com/Nitrokey/nitrokey-pro-firmware/commit/664c11b3e6429551f1b21534efd8ae364047fa87. 

Any documentation on how to enroll laptops with purekeys/nitrokey pro v2?

**Comment by tlaurion** [comment]
@kylerankin When attempting to build this branch on debian-9 with cmake 3.7.2-1 installed:
```
2018-07-30 19:44:38-04:00 CONFIG libremkey-hotp-verification
INSTALL=/home/user/Downloads/heads-x230/install cmake -DCMAKE_TOOLCHAIN_FILE=./Toolchain-heads.cmake -DCMAKE_AR=/home/user/Downloads/heads-x230t/build/../crossgcc/x86_64-linux-musl/bin/x86_64-musl-linux-ar . 
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.10 or higher is required.  You are running version 3.7.2

```

Any reason why depending on 3.10+? On which distro are you building this?

**Comment by tlaurion** [comment]
@kylerankin :  I see that cmake 3.11 is in fedora-28.

**Comment by 1989gironimo** [comment]
Will the Nitrokey Storage 2 support Heads as well?

**Comment by kylerankin** [comment]
@1989gironimo The Nitrokey Storage, to my knowledge, uses completely different firmware from the Nitrokey Pro v2 and the Librem Key.

**Comment by tlaurion** [comment]
@kylerankin @1989gironimo : Nitrokey said that the Nitrokey Storage 2 supports HOTP "but id doesn't contain the Purism-specific verification feature yet."

**Comment by 1989gironimo** [comment]
What means "yet" in this context? Is this planned to implement in the future™ or is it just possible to implement but there's no interest in implementing this?

Am September 12, 2018 2:40:53 PM UTC schrieb tlaurion <notifications@github.com>:
>@kylerankin @1989gironimo : Nitrokey says that the Nitrokey Storage 2
>supports HOTP "but id doesn't contain the Purism-specific verification
>feature yet."
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/osresearch/heads/pull/426#issuecomment-420673257

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by 1989gironimo** [comment]
> @1989gironimo
> 
> > What means "yet" in this context? Is this planned to implement in the future™ or is it just possible to implement but there's no interest in implementing this?
> 
> HOTP interaction with Heads has been implemented in Nitrokey Pro v2/LibremKey as a beginning.
> Nitrokey Pro v2 firmware is still not user upgradeable without breaking the key plastic shell [and hack it's way through](https://github.com/Nitrokey/nitrokey-pro-hardware).
> 
> Nitrokey has the intention of doing it with the Storage 2, while not giving a clear roadmap on when it will happen.
> 
> FYI: As opposed to Nitrokey Pro, the Storage firmware version is user upgradeable. Pressure them for a clearer roadmap! [I've opened a ticket here to track the request](https://github.com/Nitrokey/nitrokey-storage-firmware/issues/71).

Thanks for your clarification :+1:

**Comment by tlaurion** [comment]
@flammit : had time to troubleshoot [this](https://github.com/osresearch/heads/pull/426#issuecomment-418136881)?

**Comment by osresearch** [comment]
(Coming into this discussion way late...)

Loading the USB module will affect a PCR since `insmod` measures the module before it loads it.  This allows attestation to reflect which modules were loaded.  Is this causing the TPM to not unseal the key?

**Comment by tlaurion** [comment]
@kylerankin https://github.com/tlaurion/heads/commit/8b8662f981795319f945dfbed7d03ea3978a498a needs to be cherry picked. As pointed by @flammit , the problem was in the sealing, PCR5 being modified by USB modules being loaded.

**Comment by tlaurion** [comment]
54eaba3 is a partial fix in regard of #470

**Comment by tlaurion** [comment]
@1989gironimo HOTP supported in Nitrokey Storage since January.

See referred ticket: https://github.com/Nitrokey/nitrokey-storage-firmware/issues/71

_Sent from my Galaxy S3 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by 1989gironimo** [comment]
@tlaurion cool thing! Has this been tested already with HEADS? I'd be glad to be the Guinea pig :)

**Comment by tlaurion** [comment]
You'd be the guinea pig :)

On April 13, 2019 2:39:54 AM EDT, 1989gironimo <notifications@github.com> wrote:
>@tlaurion cool thing! Has this been tested already with HEADS? I'd be
>glad to be the Guinea pig :) 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/osresearch/heads/pull/426#issuecomment-482781806

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by szszszsz** [comment]
Hi! FYI Nitrokey Storage v0.54 now supports HOTP validation similarly to Nitrokey Pro. Needs small adaptation of the client app.

**Pull request merged**
