### PR TITLE
Scale fbwhiptail and console font for high resolution displays

### PR DESCRIPTION
**Pull request by JonathonHall-Purism**
Improve output on high resolution displays.

Mini v1/v2 work significantly better on 3840x2160.  (Previously, the console font was very tiny, and fbwhiptail would mode-switch every time it started and exited.  For example, on my Samsung TV the mode switches take >10 seconds, and it often failed to sync to the new mode entirely.)

Librem 15v4 no longer has to force a 1080p mode on the eDP panel, both console and fbwhiptail are sharper.

---

fbwhiptail detects a scale factor automatically, aiming to approximate logical height 1080 with an 0.5x scale increment.  `FBWHIPTAIL_SCALE` can be set to force a particular scale factor for testing (within limits).  fbwhiptail no longer looks for a 1080p mode when the default is 2160p.  https://source.puri.sm/firmware/fbwhiptail/-/merge_requests/5

Currently, fbwhiptail scaling starts to take effect at height 1350 lines (1.5x, so 900 lines logical height).

The Linux console font size is doubled for height >= 1350 lines.  The only options here are 1x or 2x (I did not add any fonts, just doubled the built-in font at runtime).  This goes to 2x when fbwhiptail starts using 1.5x, which favors "too large" over potentially "too small".

---

@Tonux599 @househead @pcm720 x230 eDP 1440p owners!  How does this change look for you - do you like 1.5x in fbwhiptail or prefer to stay at 1.0x?  Is the Linux console OK at 1.0x?

Scaling based on resolution is just a heuristic, in general it depends on the physical size of the screen, how close you are to it, and a bit personal preference.  We can tweak it if needed.

I enabled console scaling too as I saw some mentions that 1600p panels are possible with mods, but I don't know that anyone here has one.  ~~1440p won't be affected by the console font size change currently.~~  Based on feedback, 1440p does get the 2x font now.   (To try 2x when it doesn't apply by default, do from a recovery console: `setfont -O /tmp/font; setfont -d /tmp/font`.)

### CODE REVIEW

**Comment by pcm720** [comment]
Just flashed [774955c](https://github.com/osresearch/heads/pull/1459/commits/774955cc048c7e0b5438c2c21d7f63176c66380a).
fbwhiptail looks pretty nice at 1.5x, maybe a little better than 1.0x. Linux console at 1.0x is a little too small for me, especially when fbwhiptail scaling is set to 1.5. I think that 2x would be much more readable

**Comment by JonathonHall-Purism** [comment]
Thanks for testing @pcm720 !  I reduced the threshold so 1440p displays will get the 2x console font.

**Comment by tlaurion** [comment]
@JonathonHall-Purism needs rebase on master!

Should this be merged before/after https://github.com/osresearch/heads/pull/1403 ?

**Comment by JonathonHall-Purism** [comment]
Thanks, rebased.

Ordering vs. #1403 doesn't matter as long as the modules/fbwhiptail conflict is resolved correctly.  Resolution scaling works for both DRI and linuxfb, and the linuxfb improvements included in this branch won't have any effect if you are still on DRI.

If you think the fbwhiptail changes look good, I will merge the fbwhiptail MR, tag another release, and update this PR

**Comment by tlaurion** [comment]
I like what I see and thanks to @pcm720 we have an input permitting to merge!

**Pull request merged**
