### PR TITLE
migrate all commmunity supported boards to coreboot 4.13 (Except KGPE-D16 which stays to coreboot 4.11)

### PR DESCRIPTION
**Pull request by tlaurion**
### ROMS to be tested by board owners
https://github.com/osresearch/heads/pull/1015#issuecomment-894523907

### History
Supersedes 
- [x] https://github.com/osresearch/heads/pull/949
- [x] https://github.com/osresearch/heads/pull/944

Still unanswered and needs testing and confirmation of need (@daringer @jans23 @alex-nitrokey  ?) 
- [x] https://github.com/osresearch/heads/pull/944#issuecomment-886840825 
Edit: Tested by @nitrosimon [here](https://github.com/osresearch/heads/pull/1015#issuecomment-946582824)

Includes (will rebase once merged)

- [x]  #1014 
- [x] #1013 

Bug fixes needed to install QubesOS 4.1 from verified ISO under Heads (a dd'ed ISO over USB will boot and install from boot from USB menu)
- [x] https://github.com/QubesOS/qubes-issues/issues/6792

Todos:

- [x] Review results of with/without blobs set for xx20 and xx30 boards

### Before merging

[ROM testing (needs feedback)](https://github.com/osresearch/heads/pull/1015#issuecomment-894523907)

Per commited users
- [x] [x220](https://github.com/osresearch/heads/pull/1015#issuecomment-895003945) (@techge) 
EDIT : [tested by @BlackMaria](https://github.com/osresearch/heads/pull/1015#issuecomment-922403518) 
- [ ] ~[t430s](https://github.com/osresearch/heads/pull/1015#issuecomment-894708158) (@Siproqu)~
Edit: timeout reached. Will be seperate PR.

Rom testing needing users to stand up:
- [x] t420 (xx20): @alexmaloteaux @natterangell @akfhasodh. 
- [x] t430 (xx30): @Thrilleratplay @alexmaloteaux @nickfrostatx @lsafd @bwachter @daringer @jans23 @alex-nitrokey  @shamen123 EDIT: Tested [here](https://github.com/osresearch/heads/pull/1015#issuecomment-905505280)

Reduce/synthetise

- [ ] commits and associated comments if requested.

### CODE REVIEW

**Comment by tlaurion** [comment]
TODO: Review results of with/without blobs set for xx20 and xx30 boards. 
Results are weird and coreboot configs are still inconsistent (some with some without)

With:
```
"/home/user/heads/build/coreboot-4.13/x230-hotp-maximized/cbfstool" "/home/user/heads/build/coreboot-4.13/x230-hotp-maximized/coreboot.rom" print
FMAP REGION: COREBOOT
Name                           Offset     Type           Size   Comp
cbfs master header             0x0        cbfs header        32 none
fallback/romstage              0x80       stage           85100 none
cpu_microcode_blob.bin         0x14d80    microcode       26624 none
fallback/ramstage              0x1b600    stage           97689 none
config                         0x33400    raw               756 none
revision                       0x33740    raw               691 none
fallback/dsdt.aml              0x33a40    raw             14615 none
vbt.bin                        0x373c0    raw              1433 LZMA (4281 decompressed)
cmos_layout.bin                0x379c0    cmos_layout      1884 none
fallback/postcar               0x38180    stage           25816 none
fallback/payload               0x3e6c0    simple elf    7131591 none
(empty)                        0x70b8c0   null          4539608 none
bootblock                      0xb5fdc0   bootblock       65536 none
```

Without:
```
"/home/user/heads/build/coreboot-4.13/x230-hotp-maximized/cbfstool" "/home/user/heads/build/coreboot-4.13/x230-hotp-maximized/coreboot.rom" print
FMAP REGION: COREBOOT
Name                           Offset     Type           Size   Comp
cbfs master header             0x0        cbfs header        32 none
fallback/romstage              0x80       stage           85100 none
cpu_microcode_blob.bin         0x14d80    microcode       26624 none
fallback/ramstage              0x1b600    stage           97730 none
config                         0x33400    raw               792 none
revision                       0x33780    raw               697 none
fallback/dsdt.aml              0x33a80    raw             14615 none
vbt.bin                        0x37400    raw              1433 LZMA (4281 decompressed)
cmos_layout.bin                0x37a00    cmos_layout      1884 none
fallback/postcar               0x381c0    stage           25816 none
fallback/payload               0x3e700    simple elf    7131591 none
(empty)                        0x70b900   null          4539544 none
bootblock                      0xb5fdc0   bootblock       65536 none
```

With: 
- empty space: 4539608

Without: 
- empty space: 4539544

**Comment by tlaurion** [comment]
All boards now building with cryptsetup2 and coreboot config CONFIG_USE_BLOBS is not set for xx20 and xx30.
Will cleanup this PR with minimal commit numbers once build is successful

**Comment by tlaurion** [comment]
rebased on master

**Comment by tlaurion** [comment]
rebased on master with build optimization in to compare speeds of fresh build and rebuilds

**Comment by tlaurion** [comment]
https://github.com/osresearch/heads/pull/1015/commits/b9468f5a13fc108c33b35425894cb1a9e39decd6 reduced complied time of https://app.circleci.com/pipelines/github/tlaurion/heads/758/workflows/f42445f7-258b-472f-8a60-1a87b491cbed by 45 minutes. Fresh builds doing the cache will result in even greater gains since based on all reused binaries for x86 to be based on cache passed to workspaces.

**Comment by tlaurion** [comment]
From https://github.com/osresearch/heads/issues/692:
x220 (xx20): @techge @eganonoa @shamen123 @Thrilleratplay @userongihu @BlackMaria
t420 (xx20): @alexmaloteaux @natterangell
t430 (xx30): @Thrilleratplay @alexmaloteaux @nickfrostatx @lsafd @bwachter @Trapacid
t430s and additional information (xx30): @Siproqu
x230 (xx30): already tested.

I would love to have at least one board owner to report results of testing artifacts of https://app.circleci.com/pipelines/github/tlaurion/heads/758/workflows/f42445f7-258b-472f-8a60-1a87b491cbed if possible?

**Comment by tlaurion** [comment]
Direct link to roms from past successfully builds for external flashing (note below for people having IFD unlocked so internal flashing can be done. But please only do if you have an external reprogrammer available, and backup first so you can restore!)

### Jargon

**maximized** (without hotp): Requires you to have a GPG smartcard to detach sign /boot content. Maximized builds imply a static Ethernet MAC generated and included in the ROM. This consequently requires MAC Randomization being applied on the OS level. ME is cleaned automatically from downloaded+verified Lenovo latest ME available update and reduces ME size in IFD to put that freed space into BIOS region, which coreboot uses under its CBFS region in the configuration file. This ROM permits the whole SPI to be flashed internally.

**If flashed internally with ME unlocked and IFD unlocked, a `mount-usb` and `flashrom -p internal -w /media/image.rom` with that rom put on a USB dongle should work. But it is strongly adviced only to do this if you have an external reprogrammer to reflash if necessary**

**maximized-hotp**: As maximized build above, where that rom additionally requires users to have a Librem Key/Nitrokey Pro/Nitrokey Storage USB Security dongle to do remote attestation. Only flash those images if you have such devices and remember your GPG Admin PIN, required to seal measurements into your dongle's smartcard. Heads permits you to factory reset those devices at boot if no user's public key is found injected in the ROM. You can also inject previously generated public key, or flash the rom keeping previous settings if flashed internally from previous buiilds.

**Legacy** (only for xx30 builds: t430 and x230): Doesn't require initial unlocking of IFD regions. Doesn't require either neutering ME. Consequently less space is available from freed ME space, and those boards have some features deactivated and some UX regressions. For example, dropbear (ssh) is not in. Neither is FBWhiptail, but console Whiptail (using gui-init) is still there. Please read the new board configurations in this PR. ( @flammit and others: your input is important here)





### xx20 (needs more testing, this is where #693 #1004 seem to have occured and its not clear that its completely fixed as of now. I DO NOT OWN A xx20! (t420 nor x220))
t420-hotp-maximized:
https://1537-103208611-gh.circle-artifacts.com/0/build/t420-hotp-maximized/heads-t420-hotp-maximized-v0.2.0-1058-gb9468f5.rom

t420-maximized:
https://1532-103208611-gh.circle-artifacts.com/0/build/t420-maximized/heads-t420-maximized-v0.2.0-1058-gb9468f5.rom

x220-hotp-maximized:
https://1542-103208611-gh.circle-artifacts.com/0/build/x220-hotp-maximized/heads-x220-hotp-maximized-v0.2.0-1058-gb9468f5.rom

x220-maximized:
https://1539-103208611-gh.circle-artifacts.com/0/build/x220-maximized/heads-x220-maximized-v0.2.0-1058-gb9468f5.rom

### xx30
x230-hotp-maximized (already tested multiple times. T430 counterpart needs to be tested though @daringer @jans23 others, see below).
bottom SPI: https://1530-103208611-gh.circle-artifacts.com/0/build/x230-hotp-maximized/heads-x230-hotp-maximized-v0.2.0-1058-gb9468f5-bottom.rom
TOP SPI: https://1530-103208611-gh.circle-artifacts.com/0/build/x230-hotp-maximized/heads-x230-hotp-maximized-v0.2.0-1058-gb9468f5-top.rom
Internal Flashing: https://1530-103208611-gh.circle-artifacts.com/0/build/x230-hotp-maximized/heads-x230-hotp-maximized-v0.2.0-1058-gb9468f5.rom

Legacy x230 (not maximized builds. Not requiring to neuter ME per instructions:https://osresearch.net/Clean-the-ME-firmware/ nor unlocking IFD per same instructions.):
external initial flash of TOP SPI: https://1548-103208611-gh.circle-artifacts.com/0/build/x230-flash/heads-x230-flash-v0.2.0-1058-gb9468f5-top.rom
Internal flashing: https://1531-103208611-gh.circle-artifacts.com/0/build/x230/heads-x230-v0.2.0-1058-gb9468f5.rom

Legacy x230-hotp (not maximized builds. Not requiring to neuter ME per instructions:https://osresearch.net/Clean-the-ME-firmware/ nor unlocking IFD per same instructions.):
external initial flash of TOP SPI: https://1548-103208611-gh.circle-artifacts.com/0/build/x230-flash/heads-x230-flash-v0.2.0-1058-gb9468f5-top.rom
Internal flashing after x230-flash applied to top SPI: https://1538-103208611-gh.circle-artifacts.com/0/build/x230-hotp-verification/heads-x230-hotp-verification-v0.2.0-1058-gb9468f5.rom

t430-hotp-maximized:
Bottom SPI: https://1540-103208611-gh.circle-artifacts.com/0/build/t430-maximized/heads-t430-maximized-v0.2.0-1058-gb9468f5-bottom.rom
TOP SPI: https://1540-103208611-gh.circle-artifacts.com/0/build/t430-maximized/heads-t430-maximized-v0.2.0-1058-gb9468f5-top.rom
Internal flashing: https://1540-103208611-gh.circle-artifacts.com/0/build/t430-maximized/heads-t430-maximized-v0.2.0-1058-gb9468f5.rom

t430-maximized:
Bottom SPI: https://1540-103208611-gh.circle-artifacts.com/0/build/t430-maximized/heads-t430-maximized-v0.2.0-1058-gb9468f5-bottom.rom
Top SPI: https://1540-103208611-gh.circle-artifacts.com/0/build/t430-maximized/heads-t430-maximized-v0.2.0-1058-gb9468f5-top.rom
Internal Flashing: https://1540-103208611-gh.circle-artifacts.com/0/build/t430-maximized/heads-t430-maximized-v0.2.0-1058-gb9468f5.rom

Legacy t430 (not maximized. Not requiring to neuter ME per instructions:https://osresearch.net/Clean-the-ME-firmware/ nor unlocking IFD per same instructions.):
Top SPI initial external flashing: https://1546-103208611-gh.circle-artifacts.com/0/build/t430-flash/heads-t430-flash-v0.2.0-1058-gb9468f5-top.rom
Internal flashing: https://1533-103208611-gh.circle-artifacts.com/0/build/t430/heads-t430-v0.2.0-1058-gb9468f5.rom


Please report back!

**Comment by tlaurion** [comment]
x220 (xx20): @techge @eganonoa @shamen123 @Thrilleratplay @userongihu @BlackMaria
t420 (xx20): @alexmaloteaux @natterangell
t430 (xx30): @Thrilleratplay @alexmaloteaux @nickfrostatx @lsafd @bwachter @Trapacid
t430s and additional information (xx30): @Siproqu

Please tag me here if you [test the roms](https://github.com/osresearch/heads/pull/1015#issuecomment-894523907). 
Any input welcome.

Particularly:
txxx builds which applies https://github.com/osresearch/heads/pull/1015#issuecomment-894523907 and for #1004 which is unclear to have inpacts to x220 and t420 builds. Thanks for your participation. This won't be merged without feedback.

**Comment by Siproqu** [comment]
Will test it. Unfortunately I won't have access to my T430s in the next two days.

Aug 7, 2021 23:10:54 tlaurion ***@***.***>:

**Comment by tlaurion** [comment]
0Clean rebuild requested on CircleCI (changing CACHE_VERSION on CI) to test effectiveness of https://github.com/osresearch/heads/pull/1015/commits/b9468f5a13fc108c33b35425894cb1a9e39decd6

Of course, that will change the hashes of some binaries, per #1008 opened ticket. But reusing a cache based on a board using all current dependencies is expected to reduce build time on subsequent builds when cache is used (@Tonux599: small optimization there).

**Comment by techge** [comment]
I am willing to test my x220, but I am currently short of time and do not know yet, *when* I will get to it...

**Comment by tlaurion** [comment]
For USE_OPTION_TABLE, STATIC_OPTION_TABLE and on t430 : https://github.com/osresearch/heads/pull/944#issuecomment-886840825

The reasoning behind adding this and hardcoding higher gfx_uma_size configs should be discussed and added if needed, inside of this PR or later on to cover such use case,
> avph (Arthur Heymans, 9elements) I am driving a 3840x2160 (4K) external display and have replaced the internal one with a 1080p display. With or without the external display attached, when booting I saw graphical fragments over the text at the top of the screen (looked like random data in the video memory). Also when the OS was running I had strange issues that looked like random memory corruption. https://github.com/QubesOS/qubes-issues/issues/6227 After enabling gfx_uma_size=224M both effects are gone.

But:
> there is little to suggest this is needed for every T430 out there

@jans23 and team? Needed for T430?

**Comment by tlaurion** [comment]
Note that builds from cache now builds under 3 hours for all boards under CircleCI. This means, once again, that unless a module definition changes, the biggest cache matching created digest is reused to build. If all modules are consistent (no modification on those modules in past commit for current build, meaning only scripts have changed or a rebuild was asked) like in the previous build, a CircleCI build takes [2h30](https://app.circleci.com/pipelines/github/tlaurion/heads/758/workflows/a0275bdb-26ab-40a4-94eb-788cb186e292) instead of [3h40 ](https://app.circleci.com/pipelines/github/tlaurion/heads/755/workflows/374a3fac-d404-4252-bc0d-9e4c3cef6154). 

This is due by not having to build 3 versions of coreboot (4.8.1 is deprecated and moved to 4.13 here for all boards but KGPE-D16 still being based on coreboot 4.11) and having the most complex boards being built first where libraries and binaries being in the cache are reused instead of being recompiled for each boards.

**Comment by tlaurion** [comment]
@Siproqu let me know how #1017 went please. Really looking to have this mainstreamed at some point.
@techge @Thrilleratplay ?

**Comment by natterangell** [comment]
I’ve been traveling, but I should be able to test for the T420 this weekend.

**Comment by tlaurion** [comment]
> I’ve been traveling, but I should be able to test for the T420 this weekend.

@natterangell Awesome. Looking on your input here as second opinion of #1004.

**Comment by natterangell** [comment]
@tlaurion I've flashed the t420-hotp-maximized rom mentioned above (https://github.com/osresearch/heads/pull/1015#issuecomment-894523907, and everything seems to be working just fine.

The only difference I can see from the rom I built myself manually was some error message when booting:
IMG_0566
But it doesn't seem to cause any problem. Not sure if it's related to the NitroKey(?)

As for https://github.com/osresearch/heads/pull/998#issuecomment-891318955, my PCR-2 payload measurements remain the same after setting a new TOTP/HOTP.

After flashing the ROM initially (retaining settings), resetting TPM, new TOTP/HOTP
IMG_0567

After choosing to generate new TOTP from menu
IMG_0569

And no, I haven't experienced any TOTP/HOTP inconsistencies as mentioned in https://github.com/osresearch/heads/issues/1004. I'll update this if it should happen. No pending updates for dom0 at the moment.

**Comment by techge** [comment]
I am really sorry I could not test this so far. After realizing a broken keyboard on my x220 and losing time for this, I hadn't enough left to actually test the roms. I am still aware of this issue and would gladly help. It is just that I can not promise *when* I'll come to that. Let's say I try these days :grimacing:

**Comment by tlaurion** [comment]
@natterangell thanks for your test.


@Thrilleratplay @alexmaloteaux @nickfrostatx @lsafd @bwachter @daringer @jans23: I need the t430 tested. Any chance someone can commit to that?

**Comment by tlaurion** [comment]
x220 (xx20): @techge @eganonoa @shamen123 @Thrilleratplay @BlackMaria

The x220 still need testing. Direct links in comment of OP.

**Comment by Thrilleratplay** [comment]
@tlaurion Sorry, I am swamped with other projects I need to finish.  I'll try to but it won't be for a while.

**Comment by shamen123** [comment]
@tlaurion T430-maximised tested as follows

```
sha256sum heads-t430-maximized-v0.2.0-1058-gb9468f5-*.rom
23d0f07ab2de3980cfe32eecc46f4e10b747110249c5d4616176098418daf7b4  heads-t430-maximized-v0.2.0-1058-gb9468f5-bottom.rom
423c9fdf2ccb7b0d0a5acee51e17eb147ddc0959de010f71d575660e9178aee6  heads-t430-maximized-v0.2.0-1058-gb9468f5-top.rom
```
Flashed externally. Tested full process from blank installation (tpm ownership + GPG pubkey flash + TOTP + fresh Qubes install + luks key in TPM + GPG card/sign boot). All working good. 

I no longer have the x220 so can be removed from that list. I have x230 + t430

**Comment by tlaurion** [comment]
Rebuilding.... Since all artifacts direct links were deleted after 30 days...
https://app.circleci.com/pipelines/github/tlaurion/heads/758/workflows/7292c49d-de49-4615-a13f-ca98b5b80cd6

**Comment by BlackMaria** [comment]
@tlaurion  Sorry for the delays.
I just tested `heads-x220-maximized-v0.2.0-1058-gb9468f5.rom` everything works, including the OEM reset.

**Comment by techge** [comment]
Okay I finally tested `heads-x220-maximized-v0.2.0-1058-gb9468f5.rom` today. Good news! No brick :smile: I had problems signing files in /boot while using a pre-configured key (flashed into rom by heads). I saw the hdd indication led blinking, but nothing happening otherwise (the NK only flashing shortly and not more that would be needed to sign).

Afterwards I tested OEM reset with another NK (and thus erasing all and everything). This turned out the same.

I have to say, I am not aware what needs to be done, to make sure the *maximized* part of the rom is working correctly. And I do not know which state the installed coreboot was in either. I *think* it was a stripped off ME version, but you might give me a link to the instruction how to flash correctly for the maximized version in case there is something wrong in this regard.

**Comment by nitrosimon** [comment]
Hello
I did some testing of this PR for @jans23. For t430 flashing internally worked fine. Though I first tested it with an x230 because I had it at hand first and had no screen output. External screens also did not work. So I tried to flash it again externally and still had the same issue. Flashing an older version without this PR worked fine, so at least the device itself seems to be working. Yesterday a coworker tried it independently from me and had the same result. Sorry for the delayed feedback.

**Comment by MrChromebox** [comment]
I've flashed 4.13/4.14 hotp-maximized on my x230 as well (but not these specific artifacts), no issues

**Comment by tlaurion** [comment]
Rebasing on master for one last CI build and x230-hotp-maximized test run on my side prior of merging.
@nitrosimon confirmed his x230 issue was related to ME region being locked where other x230 owners confirmed no issue.

@nitrosimon you might want to confirm this and your deployment procedure, since upgrading to x230-hotp-maximized might be impossible for your users: the upgrade path might be limited to upgrading only the BIOS region through a non existing t430-hotp-verification (equivalent to the x230-hotp-verification board, which doesn't take for granted IFD and ME is neutered nor takes advantage of ME neutering freed space as opposed to hotp-maximized boards who does for internal flashing upgrades.) Consequently, x230-hotp-verification and to be created t430-hotp-verification boards will be limited in the future in terms of inclusion of other features and possible kernel upgrades, since, as you know, if ME is not neutered, or if we do not know the actual minimal space consumed by ME to be changed in IFD to give that freed space to the BIOS region under coreboot config, or if we cannot take for granted that ME+IFD is unlocked in current SPI prior of upgrade, then only 7.5MB of BIOS region is usable for coreboot+heads, as opposed to 11.5Mb for maximized builds. This is why https://osresearch.net/Clean-the-ME-firmware/ is important to be followed. And also why it is possible to upgrade from Skulls ONLY IF OPTIONAL IFD UNLOCKING STEP WAS FOLLOWED. And Why upgrading from 1vyrain is impossible (They do not unlock IFD at all, they can't).

@jan23 @nitrosimon @alex-nitrokey  Also note that going the t430-hotp-verification internal upgrade path (as opposed to hotp-maximized) won't touch the gbe blob (won't change original Ethernet MAC address). Consequently, you would continue to call the extract.sh script under blob dir to extract ifd, gbe and me, and keep the original MAC address for igb ethernet. This means that the ROM flashed to each laptop is unique, as opposed to maximized builds which has the same IFD, GBE blob (generated) and ME blob (verified coming from Lenovo website, cleaned, neutered (trimmed), with IFD matching the minimal ME size where BIOS region is maximized to hold 11.5mb of BIOS region under coreboot configuration.)  

Don't hesitate to poke me proivately if you need more information.

From past tests:
- x230t did not have keyboard problem anymore
- x230 keyboard is responsive upon reboot (fixes #765)
- Both QubesOS 4.0 and 4.1 boot and install (fixes #672 #789)

**Comment by tlaurion** [comment]
@nitrosimon : added t430-hotp-verification board, which downgrades to whiptail (non-fbwhiptail. So no red nor yellow background colors nor framebuffer support here, as documented for "Legacy" non-maximized boards [here](https://github.com/osresearch/heads/pull/1015#issuecomment-894523907)

**Comment by tlaurion** [comment]
This is building over [here](https://app.circleci.com/pipelines/github/tlaurion/heads/834/workflows/02d22842-4a0a-4a93-841f-fa25377d056a), rebased on master with NEWT fixes needed merged in a couple of minutes ago.

Should permit 1vyrain users to flash internally x230-flash and t430-flash, then x230-hotp-verification and t430-hotp-verification internally from there, and fix #1049

**Comment by tlaurion** [comment]
So the next build should produce artifacts here for t430-hotp-verification: https://app.circleci.com/pipelines/github/tlaurion/heads/835/workflows/0f27e698-086f-484e-8c0d-68bbe2f75a15

**Comment by tlaurion** [comment]
Bis....
So the next build should produce artifacts here for t430-hotp-verification: https://app.circleci.com/pipelines/github/tlaurion/heads/836/workflows/f51a2d51-f334-4a73-9baa-45d16c1d460fin 2h from now.

**Comment by tlaurion** [comment]
WiP documentation: https://github.com/osresearch/heads-wiki/pull/82/files?short_path=529f311#diff-529f311e8716c83389f3e386ff6b8e9a90113d07f137321554820739e2a7b81c

**Comment by icequbes1** [comment]
With the addition of a coreboot config change from https://github.com/osresearch/heads/issues/1057#issuecomment-975350244, as of commit 1f1539c6 in this PR for a `make BOARD=t430`: an already-existing Qubes R4.1 install booted fine.

The only heads issue encountered seems to be related to the Whiptail UI. During the factory OEM reset, the Resetting GPG Key step always failed with my Yubikey 5 and the screen just displayed an empty box with no message. The only thing to do is press [enter] to go back to the menu. But I suppose this is a separate issue as this PR only addresses a coreboot upgrade.

**Comment by 0xdd7fq** [comment]
@tlaurion can you renew links? thx

**Comment by tlaurion** [comment]
> @tlaurion can you renew links? thx after 30 days, all artifacts associated with a build automatically expire

Won't be long. CircleCI broke with new price plan #1058

**Comment by tlaurion** [comment]
@0xdd7fq the builds and artifacts for latest successfully built commit 8f9ccae is accessible by clicking on the green mark.
From there you see links for boards that were built, by name of boards which can be accessed from there.
And then once in CircleCI, going into the artifacts section gives access to what was produced for each board.

I would appreciate t420 and t430 board owners to retest roms:
t420 (xx20): @alexmaloteaux @natterangell @akfhasodh
t430 (xx30): @Thrilleratplay @alexmaloteaux @nickfrostatx @lsafd @bwachter @shamen123 @eganonoa(no dGPU)
Since https://github.com/osresearch/heads/pull/1015/commits/435677707455c095271aeeb3182386317b4f3950 was pushed to address https://github.com/osresearch/heads/issues/1057#issuecomment-980445082, and since dGPU/no dGPU can happen across t4xx, I would love to have report of board owners, which might affect #1059.

Example, all being done without being logged into Github nor CircleCI as you can see in the pictures (extracting links is not so fun where people can download for themselves!)

**Comment by tlaurion** [comment]
@icequbes1 report oem-factory-reset issue on the t430, which I cannot replicate, here: https://github.com/osresearch/heads/pull/1063

Someone else has an issue? I cannot replicate on x230 for commit 8f9ccae

**Comment by tlaurion** [comment]
> @tlaurion T430-maximised tested as follows
> 
> ```
> sha256sum heads-t430-maximized-v0.2.0-1058-gb9468f5-*.rom
> 23d0f07ab2de3980cfe32eecc46f4e10b747110249c5d4616176098418daf7b4  heads-t430-maximized-v0.2.0-1058-gb9468f5-bottom.rom
> 423c9fdf2ccb7b0d0a5acee51e17eb147ddc0959de010f71d575660e9178aee6  heads-t430-maximized-v0.2.0-1058-gb9468f5-top.rom
> ```
> 
> Flashed externally. Tested full process from blank installation (tpm ownership + GPG pubkey flash + TOTP + fresh Qubes install + luks key in TPM + GPG card/sign boot). All working good.


@shamen123 your T430 has a IGPU only or also a dGPU?
Other t430 board owners (iGPU only) had problems with past rom. The new builds include https://github.com/osresearch/heads/pull/1015/commits/435677707455c095271aeeb3182386317b4f3950 which I would love to receive your feedback as working/non-working, since other boards owners having iGPU only already confirmed that that commit fixed their issues (black internal screen while external display was working).

**Comment by walliams** [comment]
>     This is linked with issue [Can't get heads to boot on t430 #1057](https://github.com/osresearch/heads/issues/1057), where both @walliams and @icequbes1 confirmed there that this commit fixed their t430 blank screen issue without a dGPU (iGPU only). Both board owners seem to have issues using the oem-factory-reset 

@tlaurion just to clarify: my board is a dGPU t430, not iGPU-- the nvidia dGPU can be found under a second heatsink pad attached to the CPU heatsink/fan assembly. I believe @icequbes1 has iGPU only, but I cannot speak for them. I did not have any issue with the OEM reset either using the new build based on the hotp-maximized coreboot config you produced in #1057 . It is now running perfectly for me.

**Comment by tlaurion** [comment]
Now only missing a t420 board owner report from either @alexmaloteaux @natterangell @akfhasodh! 
Please please please! Report if iGPU/dGPU!

**Comment by tlaurion** [comment]
> dGPU

Thanks @walliams for your feedback. I updated https://github.com/osresearch/heads/issues/692 accordingly and can now confirm that t430 boards, with dGPU or iGPU only should now all function under #1015 which should be finally merged soon. 

If there is no report from t420 owners, life goes on and the problems reported will have to be corrected after bug reports.
Next step is #1061 and other boards needing to be merged and tested, including the Talos II and adding back other boards after having fixed #1058... And having new OSes being able to build Heads as covered with #1038.

**Comment by natterangell** [comment]
Hi!

Flashed **t420**-hotp-maximized from `8f9ccae` externally. TPM ownership, GPG pubkey flash, TOTP, Nitrokey all good!
Reflashed internally, retaining settings, everything seems to work just fine!

**Comment by natterangell** [comment]
For clarity: iGPU

**Comment by tlaurion** [comment]
@natterangell updated #692 accordingly.

Waiting for a t420 dGPU report until tomorrow and merging.

**Comment by tlaurion** [comment]
Fixes #1057

**Pull request merged**
