### PR TITLE
(WIP) Kgpe d16 current working

### PR DESCRIPTION
**Pull request by tlaurion**
Trying to get back QubesOS GUI installer to install QubesOS on a preflashed Heads system ([Mitigation of "LUKS volume creation error from QubesOS text-based installer WON'T FIX error"](https://github.com/osresearch/heads/issues/368#issuecomment-432093717))

### CODE REVIEW

**Comment by zifxify** [comment]
/heads/config/coreboot-kgpe-d16_server

CONFIG_PAYLOAD_FILE="../../build/kgpe-d16_server/bzImage"
CONFIG_LINUX_INITRD="../../build/kgpe-d16_server/initrd.cpio.xz"

/heads/config/coreboot-kgpe-d16_workstation

CONFIG_PAYLOAD_FILE="../../build/kgpe-d16_workstation/bzImage"
CONFIG_LINUX_INITRD="../../build/kgpe-d16_workstation/initrd.cpio.xz"

**Comment by tlaurion** [comment]
Thanks @zifxify. There is ast support in linux. I'm doing some tests and mods to whiptail so that the server/laptops with/without TPM/Nitrokeys work as intended.

I'm not sure there is really a need to seperate such boards if options are clearly defined in board config. If they are, i'll include your fixes!

**Comment by tlaurion** [comment]
Seperated the boards properly.

**Comment by tlaurion** [comment]
#712 followup.

- kgpe-d16_server board works with ASMBv4 baord receiving all terminal output, whcih should be controlled by ssh. (See commit messages)
- kgpe-d16_workstation is in WIP stage. Lost track of what was required, playing slowly with it. In current commit, AST was activated, while standard FB was deactivated. We try here to have AST_DRM so that FBwhiptail can fireup the gui-init instead of the generic-init.

**Comment by 0rb677** [comment]
@tlaurion need to enable onboard USB (doesn't work for previous versions). thanks for commit.

**Comment by tlaurion** [comment]
Why not PS2? 

Having USB on by default for keyboards opens up a lot et attack vectors and is not recommended.

On workstation? Server?
That would also require to punch holes under qubesos.

**Comment by 0rb677** [comment]
> Why not PS2?
> 
> Having USB on by default for keyboards opens up a lot et attack vectors and is not recommended.
> 
> On workstation? Server?
> That would also require to punch holes under qubesos.

How to boot USB drive without onboard ports? Only workstation. Maybe any users have USB keyboard/mouse. 

```
suxx@lab:~/Build/heads/config$ cat linux-kgpe-d16_workstation.config | grep AST
CONFIG_DRM_AST=y
```

**Comment by 0rb677** [comment]
@tlaurion cool its works with AST enabled. Still laggy, but works. No whiptail found.
```
unable to locate /boot files on any mounted disk
/bin/gui-init: line 141: whiptail: not found
!!!!! GUI menu failed
!!!!! Starting recovery shell
```

**Comment by tlaurion** [comment]
> > Why not PS2?
> > Having USB on by default for keyboards opens up a lot et attack vectors and is not recommended.
> > On workstation? Server?
> > That would also require to punch holes under qubesos.
> 
> Only Workstation.
> Sys-usb on Qubes - specially made for this?

https://www.qubes-os.org/doc/usb-devices/#using-usb-keyboards-and-other-input-devices
> 
> Edited. New Build. Everything works. Pike too.

I'm confused now. :P

**Comment by tlaurion** [comment]
@pkubaj @0rb677 @Tonux599 @zifxify : Please let me know the current state of this PR at this point.

You can find flashable artifacts for https://github.com/osresearch/heads/pull/472/commits/46b9c7948ab476069b3e670c63638355b45943bb by clicking the green check mark on the commit which will bring you to those roms from the artifacts tab:
[kgpe-d16_workstation](https://247-103208611-gh.circle-artifacts.com/0/build/kgpe-d16_workstation/coreboot.rom)
[kgpe-d16_server](https://247-103208611-gh.circle-artifacts.com/0/build/kgpe-d16_server/coreboot.rom)

**Comment by tlaurion** [comment]
@flammit : any objection on the server config? That was basically an upgrade of what was upstream with (plymouth fix for QubesOS) in board config and USB_COMPANION added.

**Comment by pkubaj** [comment]
I actually do not use heads, but pure coreboot 4.11 with SeaBIOS. I would be happy to test heads, but will I be able to boot FreeBSD with it? This is my primary operating system.

**Comment by tlaurion** [comment]
> I actually do not use heads, but pure coreboot 4.11 with SeaBIOS. I would be happy to test heads, but will I be able to boot FreeBSD with it? This is my primary operating system.

Since its kexec based, I do not think so in current situation but if things involved in that area, which I am not aware of. I'll remove you from the list of kgpe-d16 testers under heads for the moment then.

**Comment by 0rb677** [comment]
@tlaurion remove my comment. With heads now works only PS/2 keyboard.
I'm just really in a hurry all the time

**Comment by tlaurion** [comment]
@0rb677 pike support added in both boards following https://github.com/osresearch/heads/issues/712#issuecomment-640839757

**Comment by tlaurion** [comment]
As said previously, once yellow dot will turn into green check, you can download build there (without USB keyboard support: PR welcome)

**Comment by tlaurion** [comment]
@0rb677 : board addition for kgpe-d16_workstation-usb_keyboard with Pike support.

**Comment by tlaurion** [comment]
@0rb677 b22d913 built successfully while save_cache for cache failed (got lost in commits it seems).

Artifact is there and downloadable for new board config. Let me know how it goes.

**Comment by tlaurion** [comment]
@0rb677 please test  2e4f046 build's artifacts above when build is finished and report in original ticket I tagged you in so that it can be merged in master.

**Comment by 0rb677** [comment]
I will do it tomorrow.

**Comment by 0rb677** [comment]
@tlaurion 

DSC_0200

**Comment by tlaurion** [comment]
@0rb677 I would like you to launch said script from recovery shell.
`/bin/oem-factory-reset`

And screenshot what happened out of whiptail, from shell output.

**Comment by 0rb677** [comment]
> @0rb677 I would like you to launch said script from recovery shell.
> `/bin/oem-factory-reset`
> 
> And screenshot what happened out of whiptail, from shell output.

@tlaurion 

I dont understand it works with couple of bugs.
Now i attached gpg-card  and external USB to PC when heads initialized. Then quit to shell and lauch oem-reset script.

1. It access to gpg-card
2. It generates oem-key
3. It changes Admin/Pin
4. Exporting key to USB
5. Reading Firmware
6. Adding gerenerate key to current firmware and re-flashing
7. Signed boot files and generate checksums

So it works?

**Comment by 0rb677** [comment]
It works without TPM module. /boot is signed by oem-key
and rom re-flashed by oem-reset script and signed with gpg oem key too. So branch issue is complete

**Comment by tlaurion** [comment]
@0rb677 if you could confirm that flashable artifacts work for you on CI link for latest commit (https://circleci.com/gh/tlaurion/heads/292?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) it would be amazing since I need to have at least one approval to merge.

**Comment by tlaurion** [comment]
Per https://github.com/osresearch/heads/issues/692 collaborators, new images ready to test prior of having this branch merged upstream: https://app.circleci.com/pipelines/github/tlaurion/heads/274/workflows/ba5d9adb-d40e-415e-ae53-566cf85d7617/jobs/297

KGPE-D16 servers owners (@tlaurion @Tonux599 @zifxify), can you test: 
(gui-init with whiptail gui without FBWhiptail, being BMC friedly over console access):
https://297-103208611-gh.circle-artifacts.com/0/build/kgpe-d16_server-whiptail/coreboot.rom
(generic-init based)
https://297-103208611-gh.circle-artifacts.com/0/build/kgpe-d16_server/coreboot.rom

KGPE-D16 workstation owners (@0rb677 @Tonux599 @zifxify), can you test: 
Whiptail based, with/without usb keyboard support:
https://297-103208611-gh.circle-artifacts.com/0/build/kgpe-d16_workstation/coreboot.rom
https://297-103208611-gh.circle-artifacts.com/0/build/kgpe-d16_workstation-usb_keyboard/coreboot.rom

Thanks.
@flammit: the original kgpe-d16 board is now kgpe-d16_server (generic-init based)

**Comment by tlaurion** [comment]
This opens the door for upgrading the kgpe-d16 to coreboot 4.11 per future community work. See commit https://github.com/osresearch/heads/commit/5f067ea908c1c22855801bfe4d9ee4f07739241e for how to change coreboot to 4.11

Same logic should be applied to linux kernel upgrade, so that ASPEED integrated graphics becomes more fluid and could be changed per board when fully tested without breaking anything.

PRs always welcome, community.

**Comment by Tonux599** [comment]
@tlaurion will test and report back in the next 72 hours.

I can provide testing and maintain certain flavours of this board (TPM1.2, nouveau, amdgpu) but I lack enthusiasm until #740 is fixed. Lemme know if you have any progress with it, moved away from this board to X220 until #740 is fixed.

**Comment by Tonux599** [comment]
Apologies for the delay, only managed to test `kgpe-d16_workstation` and `kgpe-d16_server-whiptail`. Haven't got BCM flashed yet so didn't test `kgpe-d16_server`.

Anyway, tested with ASpeed onboard GPU results in boot messages being displayed for a few seconds but when graphics initialised VGA output is nothing but unusable glitched graphics. Think I read somewhere this is a kernel issue now? So will presumably function correctly with an updated kernel.

**Comment by tlaurion** [comment]
Now par with master. Comments welcome, build happening on PR, as always (green arrow on latest commit: https://github.com/osresearch/heads/pull/472/commits/e9895eb72efcdc0f6aff7097dad3961a8ce51672)

Leading to https://circleci.com/gh/tlaurion/heads/432?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

When build is ready, you can download roms per artifacts.

**Comment by tlaurion** [comment]
Effort continues here: https://github.com/osresearch/heads/pull/867

**Pull request closed without merging**
