### PR TITLE
kexec-save-default: guard TPM LUKS usage with config option

### PR DESCRIPTION
**Pull request by MrChromebox**
Move the TPM LUKS key storage to its own function instead of prompting users each time they save the default boot option.

### CODE REVIEW

**Comment by tlaurion** [comment]
I thought we agreed to put on option in board config to call it automatically for boards who use it.

**Comment by MrChromebox** [comment]
@tlaurion updated

**Comment by tlaurion** [comment]
@osresearch : which other boards should have this in?

**Comment by tlaurion** [comment]
@merge you ok with that?

**Comment by merge** [comment]
> @merge you ok with that?

since it doesn't change things for the x230 for example, I'm ok with that, yes

**Comment by tlaurion** [comment]
Would now miss other boards

**Comment by MrChromebox** [comment]
just the T420, right?

**Comment by tlaurion** [comment]
I'll check. It's hard to make an assumption. Best guest would be to apply to all boards having TPM support but librems.

On February 20, 2020 4:02:52 AM UTC, MrChromebox <notifications@github.com> wrote:
>just the T420, right?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/osresearch/heads/pull/625#issuecomment-588598280

-- Sent from /e/ Mail

**Comment by MrChromebox** [comment]
what do you think I did exactly? ;-)

the only boards with 'export CONFIG_TPM=y' outside of the librems are the x220, x230, and now t420

**Comment by tlaurion** [comment]
Sorry didn't look, thought server board would!

Okidoki! Just t420 :)

On February 20, 2020 4:15:52 AM UTC, MrChromebox <notifications@github.com> wrote:
>what do you think I did exactly? ;-)
>
>the only boards with 'export CONFIG_TPM=y' outside of the librems are
>the x220, x230, and now t420
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/osresearch/heads/pull/625#issuecomment-588600772

-- Sent from /e/ Mail

**Comment by MrChromebox** [comment]
should be good now :)

**Comment by MrChromebox** [comment]
@tlaurion rebased this on master, using your preferred config string, and no change for non-Librem boards. If preferred, we could reverse the config logic (eg, CONFIG_TPM_NO LUKS_UNLOCK) and have the Librems select it. Either way, a pretty simple change to review/merge

**Comment by tlaurion** [comment]
@MrChromebox : It would be preferable that the logic is inversed, so that Purism is responsible to maintain its boards to not use Heads Disk Unlock Key security feature, while all other community boards use it per Heads design.

**Comment by MrChromebox** [comment]
@tlaurion makes sense, I will reverse the logic and push an update

**Comment by MrChromebox** [comment]
@tlaurion logic reversed and patch rebased on Heads master

**Pull request merged**
