### PR TITLE
fix(functions): update checksums of filenames with spaces

### PR DESCRIPTION
**Pull request by Thrilleratplay**

### CODE REVIEW

**Comment by Thrilleratplay** [comment]
There are many instances in the Heads scripts but this is the only one I tested.

**Comment by tlaurion** [comment]
Proof of bug:
```
user@Spotify:~/Downloads$ ls
 This_is_a_filename_without_space.txt  'This is a filename with spaces.txt'
user@Spotify:~/Downloads$   find ~/Downloads/ -type f ! -name '*kexec*' | xargs sha256sum > /tmp/kexec_hashes.txt
sha256sum: /home/user/Downloads/This: No such file or directory
sha256sum: is: No such file or directory
sha256sum: a: No such file or directory
sha256sum: filename: No such file or directory
sha256sum: with: No such file or directory
sha256sum: spaces.txt: No such file or directory
user@Spotify:~/Downloads$ cat /tmp/kexec_hashes.txt
f93b1a9dae57a4b59d3fdc2d4f5df89747c46d33b910b035a545946a12567fa8  /home/user/Downloads/This_is_a_filename_without_space.txt
```

With suggested fix:
```
user@Spotify:~/Downloads$ find ./ -type f ! -name '*kexec*' -print0 | xargs -0 sha256sum > /tmp/kexec_hashes.txt
user@Spotify:~/Downloads$ cat /tmp/kexec_hashes.txt
19f8de0d75101159539e7faae35c334ee67ae84201f7f05bed7b3f1edda7535d  ./This is a filename with spaces.txt
f93b1a9dae57a4b59d3fdc2d4f5df89747c46d33b910b035a545946a12567fa8  ./This_is_a_filename_without_space.txt
user@Spotify:~/Downloads$ 
```

All calls of the following form are ok: 
```
user@Spotify:~/Downloads$ find ./ -name '*.txt' > /tmp/filelist.txt
user@Spotify:~/Downloads$ cat /tmp/filelist.txt
./This is a filename with spaces.txt
./This_is_a_filename_without_space.txt
```

Other places needing this fix (cleaned):
```
user@x230-tests:~/heads$ grep -Rn "find " initrd/
initrd/bin/oem-factory-reset:160:    find /boot -type f ! -name '*kexec*' \
initrd/bin/kexec-sign-config:30:		find ./ -type f ! -name '*kexec*' | xargs sha256sum > /boot/kexec_hashes.txt
```

So basically, all places passing result to `xargs sha256sum`:
```
user@x230-tests:~/heads$ grep -Rn "xargs sha256sum" initrd/ -b3 -a3
initrd/bin/oem-factory-reset-158-3869-
initrd/bin/oem-factory-reset-159-3870-    # generate hashes
initrd/bin/oem-factory-reset-160-3892-    find /boot -type f ! -name '*kexec*' \
initrd/bin/oem-factory-reset:161:3935:        | xargs sha256sum > /boot/kexec_hashes.txt 2>/dev/null \
initrd/bin/oem-factory-reset-162-4000-        || whiptail_error_die "Error generating kexec hashes"
initrd/bin/oem-factory-reset-163-4062-
initrd/bin/oem-factory-reset-164-4063-    param_files=`find /boot/kexec*.txt`
--
initrd/bin/oem-factory-reset-234-6236-
initrd/bin/oem-factory-reset-235-6237-    # validate boot option
initrd/bin/oem-factory-reset-236-6264-    ( cd /boot && /bin/kexec-boot -b "/boot" -e "$entry" -f \
initrd/bin/oem-factory-reset:237:6326:        | xargs sha256sum > $hash_file 2>/dev/null ) \
initrd/bin/oem-factory-reset-238-6381-        || whiptail_error_die "Failed to create hashes of boot files"
initrd/bin/oem-factory-reset-239-6451-}
initrd/bin/oem-factory-reset-240-6453-
--
initrd/bin/kexec-sign-config-27-458-if [ "$update" = "y" ]; then
initrd/bin/kexec-sign-config-28-487-	( 
initrd/bin/kexec-sign-config-29-491-		cd /boot
initrd/bin/kexec-sign-config:30:502:		find ./ -type f ! -name '*kexec*' | xargs sha256sum > /boot/kexec_hashes.txt
initrd/bin/kexec-sign-config-31-581-		if [ -e /boot/kexec_default_hashes.txt ]; then
initrd/bin/kexec-sign-config-32-630-			DEFAULT_FILES=$(cat /boot/kexec_default_hashes.txt | cut -f3 -d ' ')
initrd/bin/kexec-sign-config:33:702:			echo $DEFAULT_FILES | xargs sha256sum > /boot/kexec_default_hashes.txt
initrd/bin/kexec-sign-config-34-776-		fi
initrd/bin/kexec-sign-config-35-781-	)
initrd/bin/kexec-sign-config-36-784-
--
initrd/bin/kexec-save-default-123-2862-rm $paramsdir/kexec_default.*.txt 2>/dev/null || true
initrd/bin/kexec-save-default-124-2916-echo "$entry" > $ENTRY_FILE
initrd/bin/kexec-save-default-125-2944-cd $bootdir && kexec-boot -b "$bootdir" -e "$entry" -f | \
initrd/bin/kexec-save-default:126:3003:	xargs sha256sum > $HASH_FILE \
initrd/bin/kexec-save-default-127-3035-|| die "Failed to create hashes of boot files"
initrd/bin/kexec-save-default-128-3082-if [ ! -r $ENTRY_FILE -o ! -r $HASH_FILE ]; then
initrd/bin/kexec-save-default-129-3131-	die "Failed to write default config"
grep: initrd/etc/mtab: No such file or directory
```

**Comment by tlaurion** [comment]
@Thrilleratplay please review and apply the additional patch to your PR (take ownership, don't care):
```
diff --git a/initrd/bin/kexec-sign-config b/initrd/bin/kexec-sign-config
index 1f8a6d7..6ecff1a 100755
--- a/initrd/bin/kexec-sign-config
+++ b/initrd/bin/kexec-sign-config
@@ -27,7 +27,7 @@ confirm_gpg_card
 if [ "$update" = "y" ]; then
        ( 
                cd /boot
-               find ./ -type f ! -name '*kexec*' | xargs sha256sum > /boot/kexec_hashes.txt
+               find ./ -type f ! -name '*kexec*' -print0 | xargs -0 sha256sum > /boot/kexec_hashes.txt
                if [ -e /boot/kexec_default_hashes.txt ]; then
                        DEFAULT_FILES=$(cat /boot/kexec_default_hashes.txt | cut -f3 -d ' ')
                        echo $DEFAULT_FILES | xargs sha256sum > /boot/kexec_default_hashes.txt
diff --git a/initrd/bin/oem-factory-reset b/initrd/bin/oem-factory-reset
index 17b3dce..b55ba95 100755
--- a/initrd/bin/oem-factory-reset
+++ b/initrd/bin/oem-factory-reset
@@ -157,8 +157,8 @@ generate_checksums()
     set_default_boot_option
 
     # generate hashes
-    find /boot -type f ! -name '*kexec*' \
-        | xargs sha256sum > /boot/kexec_hashes.txt 2>/dev/null \
+    find /boot -type f ! -name '*kexec*' -print0 \
+        | xargs -0 sha256sum > /boot/kexec_hashes.txt 2>/dev/null \
         || whiptail_error_die "Error generating kexec hashes"
 
     param_files=`find /boot/kexec*.txt`
 
```

**Comment by Thrilleratplay** [comment]
@tlaurion These changes look good. 

*  `initrd/bin/kexec-sign-config` change is far less likely to occur and if there are spaces in kexec filenames there may be issues else where.
*  `initrd/bin/oem-factory-reset`, I should have included that change in the PR but was not sure if how to test it.

**Comment by tlaurion** [comment]
@Thrilleratplay : add those and sign commit and i'll merge.

**Comment by Thrilleratplay** [comment]
@tlaurion The other instance I was thinking of was `initrd/bin/kexec-save-default` but is not used with `find` and did not feel comfortable changing it as it could create other bugs.  The version of `/initrd/bin/kexec-sign-config` is different than master, you may want to make that update on your current branch locally.  I updated `initrd/bin/oem-factory-reset` and signed off.

**Comment by tlaurion** [comment]
@Thrilleratplay please resolve conflict rebased on master and will merge

**Comment by Thrilleratplay** [comment]
@tlaurion Done.

**Pull request merged**
