### PR TITLE
Add DEBUG statements in code and fix "sh: argument expected"

### LINKED ISSUE #1316: sh: argument expected
## Please identify some basic details to help process the report

"sh: argument expected" appears pretty often

### A. Provide Hardware Details

**1. What board are you using (see list of boards [here](https://github.com/eganonoa/heads/tree/master/boards))?**

**2. Does your computer have a dGPU or is it iGPU-only?**
- [ ] dGPU
- [ ] iGPU-only

Thinkpad X230

**3. Who installed Heads on this computer?**
- [ ] Insurgo
- [ ] Nitrokey
- [ ] Purism
- [X] Other provider
- [ ] Self-installed

Got this box from @tlaurion :100: 

**4. What PGP key is being used?**
- [ ] Librem Key
- [X] Nitrokey Pro 2
- [ ] Nitrokey Storage
- [ ] Yubikey
- [ ] Other

**5. Are you using the PGP key to provide HOTP verification?**
- [ ] Yes
- [X] No
- [ ] I don't know

### B. Identify how the board was flashed

**1. Is this problem related to updating heads or flashing it for the first time?**
- [ ] First-time flash
- [ ] Updating heads 

**2. If the problem is related to an update, how did you attempt to apply the update?**
- [ ] Using the Heads GUI
- [ ] Flashrom via the Recovery Shell
- [ ] External flashing

**3. How was Heads initially flashed**
- [ ] External flashing
- [ ] Internal-only / 1vyrain
- [X] Don't know

**4. Was the board flashed with a maximized or non-maximized/legacy rom?**
- [X] Maximized
- [ ] Non-maximized / legacy
- [ ] I don't know

**5. If Heads was externally flashed, was IFD unlocked?**
- [ ] Yes
- [ ] No
- [X] Don't know

### C. Identify the rom related to this bug report

**1. Did you download or build the rom at issue in this bug report?**
- [ ] I downloaded it
- [ ] I built it

**2. If you downloaded your rom, where did you get it from?**
- [ ] Heads CircleCi
- [ ] Purism
- [ ] Nitrokey
- [X] Somewhere else (please identify)

pre-installed, FW_VER says CBET4000 Heads-v0.2.0-1359-g411ca09

*Please provide the release number or otherwise identify the rom downloaded*

**3. If you built your rom, which repository:branch did you use?**
- [ ] Heads:Master
- [ ] Other (please identify)

**4. What version of coreboot did you use in building?**
- [ ] 4.8.1 (current default in heads:master)
- [ ] 4.13
- [ ] 4.14
- [ ] 4.15
- [ ] Other (please specify)
- [X] I don't know

**5. In building the rom where did you get the blobs?**
- [ ] No blobs required
- [ ] Provided by the company that installed Heads on the device
- [ ] Extracted from a backup rom taken from this device
- [ ] Extracted from another backup rom taken from another device (please identify the board model)
- [ ] Extracted from the online bios using the automated tools provided in Heads
- [X] I don't know

## Please describe the problem

**Describe the bug**

New user, I have run factory reset and during the operation at a very late stage I got "sh: argument expected" displayed.
After this, factory reset completed successfully.

Now it appears in gui-init before first menu pops up:

````
******* Normal boot: /bin/gui-init
Unable to localte /boot files on any mounted disk
sh: argument expected
````

OEM factory reset complained about missing LUKS partition (because there isn't any) but otherwise all seemed to proceed well.

**To Reproduce**

Just boot the machine

**Expected behavior**

This error message should not appear

I am sorry for the unhelpful report, but although I consider myself a pretty competent shell programmer, I can't pinpoint the location of the possible error :(

### PR DESCRIPTION
**Pull request by tlaurion**
As noted under #1316, it is sometimes difficult to isolate source of errors/diagnose problems.

This PR introduces:
- DEBUG and TRACE function under /etc/functions
- Adds TRACE statements under functions
- Adds 'export CONFIG_DEBUG_OUTPUT=y' and 'CONFIG_ENABLE_FUNCTION_TRACING_OUTPUT=y' under board config to enable DEBUG and TRACE console output in code to trace source of error.
- DEBUG calls will be possible later on to provide more debugging as needed as we go (thinking of #1292)
- [ ] Fixes #1316 

---

In current debugging state, we can see that reported #1316 can be isolated under:

### CODE REVIEW

**Comment by tlaurion** [comment]
A little bit clearer. Also permits newcomers to simply enable DEBUG in board configs to see trace of function calls

**Comment by tlaurion** [comment]
So prior of main gui-init loop

**Comment by tlaurion** [comment]
While  5d30c2b is the actual fix.

@JonathonHall-Purism let me know what you want to do with that introduced bug!

**Comment by tlaurion** [comment]
Tested: 
- [ ] With and without export CONFIG_DEBUG_CONSOLE
- [ ] Needs Librem testing (bug showed when $CONFIG_AUTO_BOOT_TIMEOUT not exposed) (@JonathonHall-Purism )

**Comment by tlaurion** [comment]
Using [x230-hotp-maximized from CircleCI builds ]( https://app.circleci.com/pipelines/github/tlaurion/heads/1482/workflows/cef37b15-f415-4993-b8b8-1b4ac572c6d9) as of now. Nothing to report as of now as regression.

**Comment by tlaurion** [comment]
Latest commit gives following output when 'export CONFIG_ENABLE_FUNCTION_TRACING_OUTPUT=y' enabled under board config



@JonathonHall-Purism ready for merging?

**Comment by JonathonHall-Purism** [comment]
This looks great, thanks let's merge :+1:

**Pull request merged**
