### PR TITLE
x230-htop-verification: coreboot CBFS_SIZE changed to 0x710000

### PR DESCRIPTION
**Pull request by tlaurion**
as per https://github.com/osresearch/heads/pull/748/files#diff-540d604c350e8fd52c25559b642795fbR5

Adresses: https://github.com/osresearch/heads/issues/737#issuecomment-646991153

### CODE REVIEW

**Comment by alex-nitrokey** [comment]
This is already included in #748 and can be merged there as soon it is ready (should be later this day).

Or do you want to merge this to master and I merge it in my PR instead?

**Comment by tlaurion** [comment]
@alex-nitrokey : some users had weird behavior. Will test this change with others and reply back

**Comment by tlaurion** [comment]
This fix alone is tested and works and will be merge with #748 tested currently with other Nitrokey PRs

**Comment by tlaurion** [comment]
#748 is not mergeable as it is now since not reproducible. Merging this one so that x230-hotp-verification board can work again,

**Pull request merged**
