### PR TITLE
(WiP) xx20 boards: add xx20-hotp-maximized & remove HOTP and NITROCLI support from xxx0-maximized boards

### PR DESCRIPTION
**Pull request by tlaurion**
- xx20-maximized boards were supporting HOTP by error. This adds the xx20-hotp-maximized boards and removes HOTP support from xx20-maximized boards for coherence with the xx30-maximized boards.
- Add those boards to CircleCI.

@Thrilleratplay should be that originally I guess, where you can't test hotp right?

Also unsure if NKSTORAGECLI should be here, since they needed to be removed under https://github.com/tlaurion/heads/commit/00c2ffffade493e17edf6a93b1f6970c01d23719 for https://app.circleci.com/pipelines/github/tlaurion/heads/648/workflows/337f0829-e3e9-47aa-85b1-1e10a9199e54/jobs/696 to build (cryptsetup2 support for future #789 support since LUKS2 at default install)

~~Doesn't build as of right now, since boards configs declare cryptsetup2 dependency.~~ EDIT: removed dependency to cryptsetup2. Should not be linked issues.

### CODE REVIEW

**Comment by Thrilleratplay** [comment]
@tlaurion I do not have a Nitrokey/LibremKey so I was not able to test this.  I only included them to match xx30 boards.

**Comment by tlaurion** [comment]
@Thrilleratplay which is why I seperated this into xx30 as well. Now xx20-maximized builds do not contain HOTP (which you can test) and xx20-htop which you can't. Merge?

**Comment by tlaurion** [comment]
As a side note, I would go forward and remote NKSTORECLI inside of those board configs also, reducing future maintenance of those boards (nobody wants NKSTORECLI by default). I will go forward and we wil lbe able to use those two builds to compare size difference.

That would close https://github.com/osresearch/heads/issues/926#issuecomment-743793731 with one stone.

**Comment by Thrilleratplay** [comment]
@tlaurion I understand that but `CONFIG_HOTPKEY=y` was taken from [x230-maximized](https://github.com/osresearch/heads/blob/master/boards/x230-maximized/x230-maximized.config#L39). If it is being removed from the xx20-maximized boards, they should also removed from the xx30-maximized boards.  I assume would be the same for `CONFIG_NKSTORECLI=y` in xx30-maximized and xx20-maximixed boards.

If doing so allows for enough room for cryptsetup2 to be installed in the xx20-maximized boards and does not take away any functionality, then I would suggest doing so for the xx30-maximized boards too.  This will keep them functionally the same for now.

**Comment by tlaurion** [comment]
Agreed. pushing. Will create a x230-PrivacyBeast for my own needs adding this in I guess instead of using the xx30-htop-maximized.

**Pull request merged**
