### PR TITLE
add Nitropad NV41/NS50 TPM2 boards (2nd)

### PR DESCRIPTION
**Pull request by daringer**
This is the continuation PR, originating from: #1417
Mainly adds the CI related fixes from here: #1469
The Nitrokey 3 support is extracted into this PR: #1483 

CircleCI builds are also activated

### CODE REVIEW

**Comment by daringer** [comment]
rebased on top of master

**Comment by tlaurion** [comment]
You can confirm NV41/NS50 ROMs works as expected on the images produced by Circleci?

**Comment by nestire** [comment]
Hi,
circle ci build work for ns50/nv41:
Tested:
- oem-factroy-reset
- Booting Ubuntu 22.04 and Qubes 4.1.2
- Nitrokey 3 and Nitrokey Pro 2

**Comment by tlaurion** [comment]
Thanks for Nlnet for supporting this part of the work https://nlnet.nl/project/HEADS-TPM2.0/#ack

**Pull request merged**
