### PR TITLE
t430-hotp-verification board addition

### PR DESCRIPTION
**Pull request by tlaurion**
- Adds support for Nitrokey Pro 2/Nitrokey Storage 2 / Librem Key USB Security dongles for remote attestation of TPM measurements through HOTP.
- Adds board config in CIs

### CODE REVIEW

**Comment by tlaurion** [comment]
@flawedworld: have a Librem Key / Nitrokey Pro 2/ Nitrokey Storage 2 to test this with? 
(Might need to be adapted if https://github.com/osresearch/heads/pull/761 gets merged first to change LIBREMKEY with HOTP_KEY in board config)

**Comment by flawedworld** [comment]
Yeah I can try to get this working. Will report back soon.

**Comment by tlaurion** [comment]
Now requires this addition in board config:
https://github.com/osresearch/heads/pull/776/files#diff-7e9abf6ddbc48cef5d1b1e08a9ad0afcR3

**Comment by tlaurion** [comment]
oups haha, thats my PR. changing it now for you to test.

**Comment by tlaurion** [comment]
#1015 merged

**Pull request closed without merging**
