### PR TITLE
merge dgpu-t430 configs

### PR DESCRIPTION
**Pull request by walliams**
sourced from eganonoa/heads and edited. conflicts should be resolved now

### CODE REVIEW

**Comment by tlaurion** [comment]
@walliams ! Awesome, t430-dgpu owners will be happy (where documentation on disassembling and supported platforms is totally out of date in regard of w530 t530 in wiki and users confused that only x230 i documented.)

I would love to see a at least a reference in the boards configs to the blobs  required/included in the coreboot configurations, otherwise hidden under coreboot configuration file alone, also a pointer to the script that is required to be ran to have the blobs put in place, and a reference to the README in the blobs dir, even more if that needs to have nvramutil ran to configure things properly (might not be, i'm still not super knowledgeable about the dgpu requirements and mix dgpu requirements myself of the lately added dgpu boards)? 

@walliams : since you are owner of all those boards, are you up to drafting some documentation updates, at least in regard to this t430-dgpu additional board support ?

https://osresearch.net/Contributing-to-Heads-wiki/

Affected links:
- https://osresearch.net/Building/
- https://osresearch.net/Flashing-guides
- https://osresearch.net/Prerequisites#supported-devices

**Comment by walliams** [comment]
happy to help with documentation on xx30-dgpu models as my next task. didn't notice that even the existing dgpu configs lack reference to vbios blob scripts... that could be improved. i can work on that as well.

also, any clue why the circleci check failed here? i didn't change anything related to the x230, though these boards do reference x230-hotp-maximized in .circleci/config.yml

**Comment by tlaurion** [comment]
@walliams please rebase on master.... CircleCI is failing for race conditions, I have to kick the builds on merging... This is annoying but will change when updating coreboot and linux kernels....

**Comment by tlaurion** [comment]
Houla.

git fetch master
git rebase master
git commit --amend 

Should be an empty commit.
Otherwise we will have to rebase dynamically after, you should not merge master in your branch.

Now we have an undesired commit in this branch :/

**Comment by walliams** [comment]
o darn. sry i'm new to this. do i need to setup a github desktop cli or something

**Comment by walliams** [comment]
i can just close this and redo my branch. i don't want to create any more work for anyone else

**Comment by tlaurion** [comment]
> git fetch master
> git rebase master
> git commit --amend

Those are from command line?

**Comment by walliams** [comment]
i'm just confused about doing this from cli... i forked the repo and edited this all in browser.

**Comment by tlaurion** [comment]
Curious, what are you using right now?

**Comment by walliams** [comment]
just github.com web interface, via firefox. is this something i can do here, or do i need to clone to a local repo and run commands? 
or now that i accidentally merged master downstream is it too late or can i reverse the commit and rebase as you suggest? or better off just wiping my repo, rebuild starting from updated master and merge code from eganonoa again?

sorry. am git noob

**Comment by walliams** [comment]
i mean i build heads in a debian vm, with manually inserted code for the t430-dgpu, but my fork and PR here were all done on the web interface because the only git commands i know are clone and pull.

**Comment by walliams** [comment]
i'll just make a new PR once i figure out what i'm doing. thanks for the pointers

**Comment by tlaurion** [comment]
Well, I can quickly fix this, create a PR.

**Pull request closed without merging**
