### PR TITLE
Talos II : add TPM module as under dasharo

### PR DESCRIPTION
**Pull request by tlaurion**
- Made to match https://github.com/Dasharo/coreboot/commit/2207bbcccba31ad89cf21607b0d8d05d8dc47c03

### CODE REVIEW

**Comment by tlaurion** [comment]
Hopefully this will fix https://github.com/3mdeb/talos-tpm-module/issues/2 and https://github.com/Dasharo/dasharo-issues/issues/272

**Comment by tlaurion** [comment]
Note that measurements are made in bootblock but cached in memory and actually reported by ramstage. 
So ramstage is actually talking to TPM, not bootblock.

**Comment by tlaurion** [comment]
Builds happening under https://app.circleci.com/pipelines/github/tlaurion/heads/1275/workflows/c1d5c877-f009-4a5b-9497-261de3035663

**Comment by tlaurion** [comment]
Basically, heads was using

```
user@heads-tests:~/heads/build/ppc64/coreboot-git$ grep -i tpm .config

    # CONFIG_TALOS_2_INFINEON_TPM_1 is not set

    CONFIG_CRB_TPM_BASE_ADDRESS=0xfed40000

    # CONFIG_MAINBOARD_HAS_CRB_TPM is not set

    # CONFIG_MAINBOARD_HAS_I2C_TPM_ATMEL is not set

    # CONFIG_MAINBOARD_HAS_I2C_TPM_CR50 is not set

    # CONFIG_MAINBOARD_HAS_I2C_TPM_GENERIC is not set

    # CONFIG_DRIVER_I2C_TPM_ACPI is not set

    # CONFIG_MAINBOARD_HAS_LPC_TPM is not set

    # CONFIG_MAINBOARD_HAS_SPI_TPM_CR50 is not set

    # CONFIG_MAINBOARD_HAS_SPI_TPM is not set

    CONFIG_USER_NO_TPM=y
```
    - Ok, config in Heads was not as [https://github.com/Dasharo/coreboot/commit/](https://github.com/Dasharo/coreboot/commit/2207bbcccba31ad89cf21607b0d8d05d8dc47c03)[2207bbcccba31ad89cf21607b0d8d05d8dc47c03](https://github.com/Dasharo/coreboot/commit/2207bbcccba31ad89cf21607b0d8d05d8dc47c03)

With this config:
```
user@heads-tests:~/heads/build/ppc64/coreboot-git$ grep -i tpm .config

    CONFIG_DRIVER_TPM_I2C_BUS=0x02

    CONFIG_DRIVER_TPM_I2C_ADDR=0x20

    CONFIG_TALOS_2_INFINEON_TPM_1=y

    CONFIG_CRB_TPM_BASE_ADDRESS=0xfed40000

    # CONFIG_MAINBOARD_HAS_CRB_TPM is not set

    CONFIG_TPM_INIT_RAMSTAGE=y

    CONFIG_I2C_TPM=y

    # CONFIG_MAINBOARD_HAS_I2C_TPM_ATMEL is not set

    # CONFIG_MAINBOARD_HAS_I2C_TPM_CR50 is not set

    CONFIG_MAINBOARD_HAS_I2C_TPM_GENERIC=y

    # CONFIG_DRIVER_I2C_TPM_ACPI is not set

    # CONFIG_DRIVER_TPM_DISPLAY_TIS_BYTES is not set

    # CONFIG_MAINBOARD_HAS_LPC_TPM is not set

    # CONFIG_MAINBOARD_HAS_SPI_TPM_CR50 is not set

    # CONFIG_MAINBOARD_HAS_SPI_TPM is not set

    CONFIG_TPM1=y

    CONFIG_MAINBOARD_HAS_TPM1=y

    # CONFIG_TPM_DEACTIVATE is not set

    # CONFIG_DEBUG_TPM is not set

    CONFIG_TPM_MEASURED_BOOT=y

    CONFIG_TPM_MEASURED_BOOT_SPEC_LOG=y

    CONFIG_TPM_MEASURED_BOOT_RUNTIME_DATA=""
```

In community meeting notes:
- Looks good, with TPM actually initialized in ramstage and where bootblock measurements are cached and reported in the same order by ramstage (not bootblock)

**Comment by tlaurion** [comment]
@SergiiDmytruk : if anything else is missing outside of this PR to have TPM support on your side working, please steal my change and point to another PR with anything else currently missing under Heads master to support TPM module correctly.

https://github.com/osresearch/heads/commit/d0ef7e8c1fb8c4be8847b1c9167e6d1214749613 was not including the coreboot config requirement, so I'm not quite sure how you functionally tested positively with same TPM module board revision as I have received.

Having something known working on your side would be a good base for testing. As you know my TPM module seems bricked/shorted, which is not discoveered, as discussed under https://github.com/Dasharo/dasharo-issues/issues/272

**Comment by macpijan** [comment]
> I'm not quite sure how you functionally tested positively with same TPM module board revision as I have received.

v0.6.0 release of firmware from https://docs.dasharo.com/variants/talos_2/releases/#v060-2022-08-26 was used for testing the TPM module initially AFAIK. We will retest again with the revisions provided by you in this report: https://github.com/Dasharo/dasharo-issues/issues/272#issuecomment-1329233127

**Comment by SergiiDmytruk** [comment]
@tlaurion The release was built by https://github.com/Dasharo/dasharo/ from https://github.com/Dasharo/coreboot/commit/2207bbcccba31ad89cf21607b0d8d05d8dc47c03 (Heads uses the same commit). The thing to note is that build script there compiles coreboot on its own and ignores coreboot built by Heads. So there should be no other changes necessary.

@macpijan By the way, TPM changes were merged for release only and are still not in the development branch for Talos-2. It seemed weird that release contained changes absent from the develop, but I thought there would be a merge later and there wasn't as of now. Just reminding that next release should take this into account in some way.

**Comment by tlaurion** [comment]
> @macpijan By the way, TPM changes were merged for release only and are still not in the development branch for Talos-2. It seemed weird that release contained changes absent from the develop, but I thought there would be a merge later and there wasn't as of now. Just reminding that future releases should take this into account in some way.

@macpijan just pinging to make sure the above is noted somewhere.
Merging this so that builds of Heads reflects the current TPM situation covered in other tickets, waiting for TPM module documentation and posible fixes. 

As of this merge, Heads coreboot configuration under Talos reflects https://github.com/Dasharo/coreboot/commit/2207bbcccba31ad89cf21607b0d8d05d8dc47c03

Main issue is under https://github.com/Dasharo/dasharo-issues/issues/272, missing TPM module installation/orientation documentation and I still cannot test TPM support since module is not functional/undetected.

**Pull request merged**
