### PR TITLE
flash.sh: Add progress bar

### PR DESCRIPTION
**Pull request by MrChromebox**
Show progress of flashrom reads/writes when flashing by means
of a progress bar, adapted from the Librem coreboot flashing script.

Also provides a time-stamped flashrom log in /tmp to aid diagnosis in the
event that a firmware update fails.

Signed-off-by: Matt DeVillier <matt.devillier@puri.sm>

### CODE REVIEW

**Comment by MrChromebox** [comment]
updated with some error suppression for `seq` since occasionally it would puke around 99%/1%

**Comment by MrChromebox** [comment]
resulting output (hopefully this works):

flashrom progress bar

**Comment by MrChromebox** [comment]
@flammit can you review / test on top of flashrom 1.2 please?

**Comment by tlaurion** [comment]
Adding gpg key and flash resulted in a 171% flashing progress at 100%.
Same when reapplying ROM with settings on a ROM where BIOS region of size of 7100000 is applied.

@MrChromebox

**Comment by MrChromebox** [comment]
I'll take a look at this tomorrow or day after, didn't test w/ '--ifd -i BIOS' but shouldn't make a difference...hmm

**Comment by tlaurion** [comment]
@MrChromebox sorry for bad picture, was a race condition.
signal-2020-06-28-170310

**Comment by MrChromebox** [comment]
@tlaurion think I fixed it, but can't reproduce so will need you to re-test

**Comment by MrChromebox** [comment]
> Result is the same as before and seems to be caused per BIOS region only being flashed, not whole flash.

ok, I'll modify one of my devices here to only flash BIOS region and see if I can reproduce/resolve

**Comment by tlaurion** [comment]
@MrChromebox

**Comment by MrChromebox** [comment]
@tlaurion will look into this coming week

**Comment by MrChromebox** [comment]
@tlaurion I'm not able to reproduce this anomaly you're seeing, even on my x230. The Total flash size reflects the size of the BIOS region (~12MB on x230-hotp-maximized) and the counter never runs past 100%. Can you retry with a fresh build?

**Comment by tlaurion** [comment]
It works with maximized builds because opaque 12mb is taken into calculation. 

Problem arises for boards not flashing the whole combined space. That is, if --ifd --image bios is specified

**Comment by tlaurion** [comment]
@mrchromebox: One thing I miss is the ability that we had from the console to see that the image that is attempted to be flashed equals what is already on the SPI flash. Good news is, reflashing the same rom that is on SPI should keep the HOTP and TOTP values consistent if keeping settings. So should not be a problem.

Tested working as of now:
- x230-hotp-verification. Report is good and doesn't go over 100% even if for legacy boards, only the BIOS region is asked to be flashed. Initial size shown is of 12mb though, but then only the BIOS region is considered for internal, non-displayed calculations, but it works. Reflashing same firmware over also keeps TOTP/HOTP valid.
- x230-hotp-maximized: same! Reflashing same firmware over also keeps TOTP/HOTP valid.

@MrChromebox : should we still say, explicitely, to the user if the rom flashed is the same that is on SPI?
Otherwise, ready to merge.

**Comment by tlaurion** [comment]
@MrChromebox actually, looking closer at the code, there is supposed to be a confirmation saying that the [rom is identical](https://github.com/osresearch/heads/pull/658/files#diff-e33f7a1603ea94b6a0ff385404e9860ff48e1c5afe2ed5c8e68207d3b39186ccR81), which I never got. Might want to look into that

**Comment by MrChromebox** [comment]
@tlaurion that part of the code is indeed working, which can be verified by flashing the same ROM from the recovery shell twice in a row: 
PXL_20211217_211732016

Flashing the same ROM as is running on the system currently will not generate the 'identical image' message because the RW_MRC_CACHE coreboot FMAP region is populated with the RAM training data on the first boot after flashing (or if the RAM modules change), and when flashing a new ROM, that data is cleared.

**Comment by tlaurion** [comment]
@MrChromebox Perfect, thanks for the reminder. 
RW_MRC_CACHE will always be different from initial flash from trained memory updated data.

So that goes to relaying into HOTP/OTP to confirm that internally/externally flashed rom is the same as it was before.

Merging!

**Pull request merged**
