### PR TITLE
Support Thinkpad W541

### PR DESCRIPTION
**Pull request by gaspar-ilom**
allows building heads for the w541 based on the t440p which has a sufficiently similar architecture.

I tested this with my the blobs from the test board and did not encounter any issues so far.

### CODE REVIEW

**Comment by tlaurion** [comment]
@gaspar-ilom please duplicate config from either x230 or t440p under .circleci/config.yml

Board needs to build first prior of code review.

**Comment by tlaurion** [comment]
@gaspar-ilom Also test 5.10.5 config that just got merged and rebase please

**Comment by tlaurion** [comment]
You might want to rebase on master, lots of changes happened.
Also address previous comments so CircleCI builds which you should test outcome and confirm working.

@gaspar-ilom thanks!

**Comment by gaspar-ilom** [comment]
Thanks for you reply. I will do that. Unfortuantely, it will take some time as I am currently quite busy.

**Comment by gaspar-ilom** [comment]
I rebased, added the circleci config and tested the hotp build on the device. I did not encounter any issues yet. Also, I added the blobs which are extracted from the original rom on my board. I set the MAC address in both `gbe.bin` parts to `00:de:ad:c0:ff:ee` using nvmutil.

Please take a look at the code and let me know which changes I should make. I copied most of the config from the 440p. However, I am not sure, what is your preferred way to manage such shared configs. So if there is some documentation you can refer me to I would appreciate it.

**Comment by gaspar-ilom** [comment]
> I rebased, added the circleci config and tested the hotp build on the device. I did not encounter any issues yet. Also, I added the blobs which are extracted from the original rom on my board. I set the MAC address in both `gbe.bin` parts to `00:de:ad:c0:ff:ee` using nvmutil.
> 
> Please take a look at the code and let me know which changes I should make. I copied most of the config from the 440p. However, I am not sure, what is your preferred way to manage such shared configs. So if there is some documentation you can refer me to I would appreciate it.
> 
> If preferred I can also squash the branch to a single commit.

I did just squash the branch

**Comment by tlaurion** [comment]
Duplicate of #1500?

**Comment by gaspar-ilom** [comment]
> Duplicate of #1500?

Yes, both PRs are pretty much the same. This one is rebased on master, is the main difference. I would love to see either PR merged into master. What need to be fixed for that to happen?

**Comment by tlaurion** [comment]
@gaspar-ilom I will review tomorrow thoroughly

**Comment by tlaurion** [comment]
Note:
@resende-gustavo and @gaspar-ilom owners of board to be added under #692

**Comment by tlaurion** [comment]
Added missing librem boards in op

**Comment by tlaurion** [comment]
Added @resende-gustavo and @gaspar-ilom as w541 board owners in op

**Pull request merged**
