### PR TITLE
Fix X220 and T420 CBFS sizes

### PR DESCRIPTION
**Pull request by SebastianMcMillan**
Add some room in the CBFS to actually save GPG keys, as well as have room to add libremkey support on libremkey-enabled builds. As of right now, they cannot save GPG keys due to the lack of space. Addresses #690.

We cannot simply revert the sizes due to the 50 second delay being seemingly related to the CBFS size being too large.

The values provided here do work on my T420 and X220, do not cause said delay, and will enable GPG keys being saved as well as libremkey support presumably working on libremkey-enabled builds (someone with one needs to test to confirm it, I get all the prompts and such, I just don't have a libremkey to test if behavior is as expected).

### CODE REVIEW

**Comment by tlaurion** [comment]
@SebastianMcMillan https://github.com/osresearch/heads/pull/568#issuecomment-596995130

**Comment by eganonoa** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Well re the bios, I was using a modified version of UEFI 1.46 and ECP 1.24. This is the latest Bios for the x220 (27 Jun 2018) and will have no further updates. So I think you can comfortably move forward with the understanding that the latest Bios is the one to use.                                                                                                                                                                           From: notifications@github.comSent: 10 March 2020 19:20To: heads@noreply.github.comReply to: reply@reply.github.comCc: ralphbunche@gmail.com; mention@noreply.github.comSubject: Re: [osresearch/heads] Fix X220 and T420 CBFS sizes (#693)  @SebastianMcMillan  @eganonoa  #568 (comment)
Once again. Most updated Lenovo BIOS update needs to be applied, providing consistent original Intel ME, needs to present to extract consistent blobs and offer the same IFD/CBFS regions. The guideline referred here is in goal of having consistent upgradeable CBFS regions (required to flash internally, which means only reflashing the BIOS section determined by coreboot in CBFS configuration section of coreboot config which needs to match IFD descriptor in blob).
If we go with a first, required, externally flashed coreboot containing well carved CBFS region, containing modified IFD blob (expended) and neutered+deactivated ME(reduced maximally), then Heads provided flash scripts could be modified in next ROM upgrade to flash whole ROM images, not only --ifd --image bios region. That would permit maximal available and usable space for all Heads needs for a board, in a reproducible manner (thorugh #307 acceptance of plan)
Else, we are stuck at using consistent CBFS sizes that would match ifd original descriptor size and CBFS regions matching non-neutered ME. Hope I made this point clear this time.
This same situation will be valid for all Ivy/Sandy bridges without mrc, fsp and fully neutered Intel ME (no syslib, no kernel in ME), while to a wider extent, to all existing and future coreboot Intel board inclusion (and probably AMD too, we'll see) in Heads with less freeable space in ME and less available space in Coreboot since relying on more required blobs to be present for initialization of hardware.
All those concerns should probably be in another ticket. I'll cherrypick those later on.

**Comment by tlaurion** [comment]
@SebastianMcMillan @eganonoa : See https://github.com/osresearch/heads/issues/690#issuecomment-600006494

**Comment by SebastianMcMillan** [comment]
@tlaurion you able to review this and merge the changes? My X220 and T420 were both on latest stock firmwares and this the size in this PR are as high as they can go for now. Further work will need to be done to maximize the space of these systems, but that'll be a ways away, and as of right now they don't even function in master, so this is better than nothing.

**Pull request merged**
