### PR TITLE
required changes to apply on top of osresearch/gpg2 

### PR DESCRIPTION
**Pull request by tlaurion**
Upgraded tools and libs to latests versions.
Added a gpg_agent.conf file pointing to /bin/scdaemon
Added gpg2 config under x230 board

### CODE REVIEW

**Comment by tlaurion** [comment]
@osresearch @flammit: see here for a [building alternative to gpg-agent.conf](https://github.com/osresearch/heads/pull/454#issuecomment-426862149)

**Comment by tlaurion** [comment]
Still have some problems with pinentry.

Trying to debug with the following changes with fbwhiptail in:

diff --git a/initrd/bin/flash-gui.sh b/initrd/bin/flash-gui.sh
index 191d977..3494ea7 100755
--- a/initrd/bin/flash-gui.sh
+++ b/initrd/bin/flash-gui.sh
@@ -183,7 +183,7 @@ while true; do
           if (cbfs -o /tmp/gpg-gui.rom -l | grep -q "heads/initrd/.gnupg/pubring.gpg") then
             cbfs -o /tmp/gpg-gui.rom -d "heads/initrd/.gnupg/pubring.gpg"
           fi
-          cbfs -o /tmp/gpg-gui.rom -a "heads/initrd/.gnupg/pubring.gpg" -f /.gnupg/pubring.gpg
+          cbfs -o /tmp/gpg-gui.rom -a "heads/initrd/.gnupg/pubring.gpg" -f /.gnupg/pubring.kbx
 
           if (cbfs -o /tmp/gpg-gui.rom -l | grep -q "heads/initrd/.gnupg/trustdb.gpg") then
             cbfs -o /tmp/gpg-gui.rom -d "heads/initrd/.gnupg/trustdb.gpg"
diff --git a/initrd/bin/kexec-sign-config b/initrd/bin/kexec-sign-config
index 1ff9f46..538c45e 100755
--- a/initrd/bin/kexec-sign-config
+++ b/initrd/bin/kexec-sign-config
@@ -49,7 +49,7 @@ if [ -z "$param_files" ]; then
 fi
 
 for tries in 1 2 3; do
-       if sha256sum $param_files | gpg \
+       if sha256sum $param_files | gpg --debug-all \
                --digest-algo SHA256 \
                --detach-sign \
                -a \

**Comment by tlaurion** [comment]
@jandryuk @duncanguthrie: any insights?

**Comment by osresearch** [comment]
I'll pull this into #454

**Comment by tlaurion** [comment]
@osresearch : works [here](https://github.com/tlaurion/heads/tree/x230-current-working-FBWhiptail_required_changes-gpg2)

**Pull request merged**
