### PR TITLE
TOTP code mismatch: better guidelines in code

### PR DESCRIPTION
**Pull request by tlaurion**
Fixes https://github.com/osresearch/heads-wiki/issues/103 

@JonathonHall-Purism : comments?
Also note that we should maybe cover with one rock (two birds) https://github.com/osresearch/heads/issues/1266

### CODE REVIEW

**Comment by tlaurion** [comment]
GUI Results in:


Console output results in:



Then some issues resulting in "Alarm clock" as reported under https://dev.archive.openwrt.org/ticket/14541

Which if we removed -q option for ntpd would go forever:


Let's remember that network-init-recovery tried to do ntp sync with router, based on DNS provider (router) first, and then tries to talk to ntp.pool.org first resolving address through DNS, then talking to it through NTP. Through my setup (qemu under Qubes appvm) ntp (UDP) doesn't succeed).

@JonathonHall-Purism : we could document further on command line the process if needed for network-init-recovery:
- First: address is attempted to be obtained dynamically through DHCP locally, etting DNS server from response
- Second: NTP sync is attempted on DNS server provided by DCP response.
- Third: if NTP against DNS server fails, ntp.pool.org is attempted to be resolved and then NTP sync is attempted on IP address (UDP). Might be firewalled.

Thoughts?

**Comment by JonathonHall-Purism** [comment]
Regarding the immediate change, it is certainly an improvement, I've had to help people a handful of times to deal with RTC resets.

I don't think we need to spell out everything `network-init-recovery` does.  I think it'd be pretty verbose and would probably distract from the more important information.

Re: #1266, per discussion in Matrix channel, if we can avoid the problem entirely (not increment the counter when the HOTP dongle isn't present), I think that'd be much better than more gotchas and warnings.

**Comment by tlaurion** [comment]
#1266 needs more thought. To be dealt individually.

@JonathonHall-Purism merge this one?

**Comment by JonathonHall-Purism** [comment]
Yep merge it, thanks :ship:

**Pull request merged**
