### PR TITLE
generic boot cleanup

### PR DESCRIPTION
**Pull request by flammit**
Starting a PR to clean up a bunch of issues with the `generic-init` boot.  So far addresses the #223 and fixing the extra / when tab-completing and manually running the scripts.  I assumed the `show_menu` parameter to `kexec-select-boot` was created to force showing the menu and avoid using the default parameters, so that was added as well.

### CODE REVIEW

**Comment by flammit** [comment]
After an OS install, setting the default boot entry also asks if you wish to add the TPM LUKS key, so this can now all be done from boot menu (w/o having to go to recovery shell).

It also reboots automatically after resign/reseal using the `/proc/sysrq-trigger` method.

**Comment by flammit** [comment]
PTAL - hopefully these address your remaining open boot issues (looks like you already handled issue #221).

**Comment by osresearch** [comment]
`reboot` and `poweroff` are definitely missing!  On qemu the busybox ones don't actually reboot and the sysrq technique seems to hang.  I need to test it on real hardware today -- I've been waiting on a fresh chipclip to be able to reflash my bricked x230.

**Comment by flammit** [comment]
I should add that this branch includes the updates to Qubes 3.2/Xen 4.6.6-29 to cover the latest Qubes Security Bulletin (issue #238)

**Pull request merged**
