### PR TITLE
Revert "Add new board: Purism Librem Mini"

### PR DESCRIPTION
**Pull request by tlaurion**
Reverts osresearch/heads#806

Build fails. https://app.circleci.com/pipelines/github/tlaurion/heads/365/workflows/c32c3e29-f383-43b1-9ffe-5b5968c7feaf/jobs/393

Cause of revert documented here: https://github.com/osresearch/heads/pull/806#issuecomment-686159584

### CODE REVIEW

**Comment by tlaurion** [comment]
https://app.circleci.com/pipelines/github/tlaurion/heads/364/workflows/df9bad8d-8ff1-40da-b8d8-1b87a05be509/jobs/392 succeeded because the cache of build 381 was restored https://app.circleci.com/pipelines/github/tlaurion/heads/364/workflows/df9bad8d-8ff1-40da-b8d8-1b87a05be509/jobs/392/parallel-runs/0/steps/0-106 from https://app.circleci.com/pipelines/github/tlaurion/heads/353/workflows/c4b5ba57-3246-4d02-87e1-6e097315ccc3/jobs/381

Rebuilding with a new CACHE_VERSION (so no restore from any cache) here: https://app.circleci.com/pipelines/github/tlaurion/heads/364/workflows/12ae254e-b1f5-4dd5-9e01-d53a4c70c608/jobs/396 prior of reverting tomorrow.

**Comment by MrChromebox** [comment]
I don't see the sense in reverting a board addition just because of CI issues -- we certainly wouldn't drop any other existing board for that. Just means that fixing CI needs to be prioritized.

**Comment by flammit** [comment]
I agree with @MrChromebox.  If local builds work, then we should keep the board.  It sounds like CI needs to be fixed to match real-world build conditions, which can be on any number of distros that should all build to the same byte-for-byte binary (how it was in the past).

**Comment by tlaurion** [comment]
> It sounds like CI needs to be fixed to match real-world build conditions, which can be on any number of distros that should all build to the same byte-for-byte binary (how it was in the past).

It is the same. We changed from musl-cross to musl-cross-make which is linked to current kernel reproducibility issue. 

@MrChromebox I will close this PR and create another one,  removing librem_mini from circleci

As always, your help in fixing gitlabci and circleci is more then welcome. They download rocker images, download build required tools and do what they are asked to do the same way it should happen locally. Please review.

**Comment by MrChromebox** [comment]
so is it a docker issue then? I've never used docker in any capacity whatsoever

**Comment by tlaurion** [comment]
> so is it a docker issue then? I've never used docker in any capacity whatsoever

I will test later on on local docker image downloaded from the same source and test software deployed under CircleCI recipe. But this is not one of my priority for the moment, unfortunately.

**Pull request closed without merging**
