### PR TITLE
Fixing i915 FB corruption with other OSes FB

### PR DESCRIPTION
**Pull request by tlaurion**
Fixing i915 FB on x230 to boot ISOs and debian kernels, permitting to deal with graphical LUKS passphrase requests and the like. 

There is a lateral flip of a millisecond still, [just like when booting QubesOS](https://github.com/osresearch/heads/issues/219#issuecomment-318857229).

### CODE REVIEW

**Comment by tlaurion** [comment]
Fixes #215

**Comment by paulmenzel** [comment]
Could you please update the commit message to describe why your changes 
fix the issue?

**Comment by flammit** [comment]
I've tested x230 on the master branch and it boots up all the distros that I would expect to work (Ubuntu, Debian, Fedora, Tails, Qubes).  I've also booted to Ubuntu, Fedora with the disk encryption and I get the graphical display prompt just fine.

@tlaurion If you're trying to enable i915 by default on x230, then yes you need to add the extra parameters to the boot kernel and the target kernel adjust the iommu settings (though I thought `iommu-igfx=off` was safer than `iommu=pt`).  However, maybe it's worth having a `x230-gui` board config that has these changes along with `gui-init` by default?

**Comment by merge** [comment]
This indeed fixes #215 for me too. Instead of testing this PR directly, I steal the necessary parts off of this fix and updated #465 accordingly which now boots cleanly as expected.

**Comment by tlaurion** [comment]
@flammit: why iommu=pt is considered less safe?
@merge @flammit:  I was merging flammit/i915 branch in my tests the past. Completely forgot about it recently. My bad. Merged those changes in my PR. Will close.

So here is what worked/still works:
[boards/x230-gui/x230.config](https://github.com/tlaurion/heads/blob/x230-FB-Tests/boards/x230/x230.config): 
`export CONFIG_BOOT_KERNEL_ADD="intel_iommu=on intel_iommu=igfx_off"`

[config/coreboot-x230.config](https://github.com/tlaurion/heads/blob/x230-FB-Tests/config/coreboot-x230.config):
```
CONFIG_NO_GFX_INIT=y
CONFIG_LINUX_COMMAND_LINE="intel_iommu=igfx_off quiet"
```

[config/linux-x230.config](https://github.com/tlaurion/heads/blob/x230-FB-Tests/config/linux-x230.config):
`CONFIG_DRM_I915=y`
(Getting rid of a lot of unneeded lines that were linked to generic framebuffer that I never got to work anyway.)

**Comment by tlaurion** [comment]
@merge : As pointed out by flammit, #480 now contains his flammit/i915 branch which fixed the issue but was never merged.

**Comment by merge** [comment]
@tlaurion thanks for your updates. I've shamelessly included them in #465 which I hope to be the minimal necessary change for switching to gui-init on the x230.

**Comment by tlaurion** [comment]
CLosing in favor of #465

**Pull request closed without merging**
