### PR TITLE
Make 4.2.1, hashes, external coreboot crossgcc, circleci and other fixes

### PR DESCRIPTION
**Pull request by osresearch**
This enables make 4.2.1 on ubuntu 18.04 (#352), adds hashes of built images (#455), speeds up circleci builds by using an external coreboot crossgcc (#162). There is now a dockerhub image for ubuntu 16.04: https://hub.docker.com/r/osresearch/heads-ubuntu/ with musl-gcc and coreboot gcc. Builds like https://circleci.com/gh/osresearch/heads/28 seem to work.

### CODE REVIEW

**Comment by hugelgupf** [comment]
Nice. Can you commit the dockerfile that built the image, too?

**Comment by tlaurion** [comment]
@osresearch : Any reason why this wasn't merged yet?

[Latest builds fails](https://circleci.com/gh/osresearch/heads/51) on your CI:
```
'standard output': Resource temporarily unavailable
tail /root/project/build/log/musl-cross.log
-----
+ btool=x86_64-musl-linux-readelf
+ [ x86_64-linux-musl-readelf != x86_64-musl-linux-readelf -a ! -e x86_64-musl-linux-readelf ]
+ ln -s x86_64-linux-musl-readelf x86_64-musl-linux-readelf
+ echo x86_64-linux-musl-size
+ sed s/-linux-musl/-musl-linux/
+ btool=x86_64-musl-linux-size
+ [ x86_64-linux-musl-size != x86_64-musl-linux-size -a ! -e x86_64-musl-linux-size ]
+ ln -s x86_64-linux-musl-size x86_64-musl-linux-size
+ echo x86_64-linux-musl-strings
+ sed s/-linux-musl/-musl-linux/
+ btool=x86_64-musl-linux-strings
+ [ x86_64-linux-musl-strings != x86_64-musl-linux-strings -a ! -e x86_64-musl-linux-strings ]
+ ln -s x86_64-linux-musl-strings x86_64-musl-linux-strings
+ echo x86_64-linux-musl-strip
+ sed s/-linux-musl/-musl-linux/
+ btool=x86_64-musl-linux-strip
+ [ x86_64-linux-musl-strip != x86_64-musl-linux-strip -a ! -e x86_64-musl-linux-strip ]
+ ln -s x86_64-linux-musl-strip x86_64-musl-linux-strip
+ exit 0
make[1]: Leaving directory '/root/project/build/musl-cross-git'
make: *** [Makefile:356: /root/project/build/musl-cross-git/.build] Error 1
Exited with code 2
```

**Comment by cawilliamson** [comment]
I've just built heads using this patch and it worked flawlessly for me on Ubuntu 18.04 as promised.

With that in mind - I think it's probably time to get this one merged! +1

**Comment by tlaurion** [comment]
@flammit @kylerankin : should we merge?
I tried to contact @nemanjan00 and @osresearch so that their docker images are updated without any feedback. I'm building with fedora-29 without any issues.

**Comment by tlaurion** [comment]
@osresearch @flammit @hugelgupf @kylerankin @cawilliamson :
If there is no opposition, i'll merge that PR next week.

**Pull request merged**
