### PR TITLE
exclude gnupg keyring files from revision control

### PR DESCRIPTION
**Pull request by persmule**
Since gnupg and ssh keyring files are highly user-specific, they should not be
managed with revision control system, otherwise they can cause trouble
when rebasing.

### CODE REVIEW

**Comment by flammit** [comment]
Maybe include /.ssh/authorized_keys too?

**Comment by persmule** [comment]
@flammit 
Just amended.

**Comment by osresearch** [comment]
Those files should move into the currently unimplemented and unspecified non-volatile user partition.  Which we should figure out how to make it work for coreboot and linuxboot, on both real hardware and qemu.

**Comment by osresearch** [comment]
This was merged as part of #357, right?

**Pull request closed without merging**
