### PR TITLE
WiP: Update coreboot to version 4.9

### PR DESCRIPTION
**Pull request by JeffreyAbbinante**
Once measured boot is in, rework the patches so that Heads can use it.

### CODE REVIEW

**Comment by JeffreyAbbinante** [comment]
Not done! I need to update the checksums!

**Comment by JeffreyAbbinante** [comment]
Vanilla coreboot 4.9 boots fine. Looking into getting the patches working.

**Comment by merge** [comment]
could you squash the 2 commit into 1 and rename the commit message title to something like "update coreboot to 4.9", and add https://doc.coreboot.org/releases/coreboot-4.9-relnotes.html to the commit message?

also, please add on which hardware you booted it.

thanks!

**Comment by tlaurion** [comment]
@merge : this is far from being ready. Measured boot is not in 4.9 yet. Verified boot is, and measured boot is a subfeature of it. 

Unfortunately, the release notes are misleading.

**Comment by JeffreyAbbinante** [comment]
Hey guys,

I apologize but I am extremely busy with school right now. I am a computer engineering student at a large state university and that is taking most of my time. I hope to eventually help you all again when I can. However, I do not exactly know when that will be. Hopefully in April when I am off. I did not realize that measured boot was not in 4.9 either. I can squash the two commits and change the commit message soon for you all.

Good Luck,

Jeffrey

**Comment by tlaurion** [comment]
please refer to #515

**Pull request closed without merging**
